### ISSUE TITLE
pg_probackup usage regarding centralized repository and cloning

### ISSUE THREAD

**Issue by pinakesh** [postgrespro/pg_probackup#100]
Hi Team,

I have below two queries on pg_probackup usage, kindly suggest.

1> Is using a centralized backup repository possible with pg_probackup?

2> Is it possible to clone a cluster using backup files and archived wall files till the latest committed transaction? i.e. cloning a cluster using latest backup files and archived wals created after the latest backup. (from standby server, I am using archive_mode=always and streaming replication)

Regards,
Pinakesh

**Comment by gsmol** [comment]
Hello!

> 1> Is using a centralized backup repository possible with pg_probackup?
>
Sure, look into documentation:
https://github.com/postgrespro/pg_probackup/blob/master/Documentation.md#adding-a-new-backup-instance
https://github.com/postgrespro/pg_probackup/blob/master/Documentation.md#using-pg_probackup-in-the-remote-mode

2> Is it possible to clone a cluster using backup files and archived wall files till the latest committed transaction? i.e. cloning a cluster using latest backup files and archived wals created after the latest backup. (from standby server, I am using archive_mode=always and streaming replication)
>
What do you mean by 'cloning' ? Restore from backup?

**Comment by pinakesh** [comment]
Hi,

Thanks for responding.

By 'cloning' I mean creating a new cluster (eg DEV_DB - for Development team's use) from the backup of an existing and running production cluster (eg. PROD_DB) (backup taken from standby of PROD_DB) so that the DEV_DB will have all the committed transactions of PROD_DB (committed till the time pg_probackup 'restore'/'or something else' command was run)...is it possible using pg_probackup?

**Comment by gsmol** [comment]
Sure, it is just ordinary restore with PITR to, I presume, remote host.

**Comment by pinakesh** [comment]
Thanks again.

I am trying to take backup on a Remote Server (Server03cn) from Standby Server (Server03cn) and for FULL backup it is working fine but for PAGE backup it is failing with the error message ::-

"ERROR: Switched WAL segment 0000000100000002000000AA could not be archived in 300 seconds"

On Repo server I added instance as below ::-
--------------------------------------------------

pg_probackup-11 add-instance -B /u02/pb/postgres/pg_pro_backupdir/ --remote-proto ssh --remote-host Server04cn.netcracker.com --remote-port 22 --remote-path /usr/bin/ -D /u02/pb/postgres/pg_pro_stby_server --instance pg_repo

On Standby's postgresql.conf
----------------------------------
archive_mode = always

archive_command = 'pg_probackup-11 archive-push -B /u02/pb/postgres/pg_pro_backupdir/ --instance pg_repo --wal-file-path %p --wal-file-name %f --remote-proto ssh --remote-host Server03cn.netcracker.com --remote-port 22 --remote-path /usr/bin/'


Error Log (on standby)
--------------------------
2019-07-24 04:21:59.468 EDT [27221] LOG:  entering standby mode
2019-07-24 04:21:59.476 EDT [27221] LOG:  redo starts at 2/AA000028
2019-07-24 04:21:59.476 EDT [27221] LOG:  consistent recovery state reached at 2/AB000000
2019-07-24 04:21:59.477 EDT [27220] LOG:  database system is ready to accept read only connections
2019-07-24 04:21:59.501 EDT [27226] LOG:  started streaming WAL from primary at 2/AB000000 on timeline 1
2019-07-24 04:22:38.348 EDT [27300] ERROR:  function pgpro_edition() does not exist at character 8
2019-07-24 04:22:38.348 EDT [27300] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2019-07-24 04:22:38.348 EDT [27300] STATEMENT:  SELECT pgpro_edition()
2019-07-24 04:22:40.276 EDT [27300] WARNING:  aborting backup due to backend exiting before pg_stop_backup was called
2019-07-24 04:22:40.276 EDT [27322] LOG:  unexpected EOF on standby connection
2019-07-24 04:22:46.831 EDT [27356] ERROR:  function pgpro_edition() does not exist at character 8
2019-07-24 04:22:46.831 EDT [27356] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


Please can you help?

**Comment by gsmol** [comment]
1. Can you provide the exact `backup` cmdline you are running ?

2. Please run following query on standby:
`select * from pg_stat_archiver, pg_last_wal_replay_lsn()`

**Comment by gsmol** [comment]
btw, following parameters are redundant, because default values are exactly the same:

--remote-port 22
--remote-proto ssh

**Comment by pinakesh** [comment]
Hi,

Please find backup command ran on Repo server (Server03cn ) below ::

[postgres@Server03cn postgres]$ pg_probackup-11 backup -B /u02/pb/postgres/pg_pro_backupdir/ --instance pg_repo -p 15432 -b PAGE --stream
INFO: Backup start, pg_probackup version: 2.1.2, backup ID: PV58M8, backup mode: page, instance: pg_repo, stream: true, remote true
WARNING: This PostgreSQL instance was initialized without data block checksums. pg_probackup have no way to detect data block corruption without them. Reinitialize PGDATA with option '--data-checksums'.
INFO: Wait for LSN 2/AA000028 in archived WAL segment /u02/pb/postgres/pg_pro_backupdir/wal/pg_repo/0000000100000002000000AA
ERROR: Switched WAL segment 0000000100000002000000AA could not be archived in 300 seconds
WARNING: Backup PV58M8 is running, setting its status to ERROR
WARNING: backup in progress, stop backup
[postgres@Server03cn postgres]$


Output of given query
-------------------------

[postgres@Server04cn ~]$ psql -p 15432
psql (11.0)
Type "help" for help.

postgres=# \x
Expanded display is on.
postgres=#
postgres=# select * from pg_stat_archiver, pg_last_wal_replay_lsn();
-[ RECORD 1 ]----------+------------------------------
archived_count         | 0
last_archived_wal      |
last_archived_time     |
failed_count           | 0
last_failed_wal        |
last_failed_time       |
stats_reset            | 2019-07-24 04:21:59.478047-04
pg_last_wal_replay_lsn | 2/AB000000

postgres=#


Thanks.

**Comment by gsmol** [comment]
There is no WAL coming from master, so no archiving is happening. No archiving means no way to compute a pagemap of changed blocks for PAGE backup. You have to force archiving on replica, so either generate some writes on master, or set archive_timeout parameter on master.

**Comment by pinakesh** [comment]
Oh okk, but in Primary I was running continuous log switch like this ::-

[postgres@Server02cn postgres]$  while [ 1 ]; do psql -p 15432 -c "select pg_switch_wal();"; sleep 5; done

I will try inserting around 1GB of data on primary and at the same time start backup from repo server.

**Comment by pinakesh** [comment]
Hi,

Thanks, it worked now.

I started inserting data on primary and PAGE backup was successful on Repo server.

Just curious, what will happen if PAGE incremental backup is scheduled at midnight and there is very less activity on prod server?

**Comment by gsmol** [comment]
> I started inserting data on primary and PAGE backup was successful on Repo server.
>
Glad to hear.

> Just curious, what will happen if PAGE incremental backup is scheduled at midnight and there is very less activity on prod server?
>
Well, for PAGE backup only archiving of segment with START LSN is mangatory, because pagemap based on WAL from  START LSN of previous backup to START LSN of current PAGE backup.
So you can mitigate the problem of low WAL traffic via several ways:
1. Use `--stream` flag when taking PAGE from standby
2. Set archive_timeout setting on master and make it slightly lower than pg_probackup parameter `--archive-timeout` (default 5 minutes)

**Comment by gsmol** [comment]
> WARNING: This PostgreSQL instance was initialized without data block checksums. pg_probackup have no way to detect data block corruption without them. Reinitialize PGDATA with option '--data-checksums'.
>
I would recommend to enable block checksumms, if you care about your data.

Do you have any more questions?

**Comment by gsmol** [comment]
Can we close this issue?

**Comment by pinakesh** [comment]
Sure..thanks
