### ISSUE TITLE
multiple typos

### ISSUE THREAD

**Issue by gsmol** [postgrespro/pg_probackup#101]
```
algorihtms
algrorithm
authentithication
backupd
baskup
bufer
calagoue
Checnge
Concatinate
concurrect
containig
corrup
Culd
cutted
decmpress
descendats
destionation
deteremine
direcory
Direcotry
directoties
dissappearance
ecovery-target-lsn
Eeach
erroneus
extention
```

**Comment by alexanderlaw** [comment]
nitalize
Interate
intstance
knowning
lastest
licence
Licence
Linix
musted
Nonpositive
Nothig
occures
Сonsequentially (с русской С)
Orphinize
otherwize
pg_pprobackup
poiter
Prevous
promts
recevied
remmaped
resquested
retreieved
Retreive
Retreived
Revaliate
sparsing
stding
symbolik
symbolink
syncronised
tablespaceses
test_arhive_ ...
unpriviledged
_vaidate_
toto ?
transfered
transfering
tusual
uncommited
uncompressable
verion
wich

**Comment by gsmol** [comment]
What's wrong with using 'sparsing' ?

**Comment by alexanderlaw** [comment]
> What's wrong with 'sparsing' ?
Perhaps, it makes some sense, but I couldn't understand what it means.

**Comment by gsmol** [comment]
Fixed.
