### ISSUE TITLE
archive-host-* options for restore command 

### ISSUE THREAD

**Issue by gsmol** [postgrespro/pg_probackup#102]
To provide values for --remote-* and --ssh-options settings for archve-get when restoring ARCHIVE backup or performing PITR additional options for `restore` are required.

**Comment by gsmol** [comment]
It is probably easier to just provide single option for setting restore_command: --restore-command

**Comment by gsmol** [comment]
New options:
1. `--restore_command=restore_command_cmdline`, can be used to set restore_command during restore. If `--restore_command` is set then `--archive-*` options are ignored.
2. `--archive-host=destination` provides value for `--remote-host` parameter in restore_command.
3. `--archive-port=port` provides value for `--remote-port` parameter in restore_command.
4. `--archive-port=user` provides value for `--remote-user` parameter in restore_command.

Do we need the `--archive-ssh-options` parameter?

**Comment by gsmol** [comment]
TODO: tests

**Comment by alubennikova** [comment]
The code looks fine.

- struct ArchiveOptions needs a comment.
- help.c and documentation must be updated to reflect new options.

**Comment by gsmol** [comment]
Merge with master, added test.

**Comment by gsmol** [comment]
> The code looks fine.
> 
> * struct ArchiveOptions needs a comment.
Done

> * help.c and documentation must be updated to reflect new options.
Done

**Comment by gsmol** [comment]
Merged.
