### ISSUE TITLE
Crash 2.1.5 под Windows во время выполнения бэкапа

### ISSUE THREAD

**Issue by ykurenkov** [postgrespro/pg_probackup#107]
2.1.5 валится при выполнении бэкапа. Команда show при этом выполняется нормально. Поведение одинаково при бэкапе на локальную NTFS и на CIFS.

![image](https://user-images.githubusercontent.com/25895491/62445077-12b75f80-b768-11e9-9b68-80992d9aec46.png)
![image](https://user-images.githubusercontent.com/25895491/62445635-5eb6d400-b769-11e9-8e24-3c5d72598e50.png)

**Comment by ykurenkov** [comment]
archive-push при этом работает нормально.

**Comment by gsmol** [comment]
Добрый день!
А можете привести полную команду, которой бэкапите?

**Comment by ykurenkov** [comment]
`"C:\Program Files\pg_probackup\2.1.3\PostgresPro10\pg_probackup.exe" backup -B \\10.20.9.240Ibis\IBIS_BACKUPS\PGBACKUPS\ --instance ny1-10 --backup-mode=FULL --skip-block-validation  --stream --progress -j 15
` 

`"C:\Program Files\pg_probackup\2.1.3\PostgresPro10\pg_probackup.exe" backup -B \\10.20.9.240\Ibis\IBIS_BACKUPS\PGBACKUPS\ --instance ny1-10 --backup-mode=DELTA --skip-block-validation  --stream --progress -j 15`

**Comment by gsmol** [comment]
Смог воспроизвести.
Похоже на баг сборки, свежесобранный бинарь работает нормально, могу быстро предоставить рабочий инсталлер, чтобы бэкапирование у Вас не простаивало.

**Comment by ykurenkov** [comment]
Спасибо. Я пока на 2.1.3 откатился. Официальный исправленный инсталлер ожидается?

**Comment by gsmol** [comment]
Да, конечно. Завтра выкатим.

**Comment by gsmol** [comment]
Сегодня не успели, переносится на завтра.

**Comment by gsmol** [comment]
Сборка бинарей и инсталлеров стала более прозрачной:
https://github.com/postgrespro/pgwininstall/tree/probackup_build#probackup-build

Завтра выкатим 2.1.5

**Comment by ykurenkov** [comment]
Там форматирование CR/LF поехало в Readme.md по этой ссылке - несколько SET в одной строке.

**Comment by gsmol** [comment]
Поправил

**Comment by gsmol** [comment]
Инсталлеры 2.1.5:
https://github.com/postgrespro/pg_probackup/releases/tag/2.1.5

**Comment by gsmol** [comment]
Проблема актуальна?

**Comment by ykurenkov** [comment]
Пока не ставил 2.1.5. Может сегодня успею, тогда завтра будет результат.

**Comment by ykurenkov** [comment]
Решил не откладывать в долгий ящик, поставил на одном сервере. Проблема не ушла.

![image](https://user-images.githubusercontent.com/25895491/62861251-87137500-bd0b-11e9-92c1-e23a640a12ce.png)

**Comment by gsmol** [comment]
А какая система?

**Comment by ykurenkov** [comment]
Windows Server 2016 Standard

**Comment by gsmol** [comment]
Хм, не могу воспроизвести.

**Comment by gsmol** [comment]
А если руками запускать, а не скриптом?

**Comment by gsmol** [comment]
Попробуйте вот этот бинарь:
https://oc.postgrespro.ru/index.php/s/NkHra55lOgHPuqi

**Comment by ykurenkov** [comment]
Запустил DELTA. Бэкап сейчас выполняется.

**Comment by ykurenkov** [comment]
Этот сервер на CIFS бэкапит. Запустил на втором, который на локальную NTFS - работает.

**Comment by ykurenkov** [comment]
Причем в обоих случаях бинарник запускается из %HOMEDRIVE%%HOMEPATH%\Downloads, в котором нет зависимых DLL, один бинарник.

**Comment by ykurenkov** [comment]
На локальной FS отработал

![image](https://user-images.githubusercontent.com/25895491/62919678-17a19200-bdac-11e9-87f8-dc131d81269f.png)

![image](https://user-images.githubusercontent.com/25895491/62919707-2daf5280-bdac-11e9-901a-3023cc1b8268.png)

**Comment by ykurenkov** [comment]
На CIFS тоже завершилось

![image](https://user-images.githubusercontent.com/25895491/62924964-ed56d100-bdb9-11e9-8705-2483cfda99e3.png)

**Comment by gsmol** [comment]
Понятно.
Запиливаю новые инсталлеры.
Спасибо!

**Comment by ykurenkov** [comment]
Скачал, установил. Запустил бэкап. Процесс идет...

**Comment by gsmol** [comment]
Еще не выпустил инсталлеры.

**Comment by ykurenkov** [comment]
Странно. А что тогда у меня отработало?

**Comment by gsmol** [comment]
Я так понял, что бинари из инсталлеров не работают, а бинарь, который я руками собрал, работает. Это так?

**Comment by gsmol** [comment]
Выложил свежие инсталлеры:
https://github.com/postgrespro/pg_probackup/releases/tag/2.1.5

**Comment by ykurenkov** [comment]
Проверить врядли смогу раньше четверга.

**Comment by ykurenkov** [comment]
Установил из новых инсталлеров. Запустил. Пока работают.

**Comment by gsmol** [comment]
Супер. Закрываю тикет.
Если появятся какие-либл проблемы - пишите.
Спасибо еще раз на фидбэк!
