### ISSUE TITLE
Ошибка при попытке выполнить archive-push или резервную копию

### ISSUE THREAD

**Issue by sfalkon** [postgrespro/pg_probackup#110]
ОС: Red Hat Enterprise Linux Server 7.6 (Maipo)
Ядро: 3.10.0-957.21.3.el7.x86_64
pg_probackup-11: 2.1.5 (PostgreSQL 11.4)

Добавляю инстанс:
-bash-4.2$ pg_probackup-11 add-instance --instance dbs24p -B /data/postgres11/backups                                                                                                                                                         
INFO: Instance 'dbs24p' successfully inited

При попытке переместить WAL: 
-bash-4.2$ /usr/bin/pg_probackup-11 archive-push -B /data/postgres11/backups --instance dbs24p --wal-file-path pg_wal/000000010000442D0000005D --wal-file-name 000000010000442D0000005D
ERROR: required parameter not specified: --instance

Ставлю параметр --instance первым в списке, получаю другую ошибку:
-bash-4.2$ /usr/bin/pg_probackup-11 archive-push --instance dbs24p -B /data/postgres11/backups --wal-file-path pg_wal/000000010000442D0000005D --wal-file-name 000000010000442D0000005D                                                       
ERROR: Instance 'dbs24p' does not exist in this backup catalog

Аналогичная ситуация при попытке создать резервную копию:
-bash-4.2$ /usr/bin/pg_probackup-11 backup -B /data/postgres11/backups --instance dbs24p --stream -b FULL
ERROR: required parameter not specified: --instance

-bash-4.2$ /usr/bin/pg_probackup-11 backup --instance dbs24p -B /data/postgres11/backups --stream -b FULL
ERROR: Instance 'dbs24p' does not exist in this backup catalog

Результат команды: pg_probackup-11 show -B /data/postgres11/backups --instance dbs24p                                                                                                                                                                 
```
==============================================================================================================
 Instance  Version  ID  Recovery Time  Mode  WAL  Current/Parent TLI  Time  Data  Start LSN  Stop LSN  Status 
==============================================================================================================
```

Результат команды: pg_probackup-11 show -B /data/postgres11/backups
```
BACKUP INSTANCE 'dbs24p'
==============================================================================================================
 Instance  Version  ID  Recovery Time  Mode  WAL  Current/Parent TLI  Time  Data  Start LSN  Stop LSN  Status 
==============================================================================================================
```

**Comment by gsmol** [comment]
Добрый день!

Не могу воспроизвести:
```
[root@5dc51eddf63f /]# pg_probackup-11 backup -B /data/postgres11/backups --instance dbs24p -b full -U postgres -d postgres --stream
WARNING: Current PostgreSQL role is superuser. It is not recommended to run backup or checkdb as superuser.
INFO: Backup start, pg_probackup version: 2.1.5, instance: dbs24p, backup ID: PVWT6D, backup mode: FULL, wal-method: STREAM, remote: false, replica: false, compress-algorithm: none, compress-level: 1
INFO: Start transferring data files
INFO: Data files are transferred
INFO: wait for pg_stop_backup()
INFO: pg_stop backup() successfully executed
INFO: Validating backup PVWT6D
INFO: Backup PVWT6D data files are valid
INFO: Backup PVWT6D real size: 40MB
INFO: Backup PVWT6D completed
```
Подозреваю, что имя инстанса `dbs24p` написано как-то неправильно, например, p - из русской раскладки.

**Comment by sfalkon** [comment]
Изменил имя, не помогло. Тип ошибки зависит от положения --instance в строке.
Дистрибутив pg_probackup скачивал отсюда: http://repo.postgrespro.ru/pg_probackup/rpm/latest/rhel-7Server-x86_64/
```
-bash-4.2$ /usr/bin/pg_probackup-11 backup -B /data/postgres11/backups --instance dbs24 --stream -b FULL
ERROR: required parameter not specified: --instance
```

```
-bash-4.2$ /usr/bin/pg_probackup-11 backup --instance dbs24 -B /data/postgres11/backups --stream -b FULL
ERROR: Instance 'dbs24' does not exist in this backup catalog
```

**Comment by gsmol** [comment]
> Дистрибутив pg_probackup скачивал отсюда: http://repo.postgrespro.ru/pg_probackup/rpm/latest/rhel-7Server-x86_64/
>
Аналогично.

Тут две разные проблемы.

```
-bash-4.2$ /usr/bin/pg_probackup-11 backup --instance dbs24 -B /data/postgres11/backups --stream -b FULL
ERROR: Instance 'dbs24' does not exist in this backup catalog
```
Да, это смог воспрозвести.
Похоже на баг, спасибо за фидбэк!
Воркараунд: параметр `--instance` нужно указывать всегда после параметра `-B`.

```
-bash-4.2$ /usr/bin/pg_probackup-11 backup -B /data/postgres11/backups --instance dbs24 --stream -b FULL
ERROR: required parameter not specified: --instance
```
Мэджик, не могу воспроизвести:
```
[root@5dc51eddf63f /]#  /usr/bin/pg_probackup-11 backup -B /data/postgres11/backups --instance dbs24p -b FULL -U postgres -d postgres --stream
WARNING: Current PostgreSQL role is superuser. It is not recommended to run backup or checkdb as superuser.
INFO: Backup start, pg_probackup version: 2.1.5, instance: dbs24p, backup ID: PVWWUW, backup mode: FULL, wal-method: STREAM, remote: false, replica: false, compress-algorithm: none, compress-level: 1
INFO: Start transferring data files
INFO: Data files are transferred
INFO: wait for pg_stop_backup()
INFO: pg_stop backup() successfully executed
INFO: Validating backup PVWWUW
INFO: Backup PVWWUW data files are valid
INFO: Backup PVWWUW real size: 40MB
INFO: Backup PVWWUW completed
[root@5dc51eddf63f /]# pg_probackup-11 show -B /data/postgres11/backups

BACKUP INSTANCE 'dbs24p'
=================================================================================================================================
 Instance  Version  ID      Recovery Time           Mode  WAL      Current/Parent TLI  Time   Data  Start LSN   Stop LSN  Status 
=================================================================================================================================
 dbs24p    11       PVWWUW  2019-08-08 09:54:36+00  FULL  STREAM   1 / 0                11s   40MB  0/A000028  0/A000160  OK     
 dbs24p    11       PVWWUL  ----                    FULL  ARCHIVE  1 / 0                 9s   ----  0/9000028        0/0  ERROR  
 dbs24p    11       PVWT6D  2019-08-08 08:35:05+00  FULL  STREAM   1 / 0                11s   40MB  0/7000028  0/7000160  OK     
 dbs24p    11       PVWT65  ----                    FULL  STREAM   1 / 0                 5s  102kB  0/5000028        0/0  ERROR
```

**Comment by sfalkon** [comment]
> > -bash-4.2$ /usr/bin/pg_probackup-11 backup -B /data/postgres11/backups --instance dbs24 --stream -b FULL
> ERROR: required parameter not specified: --instance
> Мэджик, не могу воспроизвести:
> 

С этим разобрался. Между параметрами попал непечатаемый символ, при копировании, забил строку руками команда отработала.
Заявку можно закрывать.
Спасибо!

**Comment by gsmol** [comment]
Вам спасибо за фидбэк!
Пока оставлю открытой как баг-репорт.

**Comment by gsmol** [comment]
Ввел заблуждение:

> Да, это смог воспрозвести.
> Похоже на баг, спасибо за фидбэк!
> Воркараунд: параметр --instance нужно указывать всегда после параметра -B.
>
Это не соответствует действительности:

```
/usr/bin/pg_probackup-11 backup --instance dbs24p -B /data/postgres11/backups -b FULL -U postgres -d postgres --stream
WARNING: Current PostgreSQL role is superuser. It is not recommended to run backup or checkdb as superuser.
INFO: Backup start, pg_probackup version: 2.1.5, instance: dbs24p, backup ID: PVX3A9, backup mode: FULL, wal-method: STREAM, remote: false, replica: false, compress-algorithm: none, compress-level: 1
INFO: Start transferring data files
INFO: Data files are transferred
INFO: wait for pg_stop_backup()
INFO: pg_stop backup() successfully executed
INFO: Validating backup PVX3A9
INFO: Backup PVX3A9 data files are valid
INFO: Backup PVX3A9 real size: 40MB
INFO: Backup PVX3A9 completed
```
Закрываю заявку.
