### ISSUE TITLE
backups corrupt when using page mode

### ISSUE THREAD

**Issue by killua001** [postgrespro/pg_probackup#12]
=========================================================================================
ID       Recovery time        Mode          Current/Parent TLI  Time    Data  Status  
=========================================================================================
OK805V   2017-01-23 14:57:44  PAGE           2 / 0                11m  1409MB  CORRUPT 
OK7NI5   2017-01-23 10:23:30  PAGE           2 / 0                10m  1339MB  CORRUPT 
OK6E9K   2017-01-22 18:04:53  FULL           2 / 0                 8m    66GB  OK 

## logs： ##
LOG: (9484/9714) base/17190/916086
LOG: (9485/9714) base/17190/916087
LOG: (9486/9714) base/17190/916088
LOG: (9487/9714) base/17190/916089
LOG: (9488/9714) base/17190/916090
LOG: (9489/9714) base/17190/916091
LOG: (9490/9714) base/17190/916092
LOG: (9491/9714) base/17190/916093
LOG: (9494/9714) base/17190/pg_internal.init
LOG: (9505/9714) global/1214
LOG: LOG: (9506/9714) global/1214_fsm
(9508/9714) global/1232
LOG: (9509/9714) global/1233
LOG: (9547/9714) global/pg_control
LOG: (9549/9714) global/pg_internal.init
LOG: (9550/9714) global/ptrack_control
LOG: (9556/9714) pg_clog/0003
LOG: (9682/9714) pg_commit_ts/007C
LOG: (9689/9714) pg_logical/replorigin_checkpoint
LOG: (9704/9714) pg_subtrans/0031
WARNING: backup 2017-01-23 14:57:44 is corrupted

## Validate the backup manually ##
$ pg_probackup validate OK805V
INFO: validate: 2017-01-23 14:57:44 backup and archive log files by CRC
WARNING: size of backup file "base/17190/18546" must be 31176 but 113096
WARNING: backup 2017-01-23 14:57:44 is corrupted

**Comment by alubennikova** [comment]
Hi, thank you for the report.
I didn't manage to reproduce this issue.
It would be great to see parameters you used to perform page mode backup. Was it parallel for example?
Could you also provide some more information about the schema and load you had used when got this problem?

**Comment by gsmol** [comment]
We`ve managed to reproduce this bug and fix it in recent commits.
Please upgrade.
