### ISSUE TITLE
removal of ERROR backups

### ISSUE THREAD

**Issue by sanstepan** [postgrespro/pg_probackup#120]
It would be great to have Instead of 
_for BKP in $(pg_probackup show -B /var/lib/pgpro/std-10/probackup -D /var/lib/pgpro/std-10/data --instance banana |grep ERROR|awk '{print $3}') ; do pg_probackup delete -B /var/lib/pgpro/std-10/probackup -D /var/lib/pgpro/std-10/data --instance banana --backup-id $BKP ; done_
something like 
_pg_probackup delete -B /var/lib/pgpro/std-10/probackup -D /var/lib/pgpro/std-10/data --instance banana --error-state_

**Comment by gsmol** [comment]
Hello!
We have an issue for exactly the same problem with slightly different approach of solving it.
https://github.com/postgrespro/pg_probackup/issues/57

Which approach is preferable from your POV?
Personally, I think that both solutions are sound, have their uses, so both should be implemented.

**Comment by rzharkov** [comment]
It might be a very helpful option.

**Comment by VictorSpirin** [comment]
@gsmol   issue_120 gitlab branch

**Comment by gsmol** [comment]
There are some thoughts about your patch:
1. Instead of using flag `--error-state`, lets use option `--status` with status as an argument, so it should be possible to delete all backups of any status:
```
pg_probackup delete -B backup_dir --instance node --status=ok
```
2. `instance_name` variable must be used as an argument in function do_delete_error

**Comment by VictorSpirin** [comment]
Updated issue_120 gitlab branch

**Comment by gsmol** [comment]
Inspected your patch. Please consider the following steps to improve your patch:
1. Consider `--dry-run` flag.
2. Update `--help` output.
3. Documentation must contain warning, that deleting by status do not take established retention policy into account.
4. Update documentation synopsis, command-line reference and Options

**Comment by gsmol** [comment]
Merged
