### ISSUE TITLE
Бэкап не помечен как corrupted

### ISSUE THREAD

**Issue by ykurenkov** [postgrespro/pg_probackup#124]
Был сбой во время выполнения бэкапа. Запустил валидацию. Получил сообщение о том, что отсутствует часть файлов, но бэкап остался помеченный как "DONE".
![image](https://user-images.githubusercontent.com/25895491/65425659-25205200-de17-11e9-9748-8c388a3f5081.png)
Запустил повторую валидацию
![image](https://user-images.githubusercontent.com/25895491/65427108-4f274380-de1a-11e9-89ab-73648024b797.png)
![image](https://user-images.githubusercontent.com/25895491/65427150-636b4080-de1a-11e9-8e74-393735da926a.png)

**Comment by gsmol** [comment]
Добрый день!
Хм, это явно нелегальное поведение. Сейчас посмотрим.

**Comment by gsmol** [comment]
Версия 2.1.5 ?

**Comment by ykurenkov** [comment]
Да, 2.1.5, Windows

**Comment by gsmol** [comment]
Он обнаружил коррапшен и попытался поставить соответствующий статус, но не смог прочитать control файл.

**Comment by gsmol** [comment]
Очевидно, что надо падать чуть раньше.
Оптимистичное сообщение 'Backup %s is valid' мы уже поменяли.

**Comment by gsmol** [comment]
А control файл вообще существует?

**Comment by ykurenkov** [comment]
backup.control, backup_content.control, backup.pid присутствуют не нулевой длины

**Comment by gsmol** [comment]
А можете запустить валидацию с опциями `--log-level-file=verbose --log-filename=forensic.log` и прислать файл forensic.log ?

**Comment by ykurenkov** [comment]
![image](https://user-images.githubusercontent.com/25895491/65491904-a4199700-deb8-11e9-8a07-f1ea62152b75.png)
Переименовал backup.pid, запустил
![image](https://user-images.githubusercontent.com/25895491/65492066-f65ab800-deb8-11e9-8e0e-c3c77255c9cb.png)

**Comment by ykurenkov** [comment]
[forensic.log](https://github.com/postgrespro/pg_probackup/files/3645944/forensic.log)

**Comment by ykurenkov** [comment]
Вот что удалось выяснить, перенаправив stderr в файл
[stderr.log](https://github.com/postgrespro/pg_probackup/files/3646601/stderr.log)
.

**Comment by ykurenkov** [comment]
Еще вариант.
[forensic.log](https://github.com/postgrespro/pg_probackup/files/3646727/forensic.log)
[stderr.log](https://github.com/postgrespro/pg_probackup/files/3646728/stderr.log)

**Comment by gsmol** [comment]
Тут оно походу сегфолтнулось:
```
2019-09-24 15:06:06 RTZ 4 (ceia): INFO: command: C:\Program Files\pg_probackup\2.1.5\PostgresPro10\pg_probackup.exe validate -B \\10.20.9.240\Ibis\IBIS_BACKUPS\PGBACKUPS\ --instance ny1-10 -j 15 -i PY7BS3 --log-level-file verbose --log-filename forensic.log 
2019-09-24 15:06:06 RTZ 4 (ceia): LOG: Validate begin.
2019-09-24 15:06:06 RTZ 4 (ceia): WARNING: Process 13408 which used backup PY7BS3 no longer exists
2019-09-24 15:06:06 RTZ 4 (ceia): INFO: Validating backup PY7BS3
```

А Вы не могли бы прислать метаданные этого бэкапа?
backup_content.control и backup.control

**Comment by ykurenkov** [comment]
[backup.control.txt](https://github.com/postgrespro/pg_probackup/files/3647393/backup.control.txt)
[backup_content.control.txt](https://github.com/postgrespro/pg_probackup/files/3647394/backup_content.control.txt)
Добавил к имени .txt

**Comment by gsmol** [comment]
А если 'forensic.log' файл расположить на локальной файловой системе? Например:
```
--log-level-file=verbose --log-filename=forensic.log --log-directory=C:\logs\
```

**Comment by ykurenkov** [comment]
[forensic.log](https://github.com/postgrespro/pg_probackup/files/3651035/forensic.log)
[stderr.log](https://github.com/postgrespro/pg_probackup/files/3651036/stderr.log)

**Comment by gsmol** [comment]
По-моему какая-то шляпа с файловой системой происходит.
А если не через NFS совершить валидацию?

**Comment by ykurenkov** [comment]
Там не  NFS, а CIFS (smbfs) с FreeNAS (FreeBSD), а запустить на нём pg_probackup не получится. Если найду свободное место для эксперимента, могу попробовать переписать бэкап на локальную FS. Вариант?

**Comment by ykurenkov** [comment]
Копирую...

**Comment by gsmol** [comment]
Да, если есть такая возможность.

**Comment by ykurenkov** [comment]
При копировании ошибка. Проблема на NASе. Похоже, что она возникла еще при бэкапировании, есть у меня такое подозрение. 
![2019-09-25_11-38-51](https://user-images.githubusercontent.com/25895491/65584375-79e3da00-df89-11e9-86aa-c4e545756787.png)

Сказал игнорировать ошибки и продолжить.

**Comment by gsmol** [comment]
Видимо, надо таки заняться портом на freebsd.

**Comment by gsmol** [comment]
Кстати, кто-то уже решил этим заняться:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=239559

**Comment by ykurenkov** [comment]
Зачетно. Нужно только версионность PG поддерживать по аналогии с портами postgresqlXX-*.
А потом протолкнуть https://www.ixsystems.com/documentation/freenas/11.2-U6/plugins.html
Но это другая тема.

**Comment by gsmol** [comment]
Есть новости?

**Comment by ykurenkov** [comment]
Скопировался проблемный бэкап на локальную ФС с ошибками без некоторых проблемных файлов. Запустил на него validate и через пару секунд увидел на экране:

```
WARNING: Backup file "D:/IBIS_BACKUPS/PGBACKUPS/backups/ny1-10/PY7BS3/database/base/15520165/15526151" is not found
WARNING: Backup file "D:/IBIS_BACKUPS/PGBACKUPS/backups/ny1-10/PY7BS3/database/base/15520165/15526226" is not found
WARNING: Backup file "D:/IBIS_BACKUPS/PGBACKUPS/backups/ny1-10/PY7BS3/database/base/15520165/15526131" is not found
WARNING: Backup file "D:/IBIS_BACKUPS/PGBACKUPS/backups/ny1-10/PY7BS3/database/base/15520165/15526124" is not found
WARNING: Backup file "D:/IBIS_BACKUPS/PGBACKUPS/backups/ny1-10/PY7BS3/database/base/15520165/15526116" is not found
WARNING: Backup file "D:/IBIS_BACKUPS/PGBACKUPS/backups/ny1-10/PY7BS3/database/base/15520165/15526099" is not found
WARNING: Backup file "D:/IBIS_BACKUPS/PGBACKUPS/backups/ny1-10/PY7BS3/database/base/15520165/15526066" is not found
WARNING: Backup file "D:/IBIS_BACKUPS/PGBACKUPS/backups/ny1-10/PY7BS3/database/base/15520165/15526060" is not found
WARNING: Backup file "D:/IBIS_BACKUPS/PGBACKUPS/backups/ny1-10/PY7BS3/database/base/15520165/15526052" is not found
WARNING: Backup file "D:/IBIS_BACKUPS/PGBACKUPS/backups/ny1-10/PY7BS3/database/base/15520165/15526019" is not found
WARNING: Backup file "D:/IBIS_BACKUPS/PGBACKUPS/backups/ny1-10/PY7BS3/database/base/15520165/15526010" is not found
WARNING: Backup PY7BS3 data files are corrupted
ERROR: Backup PY7BS3 is corrupt.

```

```
BACKUP INSTANCE 'ny1-10'
========================================================================================================================================
 Instance  Version  ID      Recovery Time           Mode  WAL     Current/Parent TLI   Time   Data     Start LSN      Stop LSN  Status
========================================================================================================================================
 ny1-10    10       PY7BS3  2019-09-22 05:04:06+05  FULL  STREAM  1 / 0               7465s  506GB  284/18000028  284/49011550  CORRUPT
```

**Comment by gsmol** [comment]
Ну т.е. явно какая-то шляпа с CIFS.

**Comment by ykurenkov** [comment]
![Screenshot from 2019-09-29 17-46-19](https://user-images.githubusercontent.com/25895491/65834176-163b1300-e2e1-11e9-82b2-24db26a1f5e6.png)
Да, проблема в NAS. Только почему "Backup PY7BS3 is valid."?

```
WARNING: Backup PY7BS3 data files are corrupted
INFO: Backup PY7BS3 is valid.
INFO: Validate of backup PY7BS3 completed.
```

**Comment by gsmol** [comment]
Да, это некорректно

**Comment by gsmol** [comment]
Пофиксил.
Закрываем задачку?

**Comment by ykurenkov** [comment]
Конечно!
