### ISSUE TITLE
retention option: wal-depth

### ISSUE THREAD

**Issue by gsmol** [postgrespro/pg_probackup#127]
It would be nice to have an ability to govern the amount of WAL keeped by retention measured by a number of backups.
```
A ---> --A1 ---> A2 ---> A3 --->    timeline 1
```
A - FULL backup
A{1,3} - incremental backups.

If `wal-depth` is set to 1, then keep only WAL >= START LSN of A3.
If `wal-depth` is set to 2, then keep only WAL >= START LSN of A2.

**Comment by gsmol** [comment]
New option `--wal-depth` - number of latest valid backups in timeline that can be used to perform PITR.

**Comment by alubennikova** [comment]
I slightly updated code comments.
It seems that the case of retention with multiple timelines (each of which contains several backups) must be improved. I left the corresponding TODO comment.

This issue lacks help.c and Documentaion.md update.

**Comment by gsmol** [comment]
> It seems that the case of retention with multiple timelines (each of which contains several backups) must be improved.
>
Done
TODO: Refactoring, documentation, comments improvements, more tests

**Comment by gsmol** [comment]
Merged.
