### ISSUE TITLE
Не добавляется restore_command в recovery.conf

### ISSUE THREAD

**Issue by sfalkon** [postgrespro/pg_probackup#138]
При восстановлении из резервной копии в качестве реплики, не добавляется restore_command в файл recovery.conf

-bash-4.2$ pg_probackup-11 version
```
pg_probackup-11 2.2.3 (PostgreSQL 11.5)
```

> db11-main/pg_probackup.conf 
```
# Backup instance information
pgdata = /var/lib/pgsql/11/data
system-identifier = 6751292891009303552
xlog-seg-size = 16777216
# Connection parameters
pgdatabase = postgres
pguser = backup
# Archive parameters
restore-command = 'ssh barman@db-backup barman get-wal db11-main %f > %p'
# Compression parameters
compress-algorithm = zlib
compress-level = 6
# Remote access parameters
remote-host = db11-main
remote-user = postgres
```

Команда восстановления:
-bash-4.2$ pg_probackup-11 restore -B /data/backups --instance db11-main -R --restore-command='ssh barman@db-backup barman get-wal db11-main %f > %p' --remote-host=db11-replica --remote-user=postgres
```
INFO: Validating backup PZVTNP
INFO: Backup PZVTNP data files are valid
INFO: Backup PZVTNP WAL segments are valid
INFO: Backup PZVTNP is valid.
INFO: Restore of backup PZVTNP completed.
```

Результат:
-bash-4.2$ cat 11/data/recovery.conf 
```
# recovery.conf generated by pg_probackup 2.2.3
standby_mode = 'on'
primary_conninfo = 'user=backup passfile=/var/lib/barman/.pgpass host=db11-main port=5432 sslmode=prefer sslcompression=0 krbsrvname=postgres target_session_attrs=any'
```

**Comment by gsmol** [comment]
Добрый день!
> Получается, если выполнялся бэкап с флагом stream, то нельзя использовать restore_command?
>
Нет, такого ограничения не предусмотрено, зарепорченное Вами поведение - баг.
Сейчас пофиксим и как раз выкатим вместе с 2.2.4

**Comment by gsmol** [comment]
Пожалуй, я немного поторопился с заявлением, что это баг.
Всё оказалось немного сложнее.

**Comment by gsmol** [comment]
Встает вопрос, при явном отсутствии(!) PITR параметров(recovery-target* опции), всегда ли добавлять restore_command, если задан параметр `--restore-command` или только в ситуации, когда мы восстанавливаем STREAM бэкап как реплику.
Вопрос не такой простой как кажется, потому что `--restore-command` может быть задан неявно через конфиг пробэкапа.

**Comment by gsmol** [comment]
Учитывая, что воркараунд есть, переношу пока на 2.2.5.

**Comment by gsmol** [comment]
Смержено, релизнется с 2.2.5.
Спасибо за фидбэк!
