### ISSUE TITLE
Какая-то странность бэкапа-восстановления: pg_cron

### ISSUE THREAD

**Issue by ykurenkov** [postgrespro/pg_probackup#141]
Есть кластер postgresql-10 с синхроннной репликацией на два слейва. В кластере установлено расширение [pg_cron-1.1](https://github.com/citusdata/pg_cron).  pg_probackup-2.2.4 делает бэкап этого кластера. Потом он восстанавливает бэкап на удалённую ноду. В результате восстановления таблица, созданная этим расширением восстанавливается пустая.

На сервере, с которого делается бэкап, активная нагрузка. Записи в таблицу были добавлены более 10 дней назад, так что точно всё закомичено, я надеюсь.

Куда пропали записи?

```
root@m65-wrkst-02:~/bak2tpac# psql -U postgres -h m65-pgkisc-01 -d cron -c "select count(*) from cron.job;"
 count
-------
     4
(1 row)

root@m65-wrkst-02:~/bak2tpac# psql -U postgres -h m65-tppgkis-01 -d cron -c "select count(*) from cron.job;"
 count
-------
     0
(1 row)

```
Первый хост исходный, второй восстановлен из бэкапов (полный и инкременты).

Вывод 
`
pg_probackup show
`
в файле
[pg_probackup-show.log](https://github.com/postgrespro/pg_probackup/files/3797119/pg_probackup-show.log)

**Comment by ykurenkov** [comment]
[pg_probackup-show.log](https://github.com/postgrespro/pg_probackup/files/3797123/pg_probackup-show.log)

**Comment by gsmol** [comment]
Добрый день.
Выглядит подозрительно, давайте разбираться.
1. Какая версия pg_probackup?
2. Какая версия pg_cron?
2. Какой бэкап восстанавливали(Айдюк)?
3. cron.job - это таблица или вьюха? Запрос ниже надо выполнить на исходном хосте и на восстановленном:
```
select pg_relation_filepath('cron.job')
```

**Comment by ykurenkov** [comment]
Ubuntu 18.04 везде
1. pg_probackup 2.2.4
2. pg_cron 1.1
3. Пробовал последний полный Q09BO2 и последний инкремент на то время Q0A456.
4. Это таблица, которую создаёт расширение при 
`create extension pg_cron;`
```
root@m65-wrkst-02:~/bak2tpac# psql -U postgres -h m65-pgkisc-01 -d cron -c "select pg_relation_filepath('cron.job');"
 pg_relation_filepath
----------------------
 base/2160142/3089759
(1 row)

```
```
root@m65-wrkst-02:~/bak2tpac# psql -U postgres -h m65-tppgkis-01 -d cron -c "select pg_relation_filepath('cron.job');"
  pg_relation_filepath
------------------------
 base/10615884/10615912
(1 row)
```

Вот полный лог работы скрипта с восстановлением (set -x). В нем не нашел упоминания base/2160142/3089759

[run.log.gz](https://github.com/postgrespro/pg_probackup/files/3797214/run.log.gz)

**Comment by gsmol** [comment]
Хм, у вас тут не совпадают oid`ы баз.
2160142 != 10615884

Вы уверены, что это правильный инстанс?

**Comment by gsmol** [comment]
Давайте посмотрим и там и там выхлоп запроса:
```
select * from pg_control_system();
```

**Comment by ykurenkov** [comment]
Да, есть странности. И эта не единственная. Я пока поищу причину их возникновения.

**Comment by gsmol** [comment]
И system_identifier разный, это точно какой-то другой инстанс

**Comment by gsmol** [comment]
Если бы m65-tppgkis-01 был создан из m65-pgkisc-01, то у нас были бы одинаковые system_identifier

**Comment by ykurenkov** [comment]
Одну причину мистики нашел. ssh в remote_command игнорирует && и || в команде

`ssh $tpac_pg_host service postgresql stop ; ([ -d ${PGDATA}.old ] && rm -rf ${PGDATA}.old ); ([ -d ${PGDATA} ] && mv ${PGDATA} ${PGDATA}.old)`

В итоге вся цепочка команд после остановки сервиса не отрабатывалась, а это только начало сюрпризов.

**Comment by gsmol** [comment]
А что за `remote_command` ?

**Comment by ykurenkov** [comment]
Просто набор shell комманд. Нельзя выполнить удаленно несколько команд с проверкой кода завершения. Или я это к своему позору не умею.

**Comment by gsmol** [comment]
По-моему Вы просто забыли кавычки и ваш локальный шелл передает в ssh как аргумент только первую часть вашего однострочника (до точки с запятой):
```
ssh $tpac_pg_host "service postgresql stop ; ([ -d ${PGDATA}.old ] && rm -rf ${PGDATA}.old ); ([ -d ${PGDATA} ] && mv ${PGDATA} ${PGDATA}.old)"
```

**Comment by ykurenkov** [comment]
Нет, не забыл. Это один из вариантов.

Похоже, что что-то забавнее. Сейчас проверю.

**Comment by ykurenkov** [comment]
В общем, проблема найдена. Помогла волшебная палочка 
`show data_directory;`

Думаю, что дальше объяснять уже не стоит. Спасибо за наставления в сторону достижения просветления :)

**Comment by gsmol** [comment]
Пожалуйста, обращайтесь!

**Comment by gsmol** [comment]
Хм, меня смущают метаданные ваших бэкапов:
```
=========================================================================================================================================
 Instance  Version  ID      Recovery Time           Mode   WAL Mode  TLI     Time    Data  WAL  Zratio  Start LSN    Stop LSN     Status 
=========================================================================================================================================
 ppak_kis  10       Q0A688  2019-11-01 11:10:39+03  DELTA  STREAM    5/5  10m:34s   119MB    0    1.00  60/7005148   60/A627380   OK 
```
Можете прислать выхлоп от `pg_probackup show -i Q0A688 --format=json`

**Comment by ykurenkov** [comment]
```
root@m65-wrkst-02:~/bak2tpac# ../bin/pg_backup show -i Q0A688 --format=json
[
    {
        "instance": "ppak_kis",
        "backups": [
            {
                "id": "Q0A688",
                "parent-backup-id": "Q0A5JD",
                "backup-mode": "DELTA",
                "wal": "STREAM",
                "compress-alg": "zlib",
                "compress-level": 9,
                "from-replica": "false",
                "block-size": 8192,
                "xlog-block-size": 8192,
                "checksum-version": 1,
                "program-version": "2.1.5",
                "server-version": "10",
                "current-tli": 5,
                "parent-tli": 0,
                "start-lsn": "60/7005148",
                "stop-lsn": "60/A627380",
                "start-time": "2019-11-01 11:00:08+03",
                "end-time": "2019-11-01 11:10:42+03",
                "recovery-xid": 0,
                "recovery-time": "2019-11-01 11:10:39+03",
                "data-bytes": 124965019,
                "uncompressed-bytes": 0,
                "pgdata-bytes": 0,
                "primary_conninfo": "user=postgres host=m65-pgkis-03 port=5431 sslmode=prefer sslcompression=0 krbsrvname=postgres target_session_attrs=any",
                "status": "OK"
            }
        ]
    }
]

```

**Comment by gsmol** [comment]
Хм, а может прислать мне содержимое файла backup_content.control этого бэкапа?

**Comment by gsmol** [comment]
а, стоп, это старье - 2.1.5.

**Comment by gsmol** [comment]
А есть бэкапы, сделанные с помощью 2.2.4?

**Comment by ykurenkov** [comment]
Пока нет 2.2.4. Попросил коллег проагрейдить.

**Comment by gsmol** [comment]
А текущий бинарь какой версии? Он явно посвежее.

**Comment by ykurenkov** [comment]
Бэкапит 2.1.5, а я пытаюсь восстановить 2.2.4

**Comment by gsmol** [comment]
Понял, тогда вопросов нет.
По вашей наводке нашел мелкий баг:
0d028b79eca5c90b46ccb310f425cdd67e00135b

**Comment by gsmol** [comment]
Спасибо за фидбэк!

**Comment by ykurenkov** [comment]
2.2.4 обещали завтра поставить.

**Comment by gsmol** [comment]
К этому времени уже выйдет 2.2.5.

**Comment by ykurenkov** [comment]
Какой скоростной век! Не успеваем... :)

**Comment by gsmol** [comment]
Увы, не блажь, а необходимость.
