### ISSUE TITLE
Add note to backup

### ISSUE THREAD

**Issue by gsmol** [postgrespro/pg_probackup#146]
It should be possible to add a note to a backup copy at the start of backup or via `set-backup` command. It should be possible view it via `show` command in JSON format and overwrite or clear via `set-backup`.
Max size - 1KB ?

**Comment by VictorSpirin** [comment]
@gsmol   issue_146 gitlab branch

**Comment by gsmol** [comment]
It would be good to have a test or two, covering this feature, and documentation update.
Also please use pgSetBackupParams structure in do_backup().
And it appears that note cannot be set using `set-backup` command.

**Comment by gsmol** [comment]
Merged
