### ISSUE TITLE
Восстановление реплики. Мысли.

### ISSUE THREAD

**Issue by ykurenkov** [postgrespro/pg_probackup#147]
Восстанавливаю я из бэкапа реплику. Восстановление прошло успешно, recovery.conf создан. Правлю в recovery.conf primary_conninfo, запускаю сервер и вижу в логе сообщение о том, что мастер сильно убежал вперёд и нужный мне сегмент WAL уже удалил. При этом на мастере включено непрерывное архивирование и соответствующий сегмент есть в BACKUP_DIR.

Есть выход. Создаем слот репликации, в recovery.conf отключаем потоковую репликацию, прописываем recovery_command, перезагружаем сервер и ждем, пока он не вытащит из архива все необходимое. После этого возвращаем потоковую репликацию с использованием указанного слота.

Есть ли возможность научить pg_probackup в случае восстановлении реплики вытаскивать все недостающие с момента бэкапа сегменты wal и создавать слот репликации перед восстановлением, который прописывается в создаваемый recovery.conf?

**Comment by gsmol** [comment]
Добрый день.

1. Можно было прям при первом восстановлении это сделать:
```
pg_probackup restore -R  --recovery-target='latest' ...
```

А зачем Вам слот, если есть архив?

**Comment by ykurenkov** [comment]
1. Спасибо. Видать не дочитал или не понял. Попробую.
2. На всякий случай :) За работу серверов отвечают другие люди, поэтому иногда бывают случаи отвалившегося слейва, а архивация не везде есть (сказываются индивидуальные особенности архитектуры), поэтому, чтобы часто не генерить слейва заново использую слоты репликации.

**Comment by gsmol** [comment]
Проблема в следующем:
1. Если есть архив, то слот не нужен и вреден.
2. Если же архива нет, то 100% гарантию успешного восстановления бэкапа как реплики, слот должен создаваться в момент создания бэкапа.
3. Мы можем, конечно, в начале восстановления бэкапа пытаться создать слот на мастере, начиная с позиции, соответствующей STOP LSN бэкапа. Но если бэкап сделан давно, или даже если бэкап свежий, но мастер очень агрессивно ротирует WAL, то создать слот не получится.

**Comment by ykurenkov** [comment]
1. В чем вредность? Архив для архивирования с возможностью PITR на указанный момент времени, а слот для потоковой репликации.
2. Да, согласен, это я перетащил свой опыт создания реплик с помошью pg_basebackup --wal-method=stream --slot=... Тут он не работает.
3. Да, согласен. Хотелось уйти с методики создания реплики с помошью pg_basebackup, чтобы не грузить работающий мастер. Восстановить реплику из бэкапа очень заманчиво, но это возможно в достаточно ограниченных условиях. Нет, конечно есть извращенный вариан "планового" создания реплики: создать слот перед выполнением бэкапа, из которого будет восстановлена реплика, но это уже на откуп "создателю".

Некоторое прояснение наступило. Надо осмыслить все, а потом переписать скрипты :) Спасибо.

**Comment by gsmol** [comment]
Вред в том, что Вы получаете еще одну точку отказа бесплатно. В общем случае, слот не даёт никаких преимуществ при наличии архива.

Я еще немного подумал. Учитывая, что проблема актуальна только для STREAM бэкапов, потому что ARCHIVE всегда могут догнаться из архива, то самое здаровое решение видится так:
1. Добавляем опцию `-R, --restore-as-replica` в команду `backup`
2. Если бэкап видит эту опцию вместе с опцией `-S, --slot`, то он в начале бэкапа создает перманентный слот согласно опции `-S` и использует его в процессе выполнения. После выполнения бэкапа слот остаётся.
3. Запускаем восстановление с опцией `-R` и (важно) `-S`, в этом случае команда `restore` передаёт имя слота как аргумент в `primary_slot_name` в `recovery.conf`.

**Comment by gsmol** [comment]
> Да, согласен, это я перетащил свой опыт создания реплик с помошью pg_basebackup --wal-method=stream --slot=... Тут он не работает.
>
К слову сказать, этот метод тоже не детерминированный.
В промежуток между завершением бэкапа и стартом реплики ничто не удерживает нужный Вам WAL от ротации

**Comment by ykurenkov** [comment]
Ну, может быть, только если создать бэкап с -S и не создать реплику, которая будет этот слот использовать, не получим ли мы захламление pg_wal? Чо-то боязно наличие такого функционала. Это конечно не rm -rf / но тоже с сюрпризом.

**Comment by ykurenkov** [comment]
Или WAL хранятся только для active=t слотов?

**Comment by gsmol** [comment]
> Ну, может быть, только если создать бэкап с -S и не создать реплику, которая будет этот слот использовать, не получим ли мы захламление pg_wal?
>
Получим, конечно. Но зачем так делать?

**Comment by gsmol** [comment]
> Или WAL хранятся только для active=t слотов?
>
Что это за слоты такие?

**Comment by ykurenkov** [comment]
> Но зачем так делать?

Естественно от непонимания того, как это работает и для чего оно нужно. Тут не просто документировать ключи нужно, но обязательно нужно описывать способ применения, пример приводить. 

Ничто не мешает пользователю -S в crontab указать.

**Comment by gsmol** [comment]
Ну разумеется. В доке будет дан пример и насыпано предостережений.

**Comment by ykurenkov** [comment]
Значит быть новому функционалу?

**Comment by gsmol** [comment]
Ну я еще обсужу этот вопрос с товарищами на работе, но проблема актуальная, поэтому почему бы и нет.

**Comment by ykurenkov** [comment]
Коллеги помогут посмотреть на проблему с разных сторон. Ждем.

**Comment by gsmol** [comment]
Возражения коллег против предложенного подхода:
1. Что если я хочу сделать 5 реплик? Мне нужно сделать 5 бэкапов?
2. Что если я делаю бэкап с реплики, но полученный бэкап хочу подключить к мастеру?

**Comment by ykurenkov** [comment]
Возражения обоснованные. Может тогда просто сделать ключик -S slot, чтобы он был записан в recovery.conf и больше никак не использовался? Или вообще отказаться от наших идей и ничего не делать - уж больно все неоднозначное.

**Comment by gsmol** [comment]
На мой взгляд, возражения, конечно, обоснованные, но по-моему в подавлющем большинстве случаев юзеру нужно просто накатить реплику с мастера.
Да, `-S slot` для `restore` сейчас сделаю.

**Comment by gsmol** [comment]
Готово:
```
[gsmol@deck pg_probackup]$ pg_probackup restore -B /backup  --instance replica -D /tmp/restore5 -S slotname
INFO: Validating backup Q0WBPV
INFO: Backup Q0WBPV data files are valid
INFO: Backup Q0WBPV WAL segments are valid
INFO: Backup Q0WBPV is valid.
INFO: Restore of backup Q0WBPV completed.

[gsmol@deck pg_probackup]$ cat /tmp/restore5/recovery.conf
# probackup_recovery.conf generated by pg_probackup 2.2.5

## recovery settings
recovery_target_timeline = 'current'
recovery_target_action = 'pause'
restore_command = '/home/gsmol/git/postgres/contrib/pg_probackup/pg_probackup archive-get -B /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/archive/test_archive_catalog/backup --instance replica --wal-file-path=%p --wal-file-name=%f'

## standby settings
primary_conninfo = 'user=gsmol passfile=/home/gsmol/.pgpass host=localhost port=28262 sslmode=disable sslcompression=0 gssencmode=disable target_session_attrs=any'
primary_slot_name = 'slotname'
```

**Comment by ykurenkov** [comment]
Здорово!

Я написал свой хитромудрый враппер для вызова pg_probackup. После добавления новых возможностей в pg_probackup давно назрела необходимость переписать его, но угроза появления нового в будущем сдерживает от этого...

**Comment by gsmol** [comment]
Я тут еще немного подумал и понял, что мы изобретаем велосипед, ведь всё это давно есть в pg_receivexlog:
```
[gsmol@deck pg_probackup]$ pg_receivewal --create-slot -S my_slot --if-not-exists -p 16559 && pg_probackup backup -B /backup -b full --stream -S my_slot
      
INFO: Backup start, pg_probackup version: 2.2.5, instance: node, backup ID: Q101NQ, backup mode: FULL, wal mode: STREAM, remote: true, compress-algorithm: none, compress-level: 1
WARNING: Current PostgreSQL role is superuser. It is not recommended to run backup or checkdb as superuser.
INFO: Start transferring data files
INFO: Data files are transferred
INFO: wait for pg_stop_backup()
INFO: pg_stop backup() successfully executed
INFO: Validating backup Q101NQ
INFO: Backup Q101NQ data files are valid
INFO: Backup Q101NQ resident size: 40MB
INFO: Backup Q101NQ completed

[gsmol@deck pg_probackup]$ psql

postgres=# select * from pg_replication_slots ;
-[ RECORD 1 ]-------+----------
slot_name           | my_slot
plugin              | 
slot_type           | physical
datoid              | 
database            | 
temporary           | f
active              | f
active_pid          | 
xmin                | 
catalog_xmin        | 
restart_lsn         | 0/4000000
confirmed_flush_lsn | 

[gsmol@deck pg_probackup]$ pg_probackup show  -B /backup  

BACKUP INSTANCE 'node'
================================================================================================================================
 Instance  Version  ID      Recovery Time           Mode  WAL Mode  TLI  Time  Data   WAL  Zratio  Start LSN  Stop LSN   Status 
================================================================================================================================
 node      12       Q101NQ  2019-11-15 10:19:09+03  FULL  STREAM    1/0   10s  24MB  16MB    1.00  0/4000028  0/40001A0  OK 
```

**Comment by gsmol** [comment]
Восстанавливаем бэкап:
```
[gsmol@deck pg_probackup]$ pg_probackup restore  -B /backup --instance node  -S my_slot -D /tmp/restore5
INFO: Validating backup Q101NQ
INFO: Backup Q101NQ data files are valid
INFO: Backup Q101NQ WAL segments are valid
INFO: Backup Q101NQ is valid.
INFO: Restore of backup Q101NQ completed.

[gsmol@deck pg_probackup]$ pg_ctl start -D /tmp/restore5
....

postgres=# select * from pg_replication_slots ;
-[ RECORD 1 ]-------+----------
slot_name           | my_slot
plugin              | 
slot_type           | physical
datoid              | 
database            | 
temporary           | f
active              | t
active_pid          | 24191
xmin                | 
catalog_xmin        | 
restart_lsn         | 0/5000148
confirmed_flush_lsn | 

postgres=# select * from pg_stat_replication ;
pg_stat_replication
postgres=# select * from pg_stat_replication ;
-[ RECORD 1 ]----+------------------------------
pid              | 24191
usesysid         | 10
usename          | gsmol
application_name | walreceiver
client_addr      | 127.0.0.1
client_hostname  | 
client_port      | 42198
backend_start    | 2019-11-15 07:27:31.619711+00
backend_xmin     | 
state            | streaming
sent_lsn         | 0/5000148
write_lsn        | 0/5000148
flush_lsn        | 0/5000148
replay_lsn       | 0/5000148
write_lag        | 
flush_lag        | 
replay_lag       | 
sync_priority    | 0
sync_state       | async
reply_time       | 2019-11-15 07:27:51.679046+00

**Comment by gsmol** [comment]
> Я написал свой хитромудрый враппер для вызова pg_probackup. После добавления новых возможностей в pg_probackup давно назрела необходимость переписать его, но угроза появления нового в будущем сдерживает от этого...
>
Ну у нас семантическое версионирование, мы обязуемся не ломать обратную совместимость в пределах одной мажорной версии. Т.е. могут появляться новые опции и команды, но уже имеющиеся опции и команды не будут пропадать, менять своё поведение и т.д.

**Comment by ykurenkov** [comment]
Некоторые возможности, которх не было в pg_probackup на момент написания враппера я делал в скрипте. Например, прописывал слот репликации в recovery.conf :) Ну и со временем в процессе работы приходит осознание необходимости изменения некоторого функционала. Это жизнь, это работа.

**Comment by gsmol** [comment]
Ну, учитывая, что у Вас есть архив, то я всё еще не понимаю зачем Вам слот.
Прописать при восстановлении restore_command на реплике(в пробэкапе есть соответствующие ручки для этого) и проблема будет решена.

**Comment by gsmol** [comment]
Закрываем?

**Comment by ykurenkov** [comment]
Да.
