### ISSUE TITLE
Сжатие бэкапа?

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/pg_probackup#17]
В документации написано:

- Хранение копируемых данных в сжатом состоянии для экономии дискового пространства

Работаю на следующих версиях:
```
select version()
PostgreSQL 9.6.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 ```
20160609, 64-bit
```

создал бэкап используя команду
`pg_probackup backup -b full --stream -U postgres -j 4`
```
postgres@gosmetrika:~$ pg_probackup show
=========================================================================================
ID       Recovery time        Mode          Current/Parent TLI  Time    Data  Status
=========================================================================================
OUGKUU   2017-08-10 10:44:28  FULL+STREAM    1 / 0                13m    92GB  OK
postgres@gosmetrika:~$
```
и сравниваю с оригиналом
```
postgres@gosmetrika:~$ du $PGDATA --summarize -h --exclude=pg_xlog
86G     /var/lib/postgresql/9.6/main
postgres@gosmetrika:~$
```

Вопрос:
как включить сжатие бэкапа?

**Comment by za-arthur** [comment]
Какая у вас версия `pg_probackup`? Что выдает команда
```
pg_probackup --version
```

**Comment by sgrinko** [comment]
Я выполнял обновление всего PostgreSQL с вашего репозитория с версии 9.6.2 до версии 9.6.3

# pg_probackup --version
pg_probackup 1.1.0

**Comment by za-arthur** [comment]
Вам необходим `pg_probackup` версии 2.0. Он появился в `PostgresPro` 9.6.3.2:
[Postgres Pro 9.6.3.2](https://postgrespro.ru/docs/postgrespro/9.6/release-pro-9-6-3-2.html)
Также версию PostgresPro вы можете посмотреть командой:
```
select pgpro_version();
```

**Comment by sgrinko** [comment]
у меня и стоит именно ваша сборка
pgpro_version
PostgresPro 9.6.3.1 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit

Подскажите откуда брать исходники для PostgresPro 9.6.3 для компиляции `pg_probackup` версии 2.0
?

**Comment by za-arthur** [comment]
Вам нужна версия 9.6.3.2 или новее. Сейчас у вас стоит версия 9.6.3.1.
Исходники можете взять по ссылке с этой страницы:
https://postgrespro.ru/products/postgrespro/download/9.6.3.3

**Comment by za-arthur** [comment]
К сожалению, в документации пока не описаны опции для сжатия данных. Необходимо использовать опции `--compress-level` и `--compress-algorithm`:
```
=# pg_probackup --help
...
pg_probackup backup -B backup-path -b backup-mode --instance=instance_name
                 [-C] [--stream [-S slot-name]] [--backup-pg-log]
                 [-j num-threads] [--archive-timeout=archive-timeout]
                 [--compress-algorithm=compress-algorithm]
                 [--compress-level=compress-level]
                 [--progress] [--delete-expired]
                 [-d dbname] [-h host] [-p port] [-U username]
                 [--master-db=db_name] [--master-host=host_name]
                 [--master-port=port] [--master-user=user_name]
                 [--replica-timeout=timeout]
...
```
Получилось ли у вас обновиться до версии 9.6.3.2 или выше?

**Comment by sgrinko** [comment]
Обновиться получилось, однако в документации нет ничего насчёт новых опций
--compress-algorithm и --compress-level
попытка создать бэкап без их указания привела к бэкапу размером 112 Гб

что надо задавать в этих опциях?

**Comment by za-arthur** [comment]
Для этих опций можно задать следующие опции:
* `--compress-algorithm` принимает один из трех возможных значений:
  * `zlib` - сжатие с помощью библиотеки zlib
  * `pglz` - сжатие с помощью алгоритма LZ, в этом случае дополнительные библиотеки не требуются
  * `none` - сжатие выключено, это значение **по умолчанию**
* `--compress-level` принимает значение от 0 до 9, используется если `--compress-algorithm=zlib` и означает уровень сжатия.

**Comment by sgrinko** [comment]
Моё окружение:

```
select pgpro_version()
PostgresPro 9.6.3.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit

-bash-4.2$ pg_probackup --version
pg_probackup 2.0.0
```
Попробовал разные режимы сжатия для алгоритма zlib
Размер моей тестовой БД составляет 92 ГБ (без логов)

выполнял следующие команды:
`pg_probackup backup -b full -U postgres --instance=9.6 --compress-algorithm=zlib --compress-level=<N>
`
вот результаты для разных уровней сжатия:

```
:~$ pg_probackup show
BACKUP INSTANCE '9.6'
===============================================================================================================================
 Instance    ID      Recovery time        Mode    WAL      Current/Parent TLI    Time    Data    Start LSN    Stop LSN   Status
===============================================================================================================================
--compress-level=3
 9.6         OUHLE2  2017-08-11 00:44:28  FULL    ARCHIVE    1 / 0              3892s    21GB  A1/70000060  A1/71000208  OK
--compress-level=5
 9.6         OUI864  2017-08-11 09:05:35  FULL    ARCHIVE    1 / 0              4437s    20GB  A1/73000028  A1/740001D0  OK
--compress-level=7
 9.6         OUIDSW  2017-08-11 11:19:24  FULL    ARCHIVE    1 / 0              5166s    19GB  A1/76000028  A1/7700BE48  OK
--compress-level=9
 9.6         OUIIAK  2017-08-11 13:07:15  FULL    ARCHIVE    1 / 0              5817s    19GB  A1/79000060  A1/7C592450  OK
```
Для меня вполне приемлимым по скорости и размеру подходит `--compress-level=3`

Спасибо!

**Comment by za-arthur** [comment]
Отлично. Спасибо за результаты вашего тестирования!
