### ISSUE TITLE
Archive-get fails to fetch wal segments in Remote mode when log-level-file set to ON

### ISSUE THREAD

**Issue by kuzmindb** [postgrespro/pg_probackup#178]
Archive-get fails to fetch wal segments in Remote mode when log-level-file set to ON with error:

> ERROR: could not open log file "$log_file.log": No such file or directory

How to reproduce:

- Set up backup in Remote Mode
- Set up Continuous WAL Archiving
- Set up logging to file with pg_probackup set-config -B $backup_dir --instance $instance --log-level-file=INFO
- Restore backup to a remote server

As a temporary workaround one can either completely disable logging to file or explicitly pass restore command with --log-level-file=OFF option, e.g.
`pg_probackup restore -B $backup_dir --instance $instance --remote-user $remote_user --remote-host $remote_host --restore-command='pg_probackup archive-get -B $backup_dir --instance $instance --wal-file-path=%p --wal-file-name=%f --remote-host=$remote_host --remote-user=$remote_user --log-level-file off'`

Reported by Artem Dolgih

**Comment by gsmol** [comment]
Fixed
