### ISSUE TITLE
Версия для Windows требует MSVCR120.dll

### ISSUE THREAD

**Issue by ykurenkov** [postgrespro/pg_probackup#179]
![2020-03-02_14-45-19](https://user-images.githubusercontent.com/25895491/75674023-4d00c500-5c95-11ea-806a-23bdf9b30c48.png)
Версия 2.2.7-11-vanilla. Это ошибка сборки или так и должно быть? Не нашел в описании упоминания необходимости установки VCR пакета.

**Comment by gsmol** [comment]
Хм, это же сишный рантайм.
Он разве по умолчанию не должен быть установлен?

**Comment by ykurenkov** [comment]
Server 2012 - нет.

**Comment by ykurenkov** [comment]
На более ранних версиях pg_probackup такого не наблюдал.

**Comment by gsmol** [comment]
Хм, тогда не исключено, что это действительно какой-то наш косяк.
Будем разбираться.

**Comment by VictorSpirin** [comment]
Видимо на компьютере не установлена наша сборка PostgreSQL, с ним ставится  Microsoft Visual C++ 2013 Redistributable,
Вы можете скачать этот пакет отдельно, например есть такая ссылка для 64 бит:  
https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x64.exe

**Comment by ykurenkov** [comment]
Да, там стоит сборка EDB. Установил VCR. Заработало.

**Comment by gsmol** [comment]
Тем ни менее, свои зависимости мы должны приносить самостоятельно.

**Comment by gsmol** [comment]
Исправлено в 2.3.0
