### ISSUE TITLE
Archive-get fails to apply partial compressed WAL segments produced by pg_receivewal

### ISSUE THREAD

**Issue by kuzmindb** [postgrespro/pg_probackup#180]
Archive-get fails to apply partial compressed WAL segments produced by pg_receivewal if it was manually renamed.

pg_probackup version: 2.2.5

Log on restored server:
> INFO: pg_probackup archive-get from /backup/wal/master1/0000000100000000000000B5 to /var/lib/pgpro/std-11/data/pg_wal/RECOVERYXLOG
> INFO: pg_probackup archive-get completed successfully
> 2020-03-03 16:57:13.146 +10 [1675] FATAL:  archive file "0000000100000000000000B5" has wrong size: 5376304 instead of 16777216
> 2020-03-03 16:57:13.149 +10 [1673] LOG:  startup process (PID 1675) exited with exit code 1
> 2020-03-03 16:57:13.149 +10 [1673] LOG:  terminating any other active server processes
> 2020-03-03 16:57:13.164 +10 [1673] LOG:  database system is shut down

**Comment by gsmol** [comment]
Done in 64a90dbb0d6a131b87ac20b1999fee3eb1d262b4
https://github.com/postgrespro/pg_probackup/issues/185
