### ISSUE TITLE
waiting and backup error,why?

### ISSUE THREAD

**Issue by longtian001** [postgrespro/pg_probackup#19]
pg_config

postgresql parameters:

max_wal_senders = 10
wal_level = logical
archive_mode = on
archive_command = 'pg_probackup archive-push -B /db_archive --instance pg10 --wal-file-path %p --wal-file-name %f'
hot_standby = on
full_page_writes = on 

backup steps:

$ pg_probackup init -B /home/postgres/dbbackup
INFO: Backup catalog '/home/postgres/dbbackup' successfully inited
$ pg_probackup add-instance -B /home/postgres/dbbackup -D /pgdata10/ --instance dbtest
INFO: Instance 'dbtest' successfully inited 
$ pg_probackup backup -B /home/postgres/dbbackup --instance dbtest -b full
INFO: wait for WAL segment /home/postgres/dbbackup/wal/dbtest/00000001000000000000000B to be archived
ERROR: switched WAL segment 00000001000000000000000B could not be archived in 300 seconds
$ 

why the status of backup process is "INFO: wait for",then "ERROR" is finished,and no backup files generated

**Comment by za-arthur** [comment]
Hello,

Try to use same name of the instance for the commands:
archive_command = 'pg_probackup archive-push -B /db_archive --instance *pg10* --wal-file-path %p --wal-file-name %f'
$ pg_probackup add-instance -B /home/postgres/dbbackup -D /pgdata10/ --instance *dbtest*

**Comment by longtian001** [comment]
# mkdir /backupdir
# chown postgres.postgres -R /backupdir
# su - postgres
$ pg_probackup init -B /backupdir
$ pg_probackup add-instance -B /backupdir -D /pgdata10/ --instance pg10


### - Archiving - ###
archive_mode = on              
archive_command = 'pg_probackup archive-push -B /backupdir --instance pg10 --wal-file-path %p --wal-file-name %f'

### default ###
max_wal_senders = 10
hot_standby = on
full_page_writes = on



$ pg_probackup show-config -B /backupdir --instance pg10
#Backup instance info
PGDATA = /pgdata10/
system-identifier = 6460263708618119950
#Connection parameters:
PGDATABASE = postgres
#Replica parameters:
#Logging parameters:
#Retention parameters:
#Compression parameters:
compress-algorithm = none
compress-level = 6
[postgres@masterdb ~]$ pg_probackup backup -B /backupdir -b full --instance pg10
INFO: wait for WAL segment /backupdir/wal/pg10/000000010000000000000001 to be archived




ERROR: switched WAL segment 000000010000000000000001 could not be archived in 300 seconds
[postgres@masterdb ~]$ 


if no files found in archive dir , why not make full cluster backup. but still "INFO: wait for XXXX to be archived"

**Comment by za-arthur** [comment]
I got what was the problem. I pushed some commits. Can you try a newer version `2.0.3`?

**Comment by longtian001** [comment]
newer version 2.0.3, release not found

**Comment by longtian001** [comment]
I'v got it,then will try it,pg 10 beta4

**Comment by longtian001** [comment]
hi,za-arthur
execute backup databases is OK,thank you.
but make still waring, as following:

parallel backup
full

[postgres@masterdb ~]$ pg_probackup backup -B /backupdir --instance pg10 -b FULL -j 4
INFO: wait for pg_stop_backup()
INFO: Backup OVL360 completed
[postgres@masterdb ~]$

incremental
[postgres@masterdb ~]$ pg_probackup backup -B /backupdir --instance pg10 -b page  -j 6
INFO: wait for LSN 0/B000028 in archived WAL segment /backupdir/wal/pg10/00000002000000000000000B
INFO: wait for pg_stop_backup()
INFO: Backup OVL3BK completed
[postgres@masterdb ~]$ 
[postgres@masterdb ~]$ 
[postgres@masterdb ~]$ pg_probackup show -B /backupdir --instance pg10 
===============================================================================================================================
 Instance    ID      Recovery time        Mode    WAL      Current/Parent TLI    Time    Data    Start LSN    Stop LSN   Status  
===============================================================================================================================
 pg10        OVL3BK  2017-09-01 12:33:24  PAGE    ARCHIVE    2 / 1                 6s  4417kB   0/B000028    0/C0000F0   OK      
 pg10        OVL360  2017-09-01 12:30:11  FULL    ARCHIVE    2 / 1                13s    31MB   0/9000060    0/9000198   OK      
 pg10        OVKYME  2017-09-01 10:51:56  PAGE    ARCHIVE    1 / 0                 8s  4407kB   0/4000028    0/50000F0   OK      
 pg10        OVKYC7  2017-09-01 10:45:57  FULL    ARCHIVE    1 / 0                17s    31MB   0/2000060    0/2000198   OK      
[postgres@masterdb ~]$ 


restore

[postgres@masterdb ~]$ pg_probackup restore -B /backupdir --instance pg10 -D /pgdata10/ -j 6
INFO: backup validation completed successfully
INFO: Restore of backup OVL3BK completed.
[postgres@masterdb ~]$ pg_probackup show -B /backupdir --instance pg10 -D /pgdata10
===============================================================================================================================
 Instance    ID      Recovery time        Mode    WAL      Current/Parent TLI    Time    Data    Start LSN    Stop LSN   Status  
===============================================================================================================================
 pg10        OVL3BK  2017-09-01 12:33:24  PAGE    ARCHIVE    2 / 1                 6s  4417kB   0/B000028    0/C0000F0   OK      
 pg10        OVL360  2017-09-01 12:30:11  FULL    ARCHIVE    2 / 1                13s    31MB   0/9000060    0/9000198   OK      
 pg10        OVKYME  2017-09-01 10:51:56  PAGE    ARCHIVE    1 / 0                 8s  4407kB   0/4000028    0/50000F0   OK      
 pg10        OVKYC7  2017-09-01 10:45:57  FULL    ARCHIVE    1 / 0                17s    31MB   0/2000060    0/2000198   OK      
[postgres@masterdb ~]$


make(warning)

.make warning still

src/dir.c: In function ‘get_control_value’:
src/dir.c:799:21: warning: ‘buf_uint64_ptr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       buf_uint64_ptr++;


steps:

[root@masterdb postgresql-10beta4]# cd contrib/
[root@masterdb contrib]# cd pg_probackup/
[root@masterdb pg_probackup]# make
rm -f src/datapagemap.h && ln -s ../../../src/bin/pg_rewind/datapagemap.h src/datapagemap.h
rm -f src/logging.h && ln -s ../../../src/bin/pg_rewind/logging.h src/logging.h
rm -f src/receivelog.h && ln -s ../../../src/bin/pg_basebackup/receivelog.h src/receivelog.h
rm -f src/streamutil.h && ln -s ../../../src/bin/pg_basebackup/streamutil.h src/streamutil.h
rm -f src/walmethods.h && ln -s ../../../src/bin/pg_basebackup/walmethods.h src/walmethods.h
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/backup.o src/backup.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/catalog.o src/catalog.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/configure.o src/configure.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/data.o src/data.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/delete.o src/delete.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/dir.o src/dir.c
src/dir.c: In function ‘get_control_value’:
src/dir.c:799:21: warning: ‘buf_uint64_ptr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       buf_uint64_ptr++;
                     ^
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/fetch.o src/fetch.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/help.o src/help.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/init.o src/init.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/pg_probackup.o src/pg_probackup.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/restore.o src/restore.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/show.o src/show.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/status.o src/status.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/util.o src/util.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/validate.o src/validate.c
rm -f src/datapagemap.c && ln -s ../../../src/bin/pg_rewind/datapagemap.c src/datapagemap.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/datapagemap.o src/datapagemap.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/parsexlog.o src/parsexlog.c
rm -f src/xlogreader.c && ln -s ../../../src/backend/access/transam/xlogreader.c src/xlogreader.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/xlogreader.o src/xlogreader.c
rm -f src/streamutil.c && ln -s ../../../src/bin/pg_basebackup/streamutil.c src/streamutil.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/streamutil.o src/streamutil.c
rm -f src/receivelog.c && ln -s ../../../src/bin/pg_basebackup/receivelog.c src/receivelog.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/receivelog.o src/receivelog.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/archive.o src/archive.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/utils/parray.o src/utils/parray.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/utils/pgut.o src/utils/pgut.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/utils/logger.o src/utils/logger.c
rm -f src/walmethods.c && ln -s ../../../src/bin/pg_basebackup/walmethods.c src/walmethods.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/walmethods.o src/walmethods.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 src/backup.o src/catalog.o src/configure.o src/data.o src/delete.o src/dir.o src/fetch.o src/help.o src/init.o src/pg_probackup.o src/restore.o src/show.o src/status.o src/util.o src/validate.o src/datapagemap.o src/parsexlog.o src/xlogreader.o src/streamutil.o src/receivelog.o src/archive.o src/utils/parray.o src/utils/pgut.o src/utils/logger.o src/walmethods.o -L../../src/common -lpgcommon -L../../src/port -lpgport -L../../src/interfaces/libpq -lpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -L../../src/port -L../../src/common -Wl,--as-needed -Wl,-rpath,'/opt/pgsql/10.0/lib',--enable-new-dtags  -lpgcommon -lpgport -lpthread -lz -lreadline -lrt -lcrypt -ldl -lm  -o pg_probackup
[root@masterdb pg_probackup]# make install
/usr/bin/mkdir -p '/opt/pgsql/10.0/bin'
/usr/bin/install -c  pg_probackup '/opt/pgsql/10.0/bin'
[root@masterdb pg_probackup]# 
[root@masterdb pg_probackup]#

**Comment by za-arthur** [comment]
Great! I close this issue. I will fix the warning message within the issue #18.

**Comment by abis8170** [comment]
Hi,
I'm facing below error while i create a backup. Kindly seggest me solution 
**ERROR: Instance 'Test_bkp_1' does not exist in this backup catalog**

Query:
 pg_probackup-9.6 backup  -B /home/Backup -b FULL --instance Test_bkp_1 --retention-redundancy=2 -d test_db -h localhost -p 5432 -U test -w test -j 2

# Backup instance information
pgdata = /home/DB/postgres/data/
system-identifier = 6649958869699190467
# Connection parameters
pgdatabase = test
pghost = localhost
pgport = 5432
pguser = test
# Replica parameters
replica-timeout = 5min
# Archive parameters
archive-timeout = 5min
# Logging parameters
log-level-console = INFO
log-level-file = OFF
log-filename = log_230118
log-directory = /home/DB/pro_log
log-rotation-size = 1MB
log-rotation-age = 0d
# Retention parameters
retention-redundancy = 2
retention-window = 0
# Compression parameters
compress-algorithm = none
compress-level = 1

**Comment by gsmol** [comment]
Hello!
Hm, command below works correctly?
`pg_probackup-9.6 show-config -B /home/Backup -b FULL --instance Test_bkp_1`

**Comment by abis8170** [comment]
No, It's not working getting the same error:

ERROR: Instance 'Test_bkp_1' does not exist in this backup catalog

**Comment by gsmol** [comment]
Ok, what return command below:
`pg_probackup-9.6 show -B /home/Backup`
?

**Comment by gsmol** [comment]
Closed
