### ISSUE TITLE
Archive-get fails to fetch wal segments when RECOVERYXLOG.part already exist

### ISSUE THREAD

**Issue by kuzmindb** [postgrespro/pg_probackup#190]
Archive-get fails to fetch wal segments when RECOVERYXLOG.part already exist

```
INFO: pg_probackup archive-get from /db11/pg_backup/wal/zabbix/000000010000829500000037 to /dbbackup/data/pg_wal/RECOVERYXLOG
ERROR: Cannot open destination temporary WAL file "/dbbackup/data/pg_wal/RECOVERYXLOG.part": File exists
INFO: pg_probackup archive-get from /db11/pg_backup/wal/zabbix/00000001000082940000004B to /dbbackup/data/pg_wal/RECOVERYXLOG
ERROR: Cannot open destination temporary WAL file "/dbbackup/data/pg_wal/RECOVERYXLOG.part": File exists
INFO: pg_probackup archive-get from /db11/pg_backup/wal/zabbix/00000001000082940000004C to /dbbackup/data/pg_wal/RECOVERYXLOG
ERROR: Cannot open destination temporary WAL file "/dbbackup/data/pg_wal/RECOVERYXLOG.part": File exists
INFO: pg_probackup archive-get from /db11/pg_backup/wal/zabbix/00000001000082940000004D to /dbbackup/data/pg_wal/RECOVERYXLOG
ERROR: Cannot open destination temporary WAL file "/dbbackup/data/pg_wal/RECOVERYXLOG.part": File exists
INFO: pg_probackup archive-get from /db11/pg_backup/wal/zabbix/00000001000082940000004E to /dbbackup/data/pg_wal/RECOVERYXLOG
ERROR: Cannot open destination temporary WAL file "/dbbackup/data/pg_wal/RECOVERYXLOG.part": File exists
```
> $ ls -lh
> total 285M
> -rw------- 1 postgres postgres  32M Mar 24 14:29 00000001000082940000004B
> -rw------- 1 postgres postgres  32M Mar 24 14:29 00000001000082940000004C
> -rw------- 1 postgres postgres  32M Mar 24 14:29 00000001000082940000004D
> -rw------- 1 postgres postgres  32M Mar 24 14:29 00000001000082940000004E
> -rw------- 1 postgres postgres  32M Mar 24 14:29 00000001000082940000004F
> -rw------- 1 postgres postgres  32M Mar 24 14:29 000000010000829400000050
> -rw------- 1 postgres postgres  32M Mar 24 14:29 000000010000829400000051
> -rw------- 1 postgres postgres  32M Mar 24 14:29 000000010000829500000037
> drwx------ 2 postgres postgres 4.0K Mar 24 14:29 archive_status
> -rw------- 1 postgres postgres  29M Mar 24 14:29 RECOVERYXLOG.part

**Comment by gsmol** [comment]
Fixed in 64a90dbb0d6a131b87ac20b1999fee3eb1d262b4
