### ISSUE TITLE
ASTRALINUX is support?

### ISSUE THREAD

**Issue by vitassecuriti** [postgrespro/pg_probackup#193]
ASTRALINUX is supported?

**Comment by gsmol** [comment]
Hello!
Yes, we just don`t packaging it, because it is not very widespread and there was no requests from users for us to do so.
But I assume you are requesting it now, right?

**Comment by vitassecuriti** [comment]
No. I do research and find solutions for my tasks. I consider different decisions. There are requirements for the operating system (should work on Astra Linux 1.6.), so clarified about the possibility of working under a specific OS, which did not see in the list of supported

**Comment by gsmol** [comment]
It is supported just like any Linux distribution, that PostgreSQL supports.
Binaries can be compiled.
We just don`t packaging those binaries for Astra.
But we can start doing that if there is a demand for it.

**Comment by slothfk** [comment]
It can be actual to government customers
We have some government projects on AstaLinux and we will be happy to use probackup on them
As example
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: AstraLinuxCE
Description:    Astra Linux CE 2.12.42 (Orel)
Release:        2.12.42
Codename:       orel
```

**Comment by gsmol** [comment]
Hello!
Ok, I suppose we can do that.

**Comment by slothfk** [comment]
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: AstraLinuxCE
> Description:    Astra Linux CE 2.12.42 (Orel)
> Release:        2.12.42
> Codename:       orel

As example, for this Astra version may be used packages for **stretch** release

**Comment by gsmol** [comment]
Добавил инструкции по установке
https://github.com/postgrespro/pg_probackup#linux-installation
