### ISSUE TITLE
can we use pg_probackup  with native postgresql?

### ISSUE THREAD

**Issue by tengilim** [postgrespro/pg_probackup#199]
Hi;

  Is pg_probackup compatible with native(community) postgresql? can i use it on  native postgresql without any problem?

thank you.

**Comment by gsmol** [comment]
Hello!
Yes, it is fully compatible starting from 9.5 version. Sure you can, just use vanilla repo:
https://github.com/postgrespro/pg_probackup#pg_probackup-for-vanilla-postgresql

**Comment by gsmol** [comment]
Do you have any more questions or we can close this issue?

**Comment by tengilim** [comment]
Thank you.
