### ISSUE TITLE
Is pg_probackup support compress when taking a backup?

### ISSUE THREAD

**Issue by killua001** [postgrespro/pg_probackup#2]
Is pg_probackup support compress when taking a backup?

**Comment by stalkerg** [comment]
Currently we are removing free space from pages only. 
Truly compressing with libz or similar library we planning in near future.

**Comment by killua001** [comment]
Thank you。 And when will this project release？

**Comment by stalkerg** [comment]
> Thank you。 And when will this project release？
I suppose until 1 December. I mean 1.0 version.

**Comment by stalkerg** [comment]
We have released version 1.0.

**Comment by killua001** [comment]
Great work!

Thank you.

**Comment by gsmol** [comment]
Data and WAL files are supported starting from version 2.0.14
