### ISSUE TITLE
backup failed with "ERROR: query failed: ERROR:  function pg_control_system() does not exist"

### ISSUE THREAD

**Issue by rtau-t24** [postgrespro/pg_probackup#20]
We are trying to backup the PostgreSQL 9.5 database with pg_probackup 2.0.11 but when trying to run the backup, the following error was encountered:

> LOG: (query) show archive_command
> LOG: (query) SELECT system_identifier FROM pg_control_system()
> ERROR: query failed: ERROR:  function pg_control_system() does not exist
> LINE 1: SELECT system_identifier FROM pg_control_system()
>                                       ^
> HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
> query was: SELECT system_identifier FROM pg_control_system()
> 

In addition, it seems that the function pg_control_system() does not exist in 9.5, but only 9.6 and newer.

**Comment by za-arthur** [comment]
Thank you for the issue!
Yeah it is definitely a bug. PostgreSQL hasn't `pg_control_system()`.

**Comment by za-arthur** [comment]
I changed the function a little bit. Now it checks system_identifier for PostgreSQL 9.5 using `pg_read_binary_file()`.
