### ISSUE TITLE
pg_probackup: unexpected termination of replication stream: ERROR:  requested WAL segment has already been removed

### ISSUE THREAD

**Issue by mkdel** [postgrespro/pg_probackup#202]
Hi

I run backup as:
pg_probackup-9.6 backup -B /mnt/probackup/ --instance 'myserver' -b FULL --stream --remote-host=192.168.1.1 --remote-user=postgres -U backup -d backupdb --progress -j 2

And then happened:
INFO: Progress: (409635/1153182). Process file "base/16388/51635619"
pg_probackup: unexpected termination of replication stream: ERROR:  requested WAL segment 00000001000004A500000032 has already been removed
ERROR: Problem in receivexlog
ERROR: interrupted during backup

Postgres log:
INFO: PID [27236]: pg_probackup archive-push WAL file: 00000001000004A500000032, threads: 1/1, batch: 1/1, compression: zlib
INFO: PID [27236]: pg_probackup archive-push completed successfully, pushed: 1, skipped: 0, time elapsed: 878ms

But this WAL was received and is in:
/mnt/probackup/wal/myserver/00000001000004A500000032.gz
-rw-------. 1 postgres postgres 1516504 May  7 14:39 00000001000004A500000032.gz

Did I miss something?

**Comment by gsmol** [comment]
Hello!
Error message is about WAL segment been rotated by checkpointer before pg_probackup received it. The usual remedy for this is to instruct pg_probackup to use temp replication slot via `--temp-slot` option.
BUT it would seems that you have WAL archiving enabled, which begs the question why are you taking STREAM backup (`--stream` option)?

**Comment by mkdel** [comment]
That's right! Oh, silly me!

I missed the part of difference between ARCHIVE and STREAM methods.
Yes, --temp-slot looks nice for STREAM backup, though, I prefer just get rid of '--stream' option due to enabled continuous WAL archiving.

Thank you a lot!

**Comment by gsmol** [comment]
You are welcome!
