### ISSUE TITLE
archive command get an error

### ISSUE THREAD

**Issue by tengilim** [postgrespro/pg_probackup#204]
Hi;

    When I set up backup environment with pg_probackup  the archive command get an error. 

Error: 

DETAIL:  The failed archive command was: /usr/bin/pg_probackup-10 archive-push -B /dbbackupsisi/PGBackups/pg_probackup  --instance  YYYY --wal-file path=pg_wal/00000005000000B9000000F9 --wal-file-name=00000005000000B9000000F9  --remote-host=XXXX                                                                                                                                                 
ERROR: -B, --backup-path must be a path to directory      

archive command:

archive_command = '/usr/bin/pg_probackup-10 archive-push -B /dbbackupsisi/PGBackups/pg_probackup/  --instance YYYY --wal-file-path=%p --wal-file-name=%f  --remote-host=XXXX'

I have no idea what the problem is...

Thank you..

**Comment by gsmol** [comment]
Hello!
Please run the following command on backup server and post the output:
```
stat /dbbackupsisi/PGBackups/pg_probackup
```

**Comment by tengilim** [comment]
Hi;
  output is below

 File: ‘/dbbackupsisi/PGBackups/pg_probackup’                                                                                                      
 Size: 0               Blocks: 0          IO Block: 16384  directory                                                                               
Device: 25h/37d Inode: 9867272491  Links: 2                                                                                                         
Access: (0777/drwxrwxrwx)  Uid: (   26/postgres)   Gid: (    0/    root)                                                                            
Access: 2020-04-21 15:58:34.133956900 +0300                                                                                                         
Modify: 2020-04-21 15:58:34.133956900 +0300                                                                                                         
Change: 2020-04-21 15:58:34.133956900 +0300                                                                                                         
 Birth: -


backups of 4 different servers are taken over this backup server. So I have 4 instance... This is the fifth server and fifth instance. There was no problem with other servers but I had such a problem with this server.

**Comment by gsmol** [comment]
That is strange, how directory can be of size 0?

**Comment by gsmol** [comment]
I can provide you with package of custom binary, that will report additional information to further investigate this problem

**Comment by tengilim** [comment]
Other backups and archive wal files are taken to the same place, but there is no problem with them.

**Comment by gsmol** [comment]
What is the pg_probackup version you are using?

**Comment by tengilim** [comment]
on backup_server
pg_probackup-10 2.2.7 (PostgreSQL 10.10)                                                                                                            

on postgres server
pg_probackup-10 2.3.1 (PostgreSQL 10.12)

**Comment by alexign** [comment]
Hello @tengilim !
Is the same version of probackup installed on all postgresql server you’ve mentioned above?

**Comment by gsmol** [comment]
I`ve managed to reproduce your issue.
pg_probackup requires that binaries on local and remote systems to be of the same version.
Version mismatch should be detected and error issued:
```
ERROR: Agent error: ERROR: Agent version 2.3.2 doesn't match master pg_probackup version 2.2.7
```
BUT it appears that in case of archive-push version matching works incorrectly. It is a bug.
You should either update your backup server binary to 2.3.1 or downgrade binary on postgres server to 2.2.7

**Comment by tengilim** [comment]
I think minor versions are different. I installed the pg_probackup the latest postgresql server 2 days ago.  this server's  pg_probackup version is 2.3.1 . The other postgresql server's and backup server's pg_probackup version is  2.2.7 . So just minor version is different

**Comment by tengilim** [comment]
"downgrade binary on postgres server to 2.2.7" how can I do this?

**Comment by gsmol** [comment]
> "downgrade binary on postgres server to 2.2.7" how can I do this?
>
What OS you are using?

**Comment by tengilim** [comment]
centOS7

**Comment by gsmol** [comment]
1. You must edit repo file `/etc/yum.repos.d/pg_probackup.repo` and change `latest` to `2.2.7`:
baseurl=https://repo.postgrespro.ru/pg_probackup/rpm/2.2.7/centos-$releasever-$basearch
2. Clean cache: `yum clean all`
3. Reinstall package: `yum remove pg_probackup-10 && yum install pg_probackup-10`

**Comment by tengilim** [comment]
thank you let me try

**Comment by gsmol** [comment]
Did it work?

**Comment by tengilim** [comment]
Yes  it did. After change version I made del-instance add-instance again and now it works normaly . Thanks a lot.

**Comment by gsmol** [comment]
I would recommend to upgrade all binaries to upcoming 2.3.3 at some point.

**Comment by tengilim** [comment]
Maybe  later. Thank you again

**Comment by gsmol** [comment]
You are welcome

**Comment by gsmol** [comment]
2.3.3 released

**Comment by tengilim** [comment]
thank you for informing
