### ISSUE TITLE
.pgpass support

### ISSUE THREAD

**Issue by deric** [postgrespro/pg_probackup#206]
In the documentation there are examples with `pgpass` file, however the `primary_conninfo` doesn't seem to be supported in current version:

```
primary_conninfo = 'user=backup passfile=/var/lib/pgsql/.pgpass port=5432 sslmode=disable sslcompression=1 target_session_attrs=any'
```
The backup command doesn't seem to parse .pgpass file in `$HOME/.pgpass`, is there a way how to force this?

When running with `-w` the `.pgpass` doesn't seem to be checked:
```
ERROR: could not connect to database backup: fe_sendauth: no password supplied
```

**Comment by gsmol** [comment]
Hello!
`.pgpass` is parsed by libpq library, not by pg_probackup itself (which is a good thing).
You can try to run `backup` with `strace` to determine whether `.pgpass` is accessed or not:
```
strace -o /tmp/strace.log -e trace=openat,read pg_probackup backup ...
```

**Comment by deric** [comment]
@gsmol You're right, thanks! 

For debugging `stat` seems to be useful:
```
strace -o /tmp/strace.log -e trace=stat,read pg_probackup backup
```
I was using `pg_probackup backup .. -b DELTA --stream` and I was missing password for `replication` database:
```
db01.example.net:5432:backup:backup:s3cr3tP1sswd
db01.example.net:5432:replication:backup:s3cr3tP1sswd
```
which isn't exactly clear from the password prompt. Maybe it's worth mentioning in the documentation.

**Comment by gsmol** [comment]
Good idea.
Thank you for your feedback!
