### ISSUE TITLE
Поддерживает ли версию с патчами 1с?

### ISSUE THREAD

**Issue by haronkz** [postgrespro/pg_probackup#211]
Добрый день. Скажите поддерживает ли версия pg_probackup 2.3.3 для ванильного PostgreSQL сборки с сайта https://1c.postgres.ru  ?

**Comment by gsmol** [comment]
Добрый.
Да, поддерживает:
https://github.com/postgrespro/pg_probackup#pg_probackup-for-vanilla-postgresql

**Comment by gsmol** [comment]
Можем закрывать или есть еще вопросы?

**Comment by haronkz** [comment]
Спасибо. Закрывайте.
