### ISSUE TITLE
пути бинарников при установке из пакетов

### ISSUE THREAD

**Issue by triwada** [postgrespro/pg_probackup#216]
почему пакеты называются по-разному, а бинарники устанавливаются в разные каталоги и называются иначе?
RHEL 7 
$ rpm -qa | grep probackup
pg-probackup-ent-9.6-2.2.7-1.el7.x86_64  -> /usr/pgproee-9.6/bin/pg_probackup
pg_probackup-ent-9.6-2.3.3-1.6a736c2db6402d77.x86_64 -> /usr/bin/pg_probackup-ent-9.6

**Comment by gsmol** [comment]
Добрый день.
Дело в том, что это пакеты из разных репозиториев.
> pg-probackup-ent-9.6-2.2.7-1.el7.x86_64
>
Это пакет из репозитория Postgrespro Enterprise.

>pg_probackup-ent-9.6-2.3.3-1.6a736c2db6402d77.x86_64
>
Это пакет из репозитория pg_probackup.

**Comment by triwada** [comment]
pg-probackup-ent-9.6 - наличие ent  и так говорит о том, что пакет относится к Enterprise. В чём отличие?

**Comment by triwada** [comment]
в чём логика разного именования бинарников?

**Comment by gsmol** [comment]
Нет логики, просто эти репозитории пилят разные команды.
Отсюда и расхождение.

**Comment by triwada** [comment]
есть ли разница между бинарниками pg-probackup-ent-9.6 версии 2.3.3 для разных репозиториев? или это по сути одинаковый пакет, просто в разных репозиториях называется иначе?

**Comment by gsmol** [comment]
> есть ли разница между бинарниками pg-probackup-ent-9.6 версии 2.3.3 для разных репозиториев? и
>
Разницы нет, они собираются из одних и тех же исходников.
На уровне политики самих репозиториев есть разница, в частности EE репо обновляется значительно реже.

**Comment by triwada** [comment]
спасибо за разъяснения
