### ISSUE TITLE
Важная информация отображалась другим цветом.

### ISSUE THREAD

**Issue by haronkz** [postgrespro/pg_probackup#224]
Когда много экземпляров PG, не совсем удобно мониторить список бекапов командой "show". Возможно ли добавить в "set-config" настройки цветовых вариантов? Сейчас настраиваю grc   для этих целей. Получается примерно так.

![image](https://user-images.githubusercontent.com/29562044/84006706-035d0000-a991-11ea-93da-23de7997917e.png)

**Comment by gsmol** [comment]
Добрый день!
Выглядит как что-то полезное, попробуем сделать.

**Comment by haronkz** [comment]
Я далек от С, но может это как-то будет полезно и сэкономит вам время.
https://lhs-blog.info/programming/dlang/tsvetnoy-vyivod-teksta-v-terminale-linux/

**Comment by gsmol** [comment]
Спасибо, лишним не будет.

**Comment by gsmol** [comment]
Вариант 1:
![color](https://user-images.githubusercontent.com/13132209/86498124-16df6900-bd8d-11ea-8dcb-df6392d9270f.png)

Вариант 2 (bold):
![color_1](https://user-images.githubusercontent.com/13132209/86498150-25c61b80-bd8d-11ea-8a23-0391afd77711.png)

**Comment by gsmol** [comment]
+Status:
![show_color](https://user-images.githubusercontent.com/13132209/86527639-bdb92780-bea9-11ea-9b42-20cea7acc613.png)

**Comment by gsmol** [comment]
I`m thinking, that we probably should also color the `WARNING` and `ERROR` messages.

**Comment by gsmol** [comment]
+ Сообщения:
![color_messages](https://user-images.githubusercontent.com/13132209/86588809-12859c80-bf95-11ea-8d38-91ab7ecca335.png)

**Comment by gsmol** [comment]
+ New flag: `--color`

**Comment by gsmol** [comment]
+Windows support:
![win_color](https://user-images.githubusercontent.com/13132209/86627523-23ec9a00-bfd1-11ea-885e-91dc02a9a326.jpg)

**Comment by gsmol** [comment]
Готово, можно опробовать в ветке issue_224

**Comment by gsmol** [comment]
Смержено.
