### ISSUE TITLE
2.3.5: проблема восстановления на удалённый хост

### ISSUE THREAD

**Issue by ykurenkov** [postgrespro/pg_probackup#229]
Ubuntu 18.04. Была рабочая схема, котрая работала на 2.2.5: делаем бэкап, а потом его восстанавливаем на удалённый хост командой

`pg_probackup-10 restore -B /nfsbackup --instance ppak_kis -i QBXP01 --remote-host=m65-tppgkis-01 --remote-user=postgres --no-validate --log-level-console=VERBOSE --log-level-file=VERBOSE`

После апгрейда pg_probackup до 2.3.5 при попытки восстановиться из только что сделанного 2.3.5 бэкапа получаем сообщение об ошибке:

```
pg_probackup-10 restore -B /nfsbackup --instance ppak_kis -i QBXP01 --remote-host=m65-tppgkis-01 --remote-user=postgres --no-validate --log-level-console=VERBOSE --log-level-file=VERBOSE
LOG: Start SSH client process, pid 121065
ERROR: Agent error: ERROR: Unknown subcommand "agent"
```
Выполнение прерывается. На 2.2.5 все работало.

**Comment by gsmol** [comment]
Добрый день!
Похоже, что бинарь на машине m65-tppgkis-01 остался старой версии.

**Comment by ykurenkov** [comment]
А он там нужен?

**Comment by gsmol** [comment]
Конечно, нам же нужен агент на удаленной стороне, который будет данные принимать и записывать, репортить ошибки и т.д.

**Comment by ykurenkov** [comment]
Тогда я не понял режим удалённой работы. Да, действительно там был обнаружен 2.1.5. Проапгрейдил его до 2.3.5. Процесс пошел...

**Comment by gsmol** [comment]
К слову сказать, в доке я не нашел упоминаний о том, что версии локального и удаленного бинарей должны совпадать. Исправим.
Спасибо за фидбэк!

**Comment by ykurenkov** [comment]
Я не нашел в упоминании, что pg_probackup нужен как на локальном хосте с бэкапом, так и на удалённом. И соответственно вопрос: как отработают в случае разной ОС.? Напимер с линуксовой машины захочерся удалённо бэкапить и восстанавливать виндовый сервер.

**Comment by gsmol** [comment]
> Я не нашел в упоминании, что pg_probackup нужен как на локальном хосте с бэкапом, так и на удалённом. 
>
Это есть:
When started in the remote mode, the main pg_probackup process on the local system connects to the remote system via SSH and launches one or more agent processes on the remote system, which are called remote agents. The number of remote agents is equal to the -j/--threads setting.

https://postgrespro.github.io/pg_probackup/#pbk-configuring-the-remote-mode

> И соответственно вопрос: как отработают в случае разной ОС.? Напимер с линуксовой машины захочется удалённо бэкапить и восстанавливать виндовый сервер.
>
На юниксовых машинах(Linux->FreeBSD) по идее никаких проблем быть не должно. С виндовым не получится - пробэкап процесс, запущенный в режиме агента, упадет с ошибкой, потому что сейчас удаленный режим для винды не поддерживается.
Этот вопрос приобретет остроту, когда мы его таки начнем поддерживать и для винды, и такая конфигурация станет потенциально возможной.

**Comment by gsmol** [comment]
Добавил уточнение в документацию.
