### ISSUE TITLE
Неверно формируется путь к БД

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/pg_probackup#23]
Окружение:
был установлен postgres версии standard 10.1 (был применен pg-wrapper)
было принято решение уйти на ваниль.
постгрес standard 10.1 был остановлен и установлена сборка от EDB 10.2
выполнен откат ссылок pg-wrapper links remove
установлен pg_probackup c github версии 2.0.15
при настройке архивной команды получил вот такие сообщения о ошибках
обратите внимание, что несмотря на то, что в файле конфигурации pg_probackup.conf указан каталог верно, почему-то неверно конструируется путь к файлу pg_control
```
# su - postgres
$  pg_probackup archive-push -B /mnt/pgbak --instance 10 --wal-file-path pg_wal/000000010000000F000000B0 --wal-file-name 000000010000000F000000B0
ERROR: could not open file "/var/lib/postgresql/global/pg_control" for reading: No such file or directory
$ echo $PGDATA
/var/lib/postgresql/10
$  pg_probackup archive-push  -D /var/lib/postgresql/10/ -B /mnt/pgbak --instance 10 --wal-file-path pg_wal/000000010000000F000000B0 --wal-file-name 000000010000000F000000B0
ERROR: could not open file "/var/lib/postgresql/global/pg_control" for reading: No such file or directory
$ cat /mnt/pgbak/backups/10/pg_probackup.conf
#Backup instance info
PGDATA = /var/lib/postgresql/10
system-identifier = 6524228009296411443
#Connection parameters:
#Replica parameters:
#Logging parameters:
#Retention parameters:
retention-window = 7
#Compression parameters:
compress-algorithm = zlib
compress-level = 6
postgres@pardalis:~$
```
что сделать ?

**Comment by gsmol** [comment]
Спасибо за баг-репорт. Сейчас попробуем воспроизвести, и мы либо дадим какие-то рекомендации, либо выпустим баг-фикс.

**Comment by gsmol** [comment]
Проблема на самом деле состоит в следующем. Archive-push предполагает, что текущая директория соответствует PGDATA(что соответствует действительности, если archive-push был вызван процессом архивации) и обращения к файлам внутри осуществляется по относительному пути. Поэтому запуск archive-push руками привел к описанному вами поведению.
Можно, конечно, поменять это поведение и сконструировать абсолютный путь, опираясь на параметр PGDATA в конфиге.
Однако в этом случае у нас не будет 100% гарантии, что мы кладем в архив логи того же экземпляра, что нас вызвал. Например, если рядом с экземпляром A(/var/lib/pgsql/pgdata) восстановить экземпляр B (/var/lib/pgsql/pgdata_new), то вызов archive-push приведет к тому, что мы будем пытаться архивировать сегменты из директории экземпляра А (/var/lib/pgsql/pgdata).

**Comment by sgrinko** [comment]
на самом деле проблема в том, что это происходит при вызове pg_probackup из архивной команды:
```
archive_command = 'if [ -f archive_active.trigger ]; then test ! -f /mnt/pgbak/wal/10/%f && pg_probackup archive-push -B /mnt/pgbak --instance 10 --wal-file-path %p --wal-file-name %f; else exit 0; fi'
```
и в логах при этом я вижу следующее:
```
2018-02-27 16:21:37.080 MSK [14269]: [386-1] user=[],db=[],app=[],client=[], [vxid: txid:0] [] LOG:  archive command failed with exit code 127
2018-02-27 16:21:37.080 MSK [14269]: [387-1] user=[],db=[],app=[],client=[], [vxid: txid:0] [] DETAIL:  The failed archive command was: if [ -f archive_active.trigger ]; then test ! -f /mnt/pgbak/wal/10/000000010000000F000000B0 && pg_probackup archive-push -B /mnt/pgbak --instance 10 --wal-file-path pg_wal/000000010000000F000000B0 --wal-file-name 000000010000000F000000B0; else exit 0; fi
sh: 1: pg_probackup: not found
2
```
и вот только после этого я попытался запустить руками, чтобы понять а что собственно происходит???
эта проблема началась как только я выполнил pg-wrapper links remove
а до этого всё шло хорошо:
```
INFO: pg_probackup archive-push from /var/lib/postgresql/10/pg_wal/000000010000000F00000062 to /mnt/pgbak/wal/10/000000010000000F00000062
INFO: WAL file compressed to "/mnt/pgbak/wal/10/000000010000000F00000062.gz"
INFO: pg_probackup archive-push completed successfully
2
```

сейчас на сервере у меня работает только 1 кластер постгреса.
Как решать эту проблему?

**Comment by gsmol** [comment]
> 2018-02-27 16:21:37.080 MSK [14269]: [386-1] user=[],db=[],app=[],client=[], [vxid: txid:0] [] LOG:  archive command failed with exit code 127
>2018-02-27 16:21:37.080 MSK [14269]: [387-1] user=[],db=[],app=[],client=[], [vxid: txid:0] [] DETAIL:  The failed archive command was: if [ -f archive_active.trigger ]; then test ! -f /mnt/pgbak/wal/10/000000010000000F000000B0 && pg_probackup archive-push -B /mnt/pgbak --instance 10 --wal-file-path pg_wal/000000010000000F000000B0 --wal-file-name 000000010000000F000000B0; else exit 0; fi
>sh: 1: pg_probackup: not found

Похоже что pg-wrapper links remove удалил из $PATH симлинк на pg_probackup.
Я бы посоветовал использовать полный путь до бинарника pg_probackup в archive_command

**Comment by sgrinko** [comment]
спасибо за подсказку...
я настроил себе ссылку в /usr/bin на файл pg_probackup-10 и всё заработало.
у меня такая же ссылка есть и в каталоге bin кластера (/opt/postgresql/10/bin) и я также настраивал $PATH с доступом в этот каталог (/etc/profile.d/...). Однако наверное запущенный процесс сервера эти изменения не подхватил, и у меня создалось ложное впечатление о правильной работе до применения pg-wrapper links remove.

Однако, всё же я бы хотел иметь подобную настройку:

> Возможно, стоит сделать отдельную опцию, при наличии которой archive-push будет проверять соответствие PGDATA и забирать WAL логи по абсолютному пути.

**Comment by gsmol** [comment]
>обратите внимание на параметр --stream и вывод stream: false
>наверное здесь небольшой баг?
Да, мы его буквально пару дней назад пофиксили.

**Comment by gsmol** [comment]
Кстати, в проверке:
>then test ! -f /mnt/pgbak/wal/10/%f 
нет необходимости и более того, она вредна, потому что в конце копирования сегмента в архив совершается атомарный rename, поэтому если файл уже есть в архиве, то он либо находится там на законных основаниях, либо нет. Таким образом ваша проверка может  скрыть от Вас незаконное появление файла в архиве и Вы, таким образом, рискуете получить неработоспособный архив.

**Comment by sgrinko** [comment]
Спасибо, уберу.

**Comment by za-arthur** [comment]
Спасибо большое за тикет! Закрываем?
