### ISSUE TITLE
Несколько бэкапов могут получить одинаковый ID

### ISSUE THREAD

**Issue by dlepikhova** [postgrespro/pg_probackup#231]
Несколько подряд запускаемых бэкапов могут получить одинаковый ID, если первый из них завершился с ошибкой

Прикладываю свой скрипт (в архиве), который запускала для проверки 
[backup.zip](https://github.com/postgrespro/pg_probackup/files/4779469/backup.zip)
В результате в логе ошибки вида 
ERROR: backup destination is not empty "<ссылка на директорию>"

![Снимок экрана_2020-06-15_11-51-03](https://user-images.githubusercontent.com/43872363/84639966-8393e000-af12-11ea-9ff6-20a467da61d1.jpg)

**Comment by gsmol** [comment]
Добрый день!
Это происходит, потому что айдюк бэкапа - это base36 от start_time, у которого секундная гранулярность.
Попробуем пофиксить.

**Comment by gsmol** [comment]
Merged.
