### ISSUE TITLE
segfault при попытке создания резервной копии

### ISSUE THREAD

**Issue by dimv36** [postgrespro/pg_probackup#24]
Добрый день.

Использую PostgreSQL 10.3 vanilla с патчем ptrack из Вашего README (https://gist.githubusercontent.com/gsmol/0ce69df847268333b72d72079bd48315/raw/d35d49c28446637ea3fe9dfc1a400bb298bf3318/ptrack_10.0_v1.3.patch)

pg_probackup используется 2.16, скачанный из master-ветки Вашего репозитория.

Инициализировал каталог копий в /home/developer/bak и зарегистрировал инстанс test10.
Пытаюсь создать резервную копию следующей командой:

``
pg_probackup backup -B /home/developer/bak/ -b FULL --instance test10 -U backup -d postgres -h 127.0.0.1 --stream
``

Пользователю backup выданы все необходимые права (REPLICATION и на функции из Вашей документации).

Получаю следующий выхлоп:

> INFO: Backup start, pg_probackup version: 2.0.16, backup ID: P5OEG9, backup mode: full, instance: test10, stream: true, remote: false
WARNING: This PostgreSQL instance initialized without data block checksums. pg_probackup have no way to detect data block corruption without them. Reinitialize PGDATA with option '--data-checksums'.
WARNING: Update your ptrack to the version 1.5. Current version is 1.3
Password for user backup:
INFO: pg_stop backup() successfully executed
номер записи 0 вне диапазона 0..-1
Ошибка сегментирования

Вопрос, связано ли это с устаревшей версией патча на ptrack, и если да, не могли бы ее обновить?

**Comment by gsmol** [comment]
Добрый день!
Да, связано. Выложим в течение дня.
И, очевидно, вместо WARNING`а мы должны возвращать ERROR, чтобы сегфолтов не было. 
Большое спасибо за фидбэк!

**Comment by gsmol** [comment]
А можете повторно запустить бэкап с опцией --log-level-file=verbose и прислать содержимое лог-файла?

**Comment by dimv36** [comment]
Хорошо, пришлю, но не раньше понедельника.

**Comment by dimv36** [comment]
Как и обещал, вот содержимое лог-файла:

[pg_probackup.log](https://github.com/postgrespro/pg_probackup/files/1823935/pg_probackup.log)

**Comment by gsmol** [comment]
Добрый день.
Похоже, что дело не в ptrack, а в отсутствии прав на ф-цию pg_stop_backup.
При этом мы некорректно проверяем результат выполнения этого запроса, что и приводит к сегфолту.
Это баг. И отсутствие в документации корректного DDL для PostgreSQL 10 - баг.
И тот факт, что мы перед запуском не проверяем предоставлены ли нашему пользователю права на все необходимые ему в работе ф-ции - тоже баг.
Спасибо, что обратили наше внимание на эту проблему.
Быстрым промежуточным решением будет:
GRANT EXECUTE ON FUNCTION pg_catalog.pg_stop_backup(boolean, boolean) TO backup;

**Comment by dimv36** [comment]
Что ж, рад помочь. Возвращаясь к вопросу про патч ptrack, будет ли он актуализирован?

**Comment by gsmol** [comment]
Обновил ссылки.

**Comment by dimv36** [comment]
Спасибо!

**Comment by gsmol** [comment]
Пакеты с релизом 2.0.17 доступны из репозитория.
