### ISSUE TITLE
restore с сервера на который хочу восстановиться.

### ISSUE THREAD

**Issue by Guzya** [postgrespro/pg_probackup#242]
Здравствуйте!
Не смог понять имеется ли возможность, вызвать команду restore  не с сервера где лежат бэкапы, а с сервера на котором
хочу восстановить бэкап?
Т.е. имеется сервер резервного копирования (СРК), имеется сервер на который хочу развернуть бэкап (сервер_Б).
Я могу запустить restore на СРК указав remote-host и все отработает.
Но как запустить restore с сервера_Б, как указать где находиться СРК?

Для чего нужно, хочу попробовать подружить с patroni, что бы при разворачивании узла он брал бэкап с СРК.

**Comment by gsmol** [comment]
Добрый день!
Мы над этим работаем в рамках:
https://github.com/postgrespro/pg_probackup/issues/233

Будет в версии 2.5

**Comment by Guzya** [comment]
Спасибо!
