### ISSUE TITLE
Архивирование WAL должно делаться только в pg_probackup.

### ISSUE THREAD

**Issue by Guzya** [postgrespro/pg_probackup#243]
Здравствуйте!
Верно ли я понимаю, что для выполнения бэкапа в режиме Archive в обязательном порядке wal должны архивироваться именно в структуру каталогов pg_probackup.
Т.е. имеется сервер А на котором настроено архивирование на сервер\хранилище Б.
Мы решаем внедрить pg_probackup, устанавливаем его на сервере В.
Теперь нам для работы pg_probackup в режиме Archive или резервного копирования PAGE надо перенастроить архивирование на сервер В (в каталог pg_probackup)?
И если этого не сделать, нам будет доступно только FULL Stream и DELTA Stream, но при этом мы при восстановлении сможем указывать параметры archive-* или restore-command, для извлечения wal с сервера\хранилища Б?

**Comment by gsmol** [comment]
Добрый день!



> Здравствуйте!
> Верно ли я понимаю, что для выполнения бэкапа в режиме Archive в обязательном порядке wal должны архивироваться именно в структуру каталогов pg_probackup.
Да, верно. pg_probackup в процессе создания бэкапа должен быть уверен, что диапазон WAL, необходимый для консистентного восстановления, присутствует и находится в корректном состоянии.

> Теперь нам для работы pg_probackup в режиме Archive или резервного копирования PAGE надо перенастроить архивирование на сервер В (в каталог pg_probackup)?
>
На данный момент, к сожалению, да. Наверное, можно было бы ходить по ssh на сервер Б, но pg_probackup пока так не умеет.

> И если этого не сделать, нам будет доступно только FULL Stream и DELTA Stream, но при этом мы при восстановлении сможем указывать параметры archive-* или restore-command, для извлечения wal с сервера\хранилища Б?
>
Да, конечно, можете, но в этом случае Вам будет недоступна валидация PITR. Т.е. если на сервере Б пропадет и побьется какой-то сегмент WAL, то Вы об этом узнаете (если узнаете) только уже в процессе recovery.

**Comment by Guzya** [comment]
Спасибо за ответ!
Есть еще один вопрос.
В ходе экспериментов проделал следующую штуку, создал FULL --Archive бэкап, после это создал множество разных
инкрементальных бэкапов как Archive  так и Stream. После этого зачистил ту самую папку WAL.
Как и ожидал я не смог восстановиться ни на один из бэкапов Archive, однако смог восстановиться на все 
бэкапы сделанные в режиме Stream. Собственно вопрос в том, это так задумано, там в связи с отсутствием wal-ов на FULL бэкапе ни чего не пропадет?

**Comment by gsmol** [comment]
Бэкап в режиме STREAM во время работы по протоколу потоковой репликации забирает WAL в `pg_wal` директорию в бэкапе. Это позволяет ему быть независимым от архива с точки зрения восстановления на консистетное состояние.

> Собственно вопрос в том, это так задумано, там в связи с отсутствием wal-ов на FULL бэкапе ни чего не пропадет?
>
Я правильно понимаю, что вопрос звучит так: "Безопасно ли восстанавливать инкрементальный бэкап, сделанный в режиме STREAM, если его FULL предок, сделанный в режиме ARCHIVE, потерял свой WAL?" Да, безопасно. В любом случае перед восстановление неявно запускается валидация, которая не позволит сделать потенциально опасное восстановление.

**Comment by Guzya** [comment]
Спасибо, вопрос был именно об этом!

**Comment by gsmol** [comment]
Закрываем?

**Comment by Guzya** [comment]
Да, спасибо!
