### ISSUE TITLE
Support from remote server

### ISSUE THREAD

**Issue by internetuser2008** [postgrespro/pg_probackup#25]
Please add support for remote server backup, similar to or like pg_backrest.

**Comment by gsmol** [comment]
Currently work on remote backup is going in remote_ssh branch.
Feel free to join in development or testing.

**Comment by gsmol** [comment]
Currently actual remote branch is remote_pull.

**Comment by gsmol** [comment]
c440ab0f45b8ad801eba65360990401bc43521f6
Merged to master.
Will be delievered with next release.

**Comment by gsmol** [comment]
@internetuser2008, remote capabilities are available in 2.1.1 release.
packages are also available in repository.
