### ISSUE TITLE
Status MERGING.

### ISSUE THREAD

**Issue by Guzya** [postgrespro/pg_probackup#250]
Здравствуйте!
По не понятным причинам не сливаются бэкапы.
Уже несколько раз проделывал цикл с удалением всех бэкапов, созданием FULL и далее DELTA.

![image](https://user-images.githubusercontent.com/22929301/90853896-1e31f480-e384-11ea-80cc-f6745434ecf9.png)
[pg-11-main_2020-08-21.log](https://github.com/postgrespro/pg_probackup/files/5106863/pg-11-main_2020-08-21.log)

**Comment by gsmol** [comment]
Кажется, понял.
Сейчас исправим.

**Comment by gsmol** [comment]
Да, это баг.
Временный воркараунд - запускать удаление по ретеншену отдельно через команду `delete`, а не вместе с бэкапом.

**Comment by gsmol** [comment]
И да, бэкапы, зависшие в статусе MERGING, можно смержить заново, т.к. merge реентрабельный.

**Comment by gsmol** [comment]
Исправил.
Фикс выйдет с релизом 2.4.3.
Большое спасибо за фидбэк!

**Comment by Guzya** [comment]
Вам спасибо!
