### ISSUE TITLE
Не могу добавить инстанс (add-instance).

### ISSUE THREAD

**Issue by Guzya** [postgrespro/pg_probackup#255]
Добрый день!
Имеется сервер Debian 9, postgresql 11 и сервер Ubuntu 14.04 на который хочу лить бэкапы.
Подружил сервера по ssh, учетка postgres ходит без пароля в обе стороны.
На сервере Ubuntu проинициализировал каталог (у postgres все права), и пытаюсь добавить инстанс
pg_probackup-11 add-instance -B /archive/pg_probackup/ --instance 'pg-node-test' --remote-host=<pg-host>  -D /var/lib/postgresql/11/main --log-level-console=VERBOSE

При этом мне выводится:
LOG: Start SSH client process, pid 12336

и все.

На стороне Debian вижу, что pg_probackup agent стартует, на стороне Ubuntu в auth вижу, что прошло подключение с Debian. Но ни чего не происходит.

**Comment by Guzya** [comment]
Добавил в опции ssh -vvv

**Comment by Guzya** [comment]
И после прерывания Ctr-C получаю

LOG: Start SSH client process, pid 18175
^CERROR: Agent error: OpenSSH_6.6.1, OpenSSL 1.0.2l  25 May 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to 172.25.82.91 [172.25.82.91] port 22.
debug1: Connection established.
debug3: Incorrect RSA1 identifier
debug3: Could not load "/var/lib/postgresql/.ssh/id_rsa" as a RSA1 public key
debug1: identity file /var/lib/postgresql/.ssh/id_rsa type 1
debug1: identity file /var/lib/postgresql/.ssh/id_rsa-cert type -1
debug1: identity file /var/lib/postgresql/.ssh/id_dsa type -1
debug1: identity file /var/lib/postgresql/.ssh/id_dsa-cert type -1
debug1: identity file /var/lib/postgresql/.ssh/id_ecdsa type -1
debug1: identity file /var/lib/postgresql/.ssh/id_ecdsa-cert type -1
debug1: identity file /var/lib/postgresql/.ssh/id_ed25519 type -1
debug1: identity file /var/lib/postgresql/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2

**Comment by gsmol** [comment]
Хм, а версии pg_probackup одинаковые на машинах?

**Comment by gsmol** [comment]
Нужно обновить версию 2.4.1 на убунте до 2.4.2

**Comment by gsmol** [comment]
В 2.4.1 был баг:
Previously remote operation process would hang indefinitely, when communicating with agent of lower version. Reported by @alexign
https://github.com/postgrespro/pg_probackup/releases/tag/2.4.2

**Comment by Guzya** [comment]
Я сегодня ставил из репозитория, получается там нет нужной версии.

**Comment by Guzya** [comment]
Вы можете залить в репозиторий  deb [arch=amd64] http://repo.postgrespro.ru/pg_probackup/deb/ trusty main-trusty  последнюю версию.

**Comment by Guzya** [comment]
Видимо механизм раскидывания версий дал сбой
../
bionic/                                            02-Jul-2020 03:40                   -
buster/                                            02-Jul-2020 03:42                   -
focal/                                             02-Jul-2020 03:39                   -
jessie/                                            02-Jul-2020 03:43                   -
stretch/                                           02-Jul-2020 03:42                   -
**trusty/                                            25-Jun-2020 11:07**                   -
xenial/                                            02-Jul-2020 03:38                   -

**Comment by gsmol** [comment]
Действительно, непорядок. Сейчас разберемся

**Comment by gsmol** [comment]
Пакеты в виде файлов:
https://oc.postgrespro.ru/index.php/s/SGQtK53iZDMcx9W

В следующем патч релизе починим репо для ubuntu 14.04.

**Comment by Guzya** [comment]
Спасибо!

**Comment by gsmol** [comment]
Заработало?

**Comment by Guzya** [comment]
Я уже поставил из репы jessie, все работает.

**Comment by gsmol** [comment]
Сурово.

**Comment by gsmol** [comment]
Закрываем?

**Comment by Guzya** [comment]
Да.
