### ISSUE TITLE
Вопрос по частичному восстановлению ---db-include

### ISSUE THREAD

**Issue by zhendosina** [postgrespro/pg_probackup#257]
Привет! Еще раз спасибо за продукт! Он великолепен.
Вопрос по частичному восстановлению, используя --db-include
Пробекап подразумевает полное восстановления кластера постгре, после полного уничтожения директории дата и перезаписи ее из бекапа. Никак не могу понять какой кейс для использования --db-include. Восстановить только одну базу, не затрагивая остальные не получится. Стало быть сценарий, когда нужно откатить одну базу из десяти - это развернуть копию кластера в соседнем месте, там уже снять дамп и перезалить его на основной кластер? 
Спасибо!

**Comment by gsmol** [comment]
Добрый день!
До великолепия нам еще плыть и плыть, но спасибо на добром слове.

> Никак не могу понять какой кейс для использования --db-include. Восстановить только одну базу, не затрагивая остальные не получится. Стало быть сценарий, когда нужно откатить одну базу из десяти - это развернуть копию кластера в соседнем месте, там уже снять дамп и перезалить его на основной кластер?
>
Да, это типовой случай.
Также частичное восстановление может быть полезно, если нужно налить одну базу в dev или stage.

**Comment by zhendosina** [comment]
Очень бы хотелось одну дополнительную фичу если это возможно. 
Сценарий использование probackup не позволяет полностью отказаться от снятия дампов в течение дня.
Было бы очень круто если бы  пробекап мог по волшебной команде развернуть рядом кластер, запустить постгре нf другом портe, снять custom дамп и положить его где - нибудь рядом, чтобы не делать это все руками, когда он нужен. Спасибо еще раз за ваши труды!

**Comment by gsmol** [comment]
А чем это отличается от просто снятия дампа перед бэкапом?
Условно:
```
pg_dump ... && pg_probackup backup ...
```

**Comment by zhendosina** [comment]
> А чем это отличается от просто снятия дампа перед бэкапом?
> Условно:
> 
> ```
> pg_dump ... && pg_probackup backup ...
> ```

Временем работы, двойной нагрузкой на диск, увеличением места для хранения и ненужной нагрузкой на субд.
пробекап раз в 10 быстрее pg_dump)

**Comment by gsmol** [comment]
К сожалению, из pg_probackup невозможно управлять кластером ввиду того, что в разных операционных системах разные 'layout' файлов кластера (centos vs debian), по разному устроены сервисы, управляющие кластерами (не говоря уже о Windows и FreeBSD).
Я бы предложил Вам компромиссный вариант:
1. завести в сторонке кластер, который существует только для снятия дампов
2. периодически синхронизировать его с последний бэкапом с помощью инкрементального восстановления, это должно быть довольно дешевой операцией, и снимать с него дамп.

**Comment by gsmol** [comment]
Можем закрывать тикет?

**Comment by zhendosina** [comment]
> Можем закрывать тикет?

Да, благодарю!
