### ISSUE TITLE
Проблемы при использовании аргументов --log-filename и --log-level-file

### ISSUE THREAD

**Issue by sfalkon** [postgrespro/pg_probackup#26]
Добрый день!

Имеется:
```
$ pg_probackup version
pg_probackup 2.0.16 (PostgreSQL 9.6.1)
```
Выполняю резервное копирование:
```
pg_probackup backup -B /u01/pgdata/backups --instance pgsql-stage-01 -b FULL
```
Время выполнения:
```
real    2m31.654s
user    1m40.221s
sys     0m27.101s
```
Результат выполнения.
http://pastebin.ru/G4EN8hWF/d/

Если выполнить резервное копирование так:
```
pg_probackup backup -B /u01/pgdata/backups --instance pgsql-stage-01 --log-filename=/tmp/report.txt --log-level-file=verbose -b FULL
```
Непроисходит ничего, совсем ничего.
Файл /tmp/report.txt, не создается, подключения к экземпляру не происходит.
Работу pg_probackup, становится невозможно прервать ^С, только через kill -9

**Comment by gsmol** [comment]
Спасибо за баг-репорт!
В ближайшее время починим.
Для справки: опция --log-filename задает только имя файла, путь до директории с лог-файлами задается опцией --log-directory.
Т.е. в вашем случае корректным будем использовать следующий набор опций:
```
pg_probackup backup -B /u01/pgdata/backups --instance pgsql-stage-01 --log-filename=/tmp/report.txt --log-level-file=verbose -b FULL

**Comment by za-arthur** [comment]
Добрый день. Спасибо за тикет!
Ошибку исправил.

**Comment by gsmol** [comment]
Исправлено в релизе 2.0.17

**Comment by gsmol** [comment]
Обновил пакеты на 2.0.17
