### ISSUE TITLE
REPO gives 404 for RHEL path

### ISSUE THREAD

**Issue by beremour** [postgrespro/pg_probackup#262]
Just a question:
```
sudo yum check-update
```
gives:
```
https://repo.postgrespro.ru/pg_probackup/rpm/latest/rhel-7Server-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://repo.postgrespro.ru/pg_probackup/srpm/latest/rhel-7Server-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```
and
```
https://repo.postgrespro.ru/pg_probackup/rpm/latest/
```
really dosen't contain rhel directory

**Comment by gsmol** [comment]
Ouch, I must have screwed the repo copying.

**Comment by gsmol** [comment]
Done, please, try again to install packages.

**Comment by beremour** [comment]
Thank you very much! It works for RHEL 7. But what if other people has RHEL 8 ?

**Comment by gsmol** [comment]
We are building packages using official docker images and, AFAICT, there is none for rhel8.

**Comment by beremour** [comment]
Now sure if I get it right. I mean that [repository](https://repo.postgrespro.ru/pg_probackup/rpm/latest/) dosent contain rhel 8 paths

**Comment by gsmol** [comment]
Yes, because there is no official docker image for rhel8.
Without official docker image we cannot make packages.

**Comment by beremour** [comment]
I thought repos are created with tools like [this](http://yum.baseurl.org/wiki/RepoCreate.html)

**Comment by gsmol** [comment]
Yes, but binaries for packages should be build using native environment.
The easiest way for this is to use docker image.

**Comment by gsmol** [comment]
Is it ok to close this issue?

**Comment by beremour** [comment]
Thank you
