### ISSUE TITLE
Possible WAL corruption. Error has occured during reading WAL segment

### ISSUE THREAD

**Issue by beremour** [postgrespro/pg_probackup#268]
We are using **pg_receivewal** tool to get wal-files. 3 days ago backup stops with "_Possible WAL corruption. Error has occured during reading WAL segment_" message. Is it possible to understand if wal is really corrupted ?
Some log files attached.

[probackup-page-201017-010202.log](https://github.com/postgrespro/pg_probackup/files/5410320/probackup-page-201017-010202.log)
[pg_receivewal-20201017.log](https://github.com/postgrespro/pg_probackup/files/5410321/pg_receivewal-20201017.log)
```
[root@pgbackup ~]# ls -l /vol/pgsql/wal/main/000000030000108E0000002E
-rw-------. 1 postgres postgres 16777216 Oct 17 00:36 /vol/pgsql/wal/main/000000030000108E0000002E
[root@pgbackup ~]#
```

**Comment by gsmol** [comment]
Hello!
Hm, lets take a closer look at this segment.
Can you run the following command?
```
pg_waldump -b /vol/pgsql/wal/main/000000030000108E0000002E
```

**Comment by beremour** [comment]
Oh, it gives:
```
pg_waldump: fatal: error in WAL record at 108E/2E08EA20: incorrect resource manager data checksum in record at 108E/2E08EA60
```
log is here:
[000000030000108E0000002E.log](https://github.com/postgrespro/pg_probackup/files/5415931/000000030000108E0000002E.log)

**Comment by gsmol** [comment]
WAL is definitely corrupted, but it`s hard to guess the cause for this.
The simplest explanation is a hardware failure, so you should check your hardware (dmesg -T, smart, etc).

**Comment by beremour** [comment]
ZFS with compression is underlying filesystem. What is your opinion: better use compress feature of probackup or use filesystems such as ZFS ?

**Comment by gsmol** [comment]
It there some sort of RAIDZ underneath? If so, then maybe the problem will go away if we run scrubbing?
Can you, please, run the following command:
```
zpool status -v pool_name
```
> ZFS with compression is underlying filesystem. What is your opinion: better use compress feature of probackup or use filesystems such as ZFS ?
>
That is a tough one, lets try to deal with the corruption issue first.

**Comment by beremour** [comment]
It is:
```
[root@pgbackup ~]# zpool status -v vol
  pool: vol
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	vol         ONLINE       0     0     0
	  sdb       ONLINE       0     0     0

errors: No known data errors
[root@pgbackup ~]#
```

**Comment by beremour** [comment]
```
[root@pgbackup ~]# zdb
vol:
    version: 5000
    name: 'vol'
    state: 0
    txg: 451428
    pool_guid: 13219219487336279616
    errata: 0
    hostname: 'pgbackup'
    com.delphix:has_per_vdev_zaps
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 13219219487336279616
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 16461979557565581033
            path: '/dev/sdb1'
            whole_disk: 1
            metaslab_array: 128
            metaslab_shift: 36
            ashift: 9
            asize: 10995101073408
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_leaf: 65
            com.delphix:vdev_zap_top: 66
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
[root@pgbackup ~]# df -h /vol
Filesystem      Size  Used Avail Use% Mounted on
vol             9.7T  532G  9.2T   6% /vol
[root@pgbackup ~]# uptime
 00:26:51 up 33 days,  7:12,  1 user,  load average: 0.00, 0.05, 0.10
[root@pgbackup ~]#
```

**Comment by gsmol** [comment]
Then, I think, we can rule out the disk corruption.
The other usual suspects are: memory corruption, kernel bug, PostgreSQL bug.
Are you using ECC memory?

**Comment by beremour** [comment]
Hello again)
I've asked our VMware attendants and they said: YES it is ECC memory on vmware hosts and NO there were no errors or VM migrations at specified time (when corrupted WAL was created)

**Comment by beremour** [comment]
Hm... please look /var/log/messages at near moment from standby server witch is the source for pg_receivewal
```
Oct 17 01:01:13 pgbase02 snmpd[8863]: Connection from UDP: [10.164.3.59]:54382->[10.164.3.172]:161
Oct 17 01:02:03 pgbase02 systemd: Created slice User Slice of postgres.
Oct 17 01:02:03 pgbase02 systemd-logind: New session 24373 of user postgres.
Oct 17 01:02:03 pgbase02 systemd: Started Session 24373 of user postgres.
Oct 17 01:02:03 pgbase02 systemd-logind: Removed session 24373.
Oct 17 01:02:03 pgbase02 systemd: Removed slice User Slice of postgres.
Oct 17 01:02:10 pgbase02 snmpd[8863]: Connection from UDP: [10.164.3.59]:33462->[10.164.3.172]:161
```

**Comment by gsmol** [comment]
Hm, according to [this](https://access.redhat.com/solutions/1564823), there is nothing wrong with.
Someone logged in as  'user' postgres.

>I've asked our VMware attendants and they said: YES it is ECC memory on vmware hosts and NO there were no errors or VM migrations at specified time (when corrupted WAL was created)
>
Then, I think, it is time for me to ask the council of the wise.

**Comment by beremour** [comment]
Then I will freeze backup server for a while to save current state.

**Comment by gsmol** [comment]
Hello!
Is it possible to for you to give us the corrupted WAL segment for forensic purposes ?

**Comment by beremour** [comment]
Oh, sorry for delay and Yes, please look at the WAL (zip compressed):
[000000030000108E0000002E.zip](https://github.com/postgrespro/pg_probackup/files/5493417/000000030000108E0000002E.zip)

**Comment by gsmol** [comment]
What PG version are you using?

**Comment by beremour** [comment]
All 3 servers (master, replica and backup) has:
```
postgresql12.x86_64    12.4-1PGDG.rhel7
```

**Comment by mizhka** [comment]
Hi @beremour ,

WAL headers looks good. The rest is backup of page. To identify corruption, can you please provide page from heap files?

The command `dd skip=97767 bs=8192 count=1 if=63270.2 of=page_master_359911` will exact page under question from file 63270.2 to file "page_master_359911". The file 63270.2 can be found under directory 33570 in tablespace 33562.

Thanks!

**Comment by beremour** [comment]
Sorry, file cannot be found
Master:
```
-bash-4.2$ find /vol1 -name "63270.2"
-bash-4.2$ find /vol2 -name "63270.2"
```
Replica:
```
-bash-4.2$ find /vol1 -name "63270.2"
-bash-4.2$ find /vol2 -name "63270.2"
```
vol1 - default tablespace, vol2 - additional tablespace

**Comment by beremour** [comment]
It, seems vacuum removed it

**Comment by mizhka** [comment]
Any chance to check backups?

**Comment by mizhka** [comment]
@beremour , is there any other case of WAL corruption?

**Comment by gsmol** [comment]
Closed due to not receiving the additional info
