### ISSUE TITLE
ERROR: WAL segment ... could not be streamed in 300 seconds (FULL Backup on Master)

### ISSUE THREAD

**Issue by makeconfig2017** [postgrespro/pg_probackup#275]
Здравствуйте,

Сегодня при создании полной копии на мастер-сервере в режиме STREAM бэкап завершился с ошибкой:
`ERROR: WAL segment 0000000100026C4E0000001C could not be streamed in 300 seconds`

Бэкап запускался на мастер-сервере в режиме STREAM командой:
`pg_probackup backup -j 12 --compress -U bckpusr -B /PROBACKUP --instance INST1 -b FULL --stream --temp-slot`

На котором настроено непрерывное архивирование WAL на слейв-сервер:
`wal_level = replica`
`archive_mode = on`
`archive_command = 'rsync -aq %p PGUSR@1.1.1.1:/ARCHIVE/%f'`

[Вот тут](https://github.com/postgrespro/pg_probackup/issues/47) описана эта ошибка, но при бэкапе на слейв-сервере (реплике) и коментарий:
`As you are using archiving, you don't need to use --stream option.`

Если возможно, ответьте пожалуйста, получится ли полное восстановление (без потери данных), если бэкап сделан на мастер-сервере в режиме ARCHIVE (без режима --stream), в случае отказа всего кластера (и мастера и слейва) ?

**Comment by gsmol** [comment]
Добрый день.
> ERROR: WAL segment 0000000100026C4E0000001C could not be streamed in 300 seconds
>
Можете прислать полный лог выполнения бэкапа и его метаданные (pg_probackup show -i айдюк)?

Я правильно понимаю, что:
1. бэкапы хранятся на мастере локально
2. Архивирование идет с мастера на реплику
?

**Comment by makeconfig2017** [comment]
Да, бэкапы делаются на месте и хранятся локально. Архивирование идет с мастера на реплику.
К сожалению полный лог прислать не могу, расширенное логирование не было включено, вот все что есть:
`INFO: Backup start, pg_probackup version: 2.4.4, instance: INST1, backup ID: QJ6W9N, backup mode: FULL, wal mode:`
`STREAM, remote: false, compress-algorithm: zlib, compress-level: 1`
`WARNING: This PostgreSQL instance was initialized without data block checksums. pg_probackup have no way to detect data block corruption without them. Reinitialize PGDATA with option '--data-checksums'.`
`INFO: PGDATA size: 2870GB`
`INFO: Start transferring data files`
`INFO: Data files are transferred, time elapsed: 1h:22m`
`INFO: wait for pg_stop_backup()`
`INFO: pg_stop backup() successfully executed`
`INFO: Wait for LSN 26C4E/1C48AD00 in streamed WAL segment /PROBACKUP/backups/INST1/QJ6W9N/database/pg_wal/0000000100026C4E0000001C`
`ERROR: WAL segment 0000000100026C4E0000001C could not be streamed in 300 seconds`
`WARNING: Backup QJ6W9N is running, setting its status to ERROR`

pg_probackup show:
`BACKUP INSTANCE 'INST1'`
`================================================================================================`
 `Instance  Version  ID      Recovery Time  Mode  WAL Mode  TLI    Time   Data  WAL  Zratio  Start LSN       Stop LSN  Status `
`================================================================================================`
` INST1   10       QJ6W9N  ----           FULL  STREAM    1/0  1h:27m  853GB    0    3.36  26C46/1E009360  0/0       ERROR  `

**Comment by gsmol** [comment]
По первоначальной проблеме, скорее всего Вам поможет этот фикс в грядущей версии 2.4.5 - https://github.com/postgrespro/pg_probackup/commit/59251c3d041cdc470b08ed7a7e163031bbf70fed

> Если возможно, ответьте пожалуйста, получится ли полное восстановление (без потери данных), если бэкап сделан на мастер-сервере в режиме ARCHIVE (без режима --stream), в случае отказа всего кластера (и мастера и слейва) ?
>
Для того, чтобы полагаться на архив **при снятии** бэкапов, архив должен располагаться с том же хосте, на котором запускается бэкап. Поэтому вашем случае снятие бэкапа просто зафейлится.

Я бы предложил Вам пересмотреть вашу схему резервного копирования, т.к. у нее есть объективные недостатки:
1. Смерть машины с мастером заберет с собой и бэкапы
2. Архив и бэкапы не знают ничего друг о друге, из-за чего процесс резервного копирования в целом выглядит неэффективно

Есть ли возможность перенести бэкапы на другую машину?

**Comment by makeconfig2017** [comment]
> Архив должен располагаться на том же хосте, на котором запускается бэкап

Не уверен, но возможно получится, в настоящий момент упираемся в дисковое пространство

> Архив и бэкапы не знают ничего друг о друге, из-за чего процесс резервного копирования в целом выглядит неэффективно

Не подскажете в какую сторону нужно смотреть, возможно нужно как-то совместить архивирование на реплику текущими средствами (через rsync) с архивированием средствами pg_probackup как описано [здесь](https://postgrespro.ru/docs/enterprise/12/app-pgprobackup#PBK-SETTING-UP-CONTINUOUS-WAL-ARCHIVING)

**Comment by gsmol** [comment]
> Не уверен, но возможно получится, в настоящий момент упираемся в дисковое пространство
>
А не думали перенести бэкапы на реплику?

> Не подскажете в какую сторону нужно смотреть, возможно нужно как-то совместить архивирование на реплику текущими средствами (через rsync) с архивированием средствами pg_probackup как описано здесь
>
Архивируете на реплику из-за нехватки места на мастере?

**Comment by makeconfig2017** [comment]
> А не думали перенести бэкапы на реплику?

Думали, но удаленно с реплики в режиме STREAM снимать не вышло, шли WARNING'и:
`WARNING: Could not read WAL record at 3034/2E4F8350: invalid record length at 3034/2E4F8350: wanted 24, got 0`
`INFO: Wait for LSN 3034/2E4F8350 in streamed WAL segment`
`/PROBACKUP/backups/INST1/QIWTKU/database/pg_wal/00000004000030340000002E`
`WARNING: Could not read WAL record at 3034/2E4F8350: invalid record length at 3034/2E4F8350: wanted 24, got 0`

> Архивируете на реплику из-за нехватки места на мастере?

Архивируем на реплику для создания стендбая, в случае отказа активируется реплика (правда вручную)

> Скорее всего Вам поможет этот фикс в грядущей версии 2.4.5 - 59251c3

Не собралось с postgresql-9.6.19:
`gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fPIC -m64 -DFRONTEND -I. -I./ -I/PGBIN/pgsql-9.6/include/server -I/PGBIN/pgsql-9.6/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/PGBIN/pgsql-9.6/include -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc -I/PGSRC/postgresql-9.6.19//src  -c -o src/backup.o src/backup.c`
`src/backup.c: In function ‘StreamLog’:`
`src/backup.c:2518:6: error: ‘StreamCtl’ has no member named ‘do_sync’`
`   ctl.do_sync = false; /* We sync all files at the end of backup */`
`      ^`
`make: *** [src/backup.o] Error 1`

**Comment by gsmol** [comment]
> Думали, но удаленно (локально не можем из-за нехватки дискового пространства) с реплики снимать в режиме STREAM не вышло, шли WARNING'и:
WARNING: Could not read WAL record at 3034/2E4F8350: invalid record length at 3034/2E4F8350: wanted 24, got 0
INFO: Wait for LSN 3034/2E4F8350 in streamed WAL segment
/PROBACKUP/backups/INST1/QIWTKU/database/pg_wal/00000004000030340000002E
WARNING: Could not read WAL record at 3034/2E4F8350: invalid record length at 3034/2E4F8350: wanted 24, got 0
>
Ну так это нормально для бэкапа с холодной реплики, нужно настроить `archive_timeout` на мастере. Давайте вернемся к этому варианту.

> Архивируем на реплику для создания стендбая, в случае отказа активируется реплика (правда вручную)
>
А что такое стендбай в вашем случае и чем он отличается от реплики?

> Не собралось с postgresql-9.6.19:
>
Попробуйте https://github.com/postgrespro/pg_probackup/commit/a5feea243554f8765d394666f9c76c8e8981a551

**Comment by makeconfig2017** [comment]
> Нужно настроить archive_timeout на мастере

В документации пишут, устанавливать этот таймаут не больше минуты. Не получится так что начнет забиваться архив или WAL (на мастере или на реплике) при большой активности например ?

> А что такое стендбай в вашем случае и чем он отличается от реплики?

Просто называю стендбаем, по-сути реплика

> Попробуйте a5feea2

Спасибо, собралось, правда postgresql-9.5.23 с предыдущей версией собрался без ошибок

**Comment by gsmol** [comment]
> В документации пишут устанавливать этот таймаут не больше минуты. Не получится так, что начнет забиваться архив или WAL (на мастере или на реплике), при большой активности например ? (возможно тут ошибаюсь)
>
При большой активности как раз отрицательных последствий от этого параметра нет. Я бы рекомендовал поставить `4min`,  что даст pg_probackup с его `archive_timeout` в `5min` необходимый запас времени.

> Для всех случаев не подойдет, но в идеале конечно хотелось бы видеть именно такой вариант (это было бы просто прекрасно)
>
Что останавливает?

> Просто называю стендбаем, по-сути реплика, которую можно поднять в режиме мастера в случае проблем с оным.
>
Почему нельзя просто запромоутить  уже имеющуюся реплику в случае падения мастера?

**Comment by gsmol** [comment]
Закрываем задачку?

**Comment by makeconfig2017** [comment]
Добрый день, при попытке бэкапа pg_probackup'ом скопилированным с патчем, выело все возможное место на диске и так и не забэкапилось.

**Comment by gsmol** [comment]
> Добрый день, при попытке локального бэкапа pg_probackup'ом скопилированным с патчем, выело все возможное место на диске и так и не забэкапилось.
>
Ну это одна из причина, почему бэкапить базу локально - плохая идея.

> Да, так и делаем, промоутим реплику в случае падения мастера.
>
Тогда непонятно, в чем у Вас заключается отличие стендбая от реплики.

**Comment by makeconfig2017** [comment]
> Тогда непонятно, в чем у Вас заключается отличие стендбая от реплики.

Да, Вы правы, это реплика, по незнанию думал, что это одно и то же.

> Ну это одна из причина, почему бэкапить базу локально - плохая идея.

Согласен полностью.

**Comment by gsmol** [comment]
Фикс помог? Стриминг начал успевать?

**Comment by makeconfig2017** [comment]
> Фикс помог? Стриминг начал успевать?

А он должен был помочь при удаленном бэкапе тоже ? Думал он для локального ... Проверю бэкап с реплики с этим фиксом, если он конечно не выест все место, как при локальном бэкапе.

**Comment by gsmol** [comment]
> А он должен был помочь при удаленном бэкапе тоже ? 
>
Конечно.

**Comment by makeconfig2017** [comment]
При удаленном бэкапе с реплики пропатченным pg_proback'ом 2.4.4 (PostgreSQL 12.4) выдает вот такие сообщения:
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`INFO: Wait for LSN 2EF9/7FCB9020 in streamed WAL segment /PROBACKUP/backups/INST1/QKFC8V/database/pg_wal/0000000400002EF90000007F`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
archive_timeout выстален в 4 мин как вы советовали:
` archive_timeout `
`-----------------`
` 4min`
`(1 row)`
бэкап после проверки валидный, но все же, возможно, вдруг какие-то данные были утеряны ?

**Comment by gsmol** [comment]
Это бэкап с реплики?
А полный лог можете показать?

**Comment by makeconfig2017** [comment]
> Это бэкап с реплики?

Да
> А полный лог можете показать?

К сожалению расширенного логирования не было, вот все что есть:
`INFO: Backup start, pg_probackup version: 2.4.4, instance: INST1, backup ID: QKFC8V, backup mode: FULL, wal mode: STREAM, remote: true, compress-algorithm: zlib, compress-level: 1
WARNING: This PostgreSQL instance was initialized without data block checksums. pg_probackup have no way to detect data block corruption without them. Reinitialize PGDATA with option '--data-checksums'.`
`INFO: Backup QKFC8V is going to be taken from standby`
`INFO: PGDATA size: 2134GB`
`INFO: Start transferring data files`
`INFO: Data files are transferred, time elapsed: 1h:40m`
`INFO: wait for pg_stop_backup()`
`INFO: pg_stop backup() successfully executed`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`INFO: Wait for LSN 2EF9/7FCB9020 in streamed WAL segment /PROBACKUP/backups/INST1/QKFC8V/database/pg_wal/0000000400002EF90000007F`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`WARNING: Could not read WAL record at 2EF9/7FCB9020: invalid record length at 2EF9/7FCB9020: wanted 24, got 0`
`INFO: Syncing backup files to disk`
`INFO: Backup files are synced, time elapsed: 1s`
`INFO: Validating backup QKFC8V`
`INFO: Backup QKFC8V data files are valid`
`INFO: Backup QKFC8V resident size: 672GB`
`INFO: Backup QKFC8V completed`

**Comment by gsmol** [comment]
> Да
>
Для бэкапа с реплики это нормально. Просто постгрес возвращает lsn записи, которой еще нет.
Пробэкап пытается некоторое время ее подождать, отсюда и эти варнинги.
Надо будет подумать над тем, чтобы спрятать эти сообщения куда-нибудь.

В любом случае, если бы что-то пошло не так, то validate, который автоматически запускается после успешного бэкапа, отрапортовал бы об этом и перевел бэкап в CORRUPT.

**Comment by makeconfig2017** [comment]
> Надо будет подумать над тем, чтобы спрятать эти сообщения куда-нибудь.

Спасибо, ждем с нетерпением, т.к. настроен мониторинг WARNING'ов и ERROR'ов

**Comment by makeconfig2017** [comment]
Сегодня снова появилась первоначальный WARNING 'WAL segment 0000000400002FF4000000E3 could not be streamed in 300 seconds':
`INFO: Backup start, pg_probackup version: 2.4.4, instance: SCS_UN, backup ID: QKKW8V, backup mode: DELTA, wal mode: STREAM, remote: true, compress-algorithm: zlib, compress-level: 1`
`WARNING: This PostgreSQL instance was initialized without data block checksums. pg_probackup have no way to detect data block corruption without them. Reinitialize PGDATA with option '--data-checksums'.`
`INFO: Backup QKKW8V is going to be taken from standby`
`INFO: Parent backup: QKJ1KV`
`INFO: PGDATA size: 2326GB`
`INFO: Start transferring data files`
`INFO: Data files are transferred, time elapsed: 21m:6s`
`INFO: wait for pg_stop_backup()`
`INFO: pg_stop backup() successfully executed`
`INFO: Wait for WAL segment /PROBACKUP/backups/INST1/QKKW8V/database/pg_wal/0000000400002FF4000000E3 to be streamed`
`WARNING: WAL segment 0000000400002FF4000000E3 could not be streamed in 300 seconds`
`WARNING: Failed to get next WAL record after 2FF4/E3000000, looking for previous WAL record`
`INFO: Syncing backup files to disk`
`INFO: Backup files are synced, time elapsed: 0`
`INFO: Validating backup QKKW8V`
`INFO: Backup QKKW8V data files are valid`
`INFO: Backup QKKW8V resident size: 8072MB`
`INFO: Backup QKKW8V completed`
Бэкап делался с реплики, версией с патчем:
`$ pg_probackup -V`
`pg_probackup 2.4.4 (PostgreSQL 12.4)`
archive_timeout настроен 4 мин:
`postgres=# show archive_timeout;`
` archive_timeout `
`-----------------`
` 4min`
`(1 row)`

**Comment by gsmol** [comment]
Если ERROR нет, то все хорошо.

**Comment by makeconfig2017** [comment]
Возможно не по теме трэда, параллельно борюсь с ошибками на NFS, не удаляются старые бэкапы, после pg_probackup'а остаются файлы .nfs0000, которые невозможно удалить:
`INFO: Resident data size to free by delete of backup QKH6WP : 195GB`
`INFO: Delete: QKH6WP 2020-11-28 00:35:35+02`
`ERROR: Cannot remove file "/PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.nfs000000000000472100000001": Device or resource busy`
возможно сталкивались с подобными ошибками, не понимаю даже куда смотреть, процессов которые блокируют удаление не нахожу, вывод lsof и fuser пустой

**Comment by gsmol** [comment]
```
lsof /PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.nfs000000000000472100000001
```
Ничего не возвращает?

**Comment by makeconfig2017** [comment]
Абсолютно:
`$ lsof /PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.nfs000000000000472100000001`
`$ `
пусто

**Comment by makeconfig2017** [comment]
Заполнил [BUG](https://bugzilla.linux-nfs.org/show_bug.cgi?id=352) на [OpenNET](https://www.opennet.ru/openforum/vsluhforumID1/97668.html) тоже пока не ответили.

**Comment by gsmol** [comment]
а опции монтирования можете прислать?

**Comment by makeconfig2017** [comment]
`1.1.1.1:/PROBACKUP on /PROBACKUP type nfs4
(rw,relatime,vers=4.1,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=2.2.2.2,local_lock=none,addr=1.1.1.1`

**Comment by gsmol** [comment]
Что возвращает `stat /PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.nfs000000000000472100000001` ?

**Comment by makeconfig2017** [comment]
`$ stat /PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.nfs000000000000472100000001`
`  File: /PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.nfs000000000000472100000001`
`  Size: 16777216        Blocks: 32816      IO Block: 65536  regular file`
`Device: 32h/50d Inode: 18209       Links: 1`
`Access: (0600/-rw-------)  Uid  (10114/   user)   Gid: (10114/   user)`
`Access: 2020-11-30 14:03:20.641030000 +0200`
`Modify: 2020-11-28 00:27:02.075223000 +0200`
`Change: 2020-11-29 00:49:21.070838000 +0200`
 `Birth: -`

**Comment by gsmol** [comment]
Повторная попытка удаления все еще фейлится?

**Comment by makeconfig2017** [comment]
Да:
`$ rm /PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.nfs000000000000472100000001`
`rm: cannot remove '/PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.nfs000000000000472100000001': Device or resource busy`
`$ rm /PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.nfs000000000000472100000001`
`rm: cannot remove '/PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.nfs000000000000472100000001': Device or resource busy`

**Comment by gsmol** [comment]
А на сервере нет каких-то ошибок в логе?

**Comment by makeconfig2017** [comment]
> А на сервере нет каких-то ошибок в логе?

Касающихся NFS или pg_probackup'а нет.

**Comment by gsmol** [comment]
А новые файлы создаются без проблем?
Создание/удаление файла сейчас работает?

**Comment by makeconfig2017** [comment]
> Создание/удаление файла сейчас работает?

По тому же пути и создаются и удаляются:
`$ touch /PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.test_file`
`$ ls -la /PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.test_file`
`-rw-rw-r-- 1 user user 0 Dec  2 11:51 /PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.test_file`
`$ rm /PROBACKUP/backups/INST1/QKH6WP/database/pg_wal/.test_file`
`$`

**Comment by gsmol** [comment]
> Всем спасибо за ответы, помогло обновление ядра до 5.9.12-1.el8.elrepo.x86_64
>
Я так понимаю, проблему решили и тикет можно закрывать?

**Comment by makeconfig2017** [comment]
> > Всем спасибо за ответы, помогло обновление ядра до 5.9.12-1.el8.elrepo.x86_64
> 
> Я так понимаю, проблему решили и тикет можно закрывать?

К сожалению проблема не решилась, время от времени при бэкапе с реплики выдаёт:
`ERROR: WAL segment 0000000400019327000000B7 could not be streamed in 300 seconds`
на реплике настроено:
`archive_timeout = 300`
по мониторингу связь с сервером не пропадала, БД не падала

**Comment by gsmol** [comment]
Добрый день!
Ошибка всё еще сохраняется?

**Comment by makeconfig2017** [comment]
> Добрый день! Ошибка всё еще сохраняется?

Добрый день, к сожалению да, бэкап делается с мастера, на котором настроено:
`postgres=# show archive_timeout;`
` archive_timeout `
`-----------------`
` 5min`
`(1 row)`
Сегодня ночью бэкап вылетел с ошибкой:
`ERROR: WAL segment 00000001000065910000008C could not be streamed in 300 seconds`
версия pg_probackup - 2.4.17

**Comment by makeconfig2017** [comment]
Добрый день, изменение параметра:
`--archive-timeout=1h`
не помогло, сегодня получили ошибку:
`ERROR: WAL segment 00000001000068A5000000A2 could not be streamed in 3600 seconds`
связь с сервером не пропадает

**Comment by makeconfig2017** [comment]
Здравствуйте, переход на бэкап с реплики решил все проблемы, огромное спасибо за помощь, тему можно закрывать.
