### ISSUE TITLE
ERROR: Calculated CRC checksum does not match value stored in file

### ISSUE THREAD

**Issue by edib** [postgrespro/pg_probackup#28]
I have tried in debian 9 with postgres pro standard. when creating initing a backup the above error occurs.

**Comment by edib** [comment]
I just installed via pg_pro packages. What I am tryting to do is to use the ptrack backup property. In this case should I use the compiled versions of postgres vanilla with ptrack and pg_probackup both?

**Comment by gsmol** [comment]
If you want to use ptrack, then there are several options:
1. Install Postgres Pro Standart binaries, which has build-in ptrack support. And either use pg_probackup from Postgres Pro Standart distribution, or manually compile pg_probackup using Postgres Pro Standart sources.
2. Manually compile postgres binaries using vanilla source and ptrack patches. In this case you can use pg_probackup binary from [pg_probackup repo](https://github.com/postgrespro/pg_probackup#linux-installation).
3. Same as p.2, except that you can also compile pg_probackup using vanilla sources.

**Comment by edib** [comment]
Ok, first option, installing from "Postgres Pro Standart distribution" works fine. I can backup the cluster right now. Now I am trying to understand the terms and concept. 
Thanks.
