### ISSUE TITLE
2.4.7: munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by deric** [postgrespro/pg_probackup#284]
After upgrading to `2.4.7` release
```
INFO: Backup start, pg_probackup version: 2.4.7, instance: db01, backup ID: QL1ITD, backup mode: FULL, wal mode: STREAM, remote: true, compress-algorithm: none, compress-level: 1
munmap_chunk(): invalid pointer
Aborted
```

**Comment by deric** [comment]
The very same problem with `2.4.6` release. `2.4.4-1.95a3fbaa1128f285.buster` works fine.

**Comment by gsmol** [comment]
Hello!
That is no good, can you check if there a core dump left by any chance? You have to run `dmesg -T` command.
Thank you for a feedback.

**Comment by gsmol** [comment]
Can you please provide the whole  cmdline of `backup` command you were running ?

**Comment by gsmol** [comment]
I`ve managed to reproduce the issue. It is a bug in timezone handling introduced by #272
The quick fix is to unset enviromental variable `TZ` before running backup.

**Comment by gsmol** [comment]
Fix will be released today in 2.4.8 version

**Comment by deric** [comment]
Thanks for quick fix :+1:

**Comment by gsmol** [comment]
2.4.8 released
