### ISSUE TITLE
restore и автостарт службы

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/pg_probackup#29]
Сейчас 
```
Когда команда restore завершит работу, запустить службу баз данных.
Postgres Pro восстановит согласованное состояние, воспроизведя файлы WAL
и будет готов принимать подключения.
```
это поведение не всегда хорошо, так как мне к примеру после восстановления нужно подменить файлы конфигурации (*.conf) и только потом стартовать.
Прошу добавить опцию подавляющую автостарт службы.
Дело в том, что я беру бэкап с другого сервера(prod) и восстанавливаю его на тестовом, а там совсем другие настройки. 
Нельзя применять настройки кластера с prod.

Кстати опечатка в доках `запустить`, (не согласован текст) поправьте как сможете.

**Comment by gsmol** [comment]
Спасибо за фидбэк!
restore не запускает postgres, а только копирует файлы из бэкапа, соответственно, после restore пользователь может изменить восстановленные файлы как посчитает нужным.

**Comment by za-arthur** [comment]
Спасибо!
> Кстати опечатка в доках запустить, (не согласован текст) поправьте как сможете.

Сообщил нашему писателю.
