### ISSUE TITLE
Как найти описание [параметры_журнала]?

### ISSUE THREAD

**Issue by shab2** [postgrespro/pg_probackup#296]
Добрый день!

В описании https://postgrespro.ru/docs/postgrespro/13/app-pgprobackup
в разделе
pg_probackup backup -B каталог_копий -b режим_копирования --instance имя_экземпляра
[--help] [-j число_потоков] [--progress]
[-C] [--stream [-S slot_name] [--temp-slot]] [--backup-pg-log]
[--no-validate] [--skip-block-validation]
[-w --no-password] [-W --password]
[--archive-timeout=тайм-аут] [--external-dirs=external_directory_path]
[--no-sync] [--note=заметка_к_копии]
[параметры_соединения] [параметры_сжатия] [параметры_удалённого_режима]
[параметры_хранения] [параметры_закрепления] **[параметры_журнала]**

Не смог найти описания на [параметры_журнала]
Можете дать ссылку?

Спасибо

**Comment by gsmol** [comment]
Добрый день.
Похоже на ошибку в наименовании, поправим.
https://postgrespro.ru/docs/postgrespro/13/app-pgprobackup#PBK-LOGGING-OPTS

Если что, есть другая документация на английском, в которой есть индекс:
https://postgrespro.github.io/pg_probackup/

**Comment by shab2** [comment]
Спасибо
