### ISSUE TITLE
Удаление wal-логов с учетом процесса наката на реплики

### ISSUE THREAD

**Issue by shab2** [postgrespro/pg_probackup#298]
День, добрый!

В моей конфигурации используется 2е асинхронных реплики, одна отстающая на 5 дней. 
При бекапировании делаю --delete-expired без --delete-wal
Логи планирую удалять на праймари только те, которые уже не нужны ни одной реплике, для этого беру (select min(flush_lsn) from pg_stat_replication) как значение границы. Перестраховка на случай, когда реплика долго
простаивала и не качала логи.
Теперь встает вопрос как удалять логи? Писать свой скрипт или спросить Вашего мнения на счет такого варианта:

  Ввести новую опцию для pg_probackup backup|delete, например --wal-depth-lsn= или --delete-wal-lsn=
При удалении логов вычислять границу, ДО которой происходит удаление логов, как наиболее старый LSN из  <вычисленного по политике бекапирования> и <переданное опцией>. 

Что скажете?

**Comment by gsmol** [comment]
Добрый день.
1. Есть опции `--wal-depth`, которая задает глубину хранения WAL в бэкапахю Если Вы снимаете бэкапы раз в день, то достаточно будет установить `--wal-depth=6`.
2. В планах на следующий релиз есть добавление опции `--wal-window`, с помощью которой можно будет указать глубину хранения в виде временного интервала.

**Comment by gsmol** [comment]
Остались ли еще какие-то вопросы/пожелания?

**Comment by shab2** [comment]
Настройки глубины что реплики, что бекапа, что логов защищают остановившуюся реплику от инвалидации запасом времени. Я предпочитаю защищать программной проверкой текущего состояния.
Ну да у каждого свои резоны. Спасибо за отклик

**Comment by gsmol** [comment]
Ваши рассуждения разумны и решаемая проблема понятна, но мне кажется, что Вы избрали для него негодный метод.
Рассмотри следующую картину:
```
                /------------------->      t2
-------B--------*--------X-------------> t1
```
B - бэкап
* - свичпоинт из t1 в t2
X - точка, заданная через `--delete-wal-lsn`

Если на t1 и t2 честно удалим весь WAL до X, то мы сломаем наши гарантии для t2, потому что хотя формально WAL после X останется, в него невозможно будет восстановиться.
Если мы будем принимать во внимание такие вопросы, то это неизбежно поменяет семантику  `--delete-wal-lsn` в сторону уже имеющихся опций. И тогда смысла в ней будет немного.

**Comment by shab2** [comment]
В логике из передаваемого X и вычисляемого вами oldest В я предложил выбирать самое старое для точки удаления, поэтому t2 это никак не затронет.
d может быть вычислена ТОЛЬКО как <=oldest B

                /------------------->      t2
---d---B--------*--------X-------------> t1

if x>= oldest b {
  d = oldest b
else
  d = x
Ну и удалять нужно ДО d

**Comment by gsmol** [comment]
Но тогда Вы не получаете вот это - "Я предпочитаю защищать программной проверкой текущего состояния", ведь получается, что Вы будете полагаться на какую-то пробэкапную blackbox логику. В чем тогда с разница с `--wal-deph` или планируемым `--wal-window`?

**Comment by shab2** [comment]
Думаю, что такая запись в man даст исчерпывающее объяснение:
========
--delete-wal-lsn=X Передаваемое значение LSN позволяет увеличить глубину сохраняемых логов, но удаление не может быть  выполнено для логов входящих в политику бекапрования определяемую в конфиге.
=========

--wal-window, если оно может быть указано в часах и минутах можно будет использовать, но c lsn правильнее.

Спасибо

**Comment by gsmol** [comment]
Стоит, мы очень внимательно относимся с фич-реквестам, а обсуждение не занимает много времени.
Нет, оно особо не усложнит, фича не очень сложная, но Вы просто не получите то, что просите, pbk все равно будет вынужден Вас обманывать.
В `wal-window` можно будет указать временной интервал, типа `5d`, `20h`.
