### ISSUE TITLE
requested WAL segment 0000000100006FF4000000C6 has already been removed

### ISSUE THREAD

**Issue by VladislavePolyakov** [postgrespro/pg_probackup#314]
description:

it was created by crontab once per week.  backup made fro replica.
`/usr/bin/pg_probackup-12 backup -B /mnt/BACKUP-postgres-ssh/ -b FULL --instance=nestle --stream
`

question:

how to guaranty all WAL will accepted after backup?

log from pg_probackup:

```
2021-01-30 05:27:25 MSK [61564]: ERROR: Problem in receivexlog
2021-01-30 05:27:25 MSK [61564]: ERROR: Interrupted during page reading
2021-01-30 05:27:25 MSK [61564]: ERROR: Data files transferring failed, time elapsed: 1d:5h
2021-01-30 05:27:25 MSK [61564]: WARNING: backup in progress, stop backup
```

log from PostgreSQL:

`2021-01-30 02:27:25.249 UTC,"backup","",61728,"[local]",601325e0.f120,1,"streaming 6FF4/C6060000",2021-01-28 21:00:16 UTC,5/0,0,ERROR,XX000,"requested WAL segment 0000000100006FF4000000C6 has already been removed",,,,,,,,,"pg_probackup-12"`

show from pg_probackup:
```
================================================================================================================================================
 Instance  Version  ID      Recovery Time           Mode   WAL Mode  TLI     Time    Data     WAL  Zratio  Start LSN      Stop LSN       Status
================================================================================================================================================
 nestle    12       QNNX01  ----                    FULL   STREAM    1/0    1d:5h  1756GB       0    2.91  6F1E/59443290  0/0            ERROR

```

versions :
```
pg_probackup-12 2.4.8 (PostgreSQL 12.5)
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

```

**Comment by gsmol** [comment]
Hello!
You can use `--temp-slot` option.

**Comment by VladislavePolyakov** [comment]
> Hello!
> You can use `--temp-slot` flag.

**Comment by VladislavePolyakov** [comment]
thanks!
will try to use it
if all ok, on next week will close issue

**Comment by gsmol** [comment]
Glad to help.
