### ISSUE TITLE
can't build pg_probackup-2.4.9 from SOURCE CODE

### ISSUE THREAD

**Issue by hunterhuang8810** [postgrespro/pg_probackup#315]
I downloaded 2.4.9 source code and tried to build on my centos server,but I can't build success
looks like miss some file, please help to check , thanks.

[root@localhost pg_probackup-2.4.9]# pwd
/root/temp/pg_probackup-2.4.9
[root@localhost pg_probackup-2.4.9]# ls
doc  gen_probackup_project.pl  LICENSE  Makefile  README.md  src  tests  travis
[root@localhost pg_probackup-2.4.9]#

[root@localhost pg_probackup-2.4.9]# make USE_PGXS=1 PG_CONFIG=/usr/local/postgresql_12.5/bin/pg_config top_srcdir=/root/temp/pg_probackup-2.4.9
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I./ -I/usr/local/postgresql_12.5/include/server -I/usr/local/postgresql_12.5/include/internal  -D_GNU_SOURCE  -I/usr/local/postgresql_12.5/include -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc -I/root/temp/pg_probackup-2.4.9//src  -c -o src/utils/configuration.o src/utils/configuration.c
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I./ -I/usr/local/postgresql_12.5/include/server -I/usr/local/postgresql_12.5/include/internal  -D_GNU_SOURCE  -I/usr/local/postgresql_12.5/include -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc -I/root/temp/pg_probackup-2.4.9//src  -c -o src/utils/json.o src/utils/json.c
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I./ -I/usr/local/postgresql_12.5/include/server -I/usr/local/postgresql_12.5/include/internal  -D_GNU_SOURCE  -I/usr/local/postgresql_12.5/include -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc -I/root/temp/pg_probackup-2.4.9//src  -c -o src/utils/logger.o src/utils/logger.c
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I./ -I/usr/local/postgresql_12.5/include/server -I/usr/local/postgresql_12.5/include/internal  -D_GNU_SOURCE  -I/usr/local/postgresql_12.5/include -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc -I/root/temp/pg_probackup-2.4.9//src  -c -o src/utils/parray.o src/utils/parray.c
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I./ -I/usr/local/postgresql_12.5/include/server -I/usr/local/postgresql_12.5/include/internal  -D_GNU_SOURCE  -I/usr/local/postgresql_12.5/include -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc -I/root/temp/pg_probackup-2.4.9//src  -c -o src/utils/pgut.o src/utils/pgut.c
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I./ -I/usr/local/postgresql_12.5/include/server -I/usr/local/postgresql_12.5/include/internal  -D_GNU_SOURCE  -I/usr/local/postgresql_12.5/include -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc -I/root/temp/pg_probackup-2.4.9//src  -c -o src/utils/thread.o src/utils/thread.c
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I./ -I/usr/local/postgresql_12.5/include/server -I/usr/local/postgresql_12.5/include/internal  -D_GNU_SOURCE  -I/usr/local/postgresql_12.5/include -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc -I/root/temp/pg_probackup-2.4.9//src  -c -o src/utils/remote.o src/utils/remote.c
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I./ -I/usr/local/postgresql_12.5/include/server -I/usr/local/postgresql_12.5/include/internal  -D_GNU_SOURCE  -I/usr/local/postgresql_12.5/include -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc -I/root/temp/pg_probackup-2.4.9//src  -c -o src/utils/file.o src/utils/file.c
make: *** No rule to make target `/root/temp/pg_probackup-2.4.9/src/include/portability/instr_time.h', needed by `src/instr_time.h'.  Stop.
[root@localhost pg_probackup-2.4.9]#

**Comment by gsmol** [comment]
Hello!
As a quick fix you can use the alternative build procedure:
```
cd <path_to_PostgreSQL_source_tree> && git clone https://github.com/postgrespro/pg_probackup contrib/pg_probackup && cd contrib/pg_probackup && make
```
I will look into this problem.
Thanks for a feedback!

**Comment by gsmol** [comment]
Btw, did you consider to just use the packages for Centos ?
https://github.com/postgrespro/pg_probackup#pg_probackup-for-vanilla-postgresql

**Comment by hunterhuang8810** [comment]
> Hello!
> As a quick fix you can use the alternative build procedure:
> 
> ```
> cd <path_to_PostgreSQL_source_tree> && git clone https://github.com/postgrespro/pg_probackup contrib/pg_probackup && cd contrib/pg_probackup && make
> ```
> 
> I will look into this problem.
> Thanks for a feedback!

**Comment by hunterhuang8810** [comment]
> Btw, did you consider to just use the packages for Centos ?
> https://github.com/postgrespro/pg_probackup#pg_probackup-for-vanilla-postgresql

yes, I can use this Centos  packages first. But I still need to build from source code for those offline circumstances.
thanks a lot for you quick response.
