### ISSUE TITLE
Ошибка при подключении к удаленному хосту pg_probackup-11: symbol lookup error: pg_probackup-11: undefined symbol: PQconninfo

### ISSUE THREAD

**Issue by dreadushka** [postgrespro/pg_probackup#322]
На 5 шаге инструкции https://postgrespro.ru/docs/postgrespro/11/app-pgprobackup#PBK-REMOTE-SERVER-OPTS
pg_probackup-11 backup -B /data/pgbackup/ --instance 'database' -b FULL --stream --remote-host=10.11.22.18 --remote-user=postgres -U backup -d backupdb
Следующая ошибка, гугление не помогает... 
pg_probackup-11: symbol lookup error: pg_probackup-11: undefined symbol: PQconninfo

**Comment by gsmol** [comment]
Добрый день!
Пришлите, пожалуйста, выхлоп команды `ldd $(which wal-g)` и имя и версию пакета pg_probackup

**Comment by dreadushka** [comment]
pg_probackup-11 2.4.9 (PostgreSQL 11.10)

-bash-4.2$ ldd $(which pg_probackup-11)
        linux-vdso.so.1 =>  (0x00007ffc3a2ae000)
        libpq.so.5 => /usr/pgsql-11/lib/libpq.so.5 (0x00007f1c6c673000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1c6c457000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f1c6c241000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f1c6c039000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f1c6bc6c000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f1c6b9fa000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f1c6b599000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f1c6b34c000)
        libldap_r-2.4.so.2 => /lib64/libldap_r-2.4.so.2 (0x00007f1c6b0ed000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1c6c8bc000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f1c6ae04000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f1c6ac00000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f1c6a9e5000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f1c6a7e1000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f1c6a5d2000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f1c6a3ce000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f1c6a1b5000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f1c69fa6000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f1c69d89000)
        libssl3.so => /lib64/libssl3.so (0x00007f1c69b37000)
        libsmime3.so => /lib64/libsmime3.so (0x00007f1c69910000)
        libnss3.so => /lib64/libnss3.so (0x00007f1c695e3000)
        libnssutil3.so => /lib64/libnssutil3.so (0x00007f1c693b4000)
        libplds4.so => /lib64/libplds4.so (0x00007f1c691b0000)
        libplc4.so => /lib64/libplc4.so (0x00007f1c68fab000)
        libnspr4.so => /lib64/libnspr4.so (0x00007f1c68d6d000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f1c68b46000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f1c6890f000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f1c686ad000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f1c684aa000)
        
ldd $(which pg_probackup-11)
        linux-vdso.so.1 =>  (0x00007ffdc1f3a000)
        libpq.so.5 => /lib64/libpq.so.5 (0x00007f91ac599000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f91ac37d000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f91ac167000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f91abf5f000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f91abb91000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f91ab91f000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f91ab4bc000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f91ab1d3000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f91aafcf000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f91aad82000)
        libldap_r-2.4.so.2 => /lib64/libldap_r-2.4.so.2 (0x00007f91aab23000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f91ac7c8000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f91aa8f0000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f91aa6ec000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f91aa4dc000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f91aa2d8000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f91aa0be000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f91a9eaf000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f91a9c92000)
        libssl3.so => /lib64/libssl3.so (0x00007f91a9a35000)
        libsmime3.so => /lib64/libsmime3.so (0x00007f91a980d000)
        libnss3.so => /lib64/libnss3.so (0x00007f91a94d9000)
        libnssutil3.so => /lib64/libnssutil3.so (0x00007f91a92a9000)
        libplds4.so => /lib64/libplds4.so (0x00007f91a90a5000)
        libplc4.so => /lib64/libplc4.so (0x00007f91a8ea0000)
        libnspr4.so => /lib64/libnspr4.so (0x00007f91a8c62000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f91a8a3b000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f91a8804000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f91a85a2000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f91a839f000)

**Comment by gsmol** [comment]
What OS are you using ?

**Comment by dreadushka** [comment]
Red Hat Enterprise Linux Server release 7.6  3.10.0-957.el7.x86_64

**Comment by gsmol** [comment]
nm -D /usr/pgsql-11/lib/libpq.so.5 | grep PQconninfo

**Comment by dreadushka** [comment]
Установил клиент postgresql11, заработало, спасибо. Просто подразумевалось только хранение резервных копий, поэтому клиент и не подумал ставить. Спасибо!

**Comment by gsmol** [comment]
Обращайтесь.
