### ISSUE TITLE
How to remove already backed up archive files?

### ISSUE THREAD

**Issue by gglybin** [postgrespro/pg_probackup#325]
Hello,

I have a number of wal archive files generated by my database instance.

I run pg_probackup in following way:
```
pg_probackup-11 backup --backup-path=${BKP_DIR} --instance=${INSTANCE} --threads ${THREADS} --backup-mode FULL --compress --delete-expired --delete-wal -d backup_db -h *** -p 5432 -U backup_usr -w

pg_probackup-11 backup --backup-path=${BKP_DIR} --instance=${INSTANCE} --threads ${THREADS} --backup-mode DELTA --compress --delete-expired --delete-wal -d backup_db -h *** -p 5432 -U backup_usr -w
```

I expect that all (or some of them) wal archive files will be removed after backup completion to avoid disk space utilization issue, but these files are still there.

Could you please clarify how is this working? When old wal archive files will be removed?

**Comment by gsmol** [comment]
Hello!
By default only those WAL segments, that cannot be applied to any backup, are deleted.
You can change that by setting WAL retention policy via `--wal-depth` option:
https://postgrespro.github.io/pg_probackup/#pbk-wal-archive-retention-policy

**Comment by gsmol** [comment]
Do you have any more questions or we can close the issue?

**Comment by gglybin** [comment]
No more questions, thank you for clarification.
