### ISSUE TITLE
Can I manually restore a full backup taken with pg_probcakup? 

### ISSUE THREAD

**Issue by tengilim** [postgrespro/pg_probackup#334]
Hi;

    Can I manually restore a full backup taken with pg_probcakup? When I manually restore a full backup  I could not enter the db. Is there any way to do this?

**Comment by gsmol** [comment]
Hello!
> Can I manually restore a full backup taken with pg_probcakup?
>
What do you mean by 'manually' exactly ?

**Comment by tengilim** [comment]
let me explain immediately!  I have  taken a  backup with pg_probackup using FULL and stream option. Then I saw that a directory named  "database" in backup location. I have copied this directory  to any other server using scp and  tried to open. Unfortunetely I  have get an error.  This is what I mean by manually.

**Comment by gsmol** [comment]
No, currently backup of any mode must be restored using `pg_probackup restore ...`, because probackup add small header to each page.

**Comment by tengilim** [comment]
Okey. Thank u for your answers. But it could be nice if there was a way.

**Comment by gsmol** [comment]
Yes, currently this header is only required for merge retry, we will think of how to remove it.

**Comment by tengilim** [comment]
I think it would be nice, thanks again
