### ISSUE TITLE
Монтирование PGDATA без atime

### ISSUE THREAD

**Issue by ykurenkov** [postgrespro/pg_probackup#337]
Нет ли каких замечаний на монтирование раздела с PGDATA с опцией noatime? Использует ли pg_probackup atime в PGDATA в работе? Заодно вопрос о необходимости atime в хранилище бэкапов.

**Comment by gsmol** [comment]
Добрый день!
probackup на такие вещи не полагается, и каких-то противопоказаний относительно включения/отключения atime у нас нет.

**Comment by ykurenkov** [comment]
Спасибо.
