### ISSUE TITLE
warning on compile pg_probackup 13 on RHEL8.3

### ISSUE THREAD

**Issue by shab2** [postgrespro/pg_probackup#338]
src/catalog.c: In function ‘lock_backup’:
src/catalog.c:603:9: warning: ‘encoded_pid’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         elog(WARNING, "Cannot to lock backup %s in exclusive mode, because process %u owns shared lock",
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 base36enc(backup->start_time), encoded_pid);
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/catalog.c:536:11: note: ‘encoded_pid’ was declared here
     pid_t encoded_pid;
           ^~~~~~~~~~~

**Comment by gsmol** [comment]
Hello!
Fixed that in https://github.com/postgrespro/pg_probackup/commit/8e930b79abc2f2a0440eb5e1528fe562f2a971c9
