### ISSUE TITLE
backup v2.0.24 - restore v2.4.10 error

### ISSUE THREAD

**Issue by shab2** [postgrespro/pg_probackup#348]
Приветствую!
Бекап сделан на версии pg_probackup 2.0.24 (Postgres Pro 10.6.1 standard)

Скопирован на другую машину с более свежим бекапом и ванильным постресом
pg_probackup 2.4.10 (PostgreSQL 10.6)

Проверен
[CYBERFT]$ pg_probackup validate --instance CYBERFT
INFO: Validate backups of the instance 'CYBERFT'
INFO: Revalidating backup QQ7Z8H
INFO: Backup QQ7Z8H data files are valid
INFO: Backup QQ7Z8H WAL segments are valid
INFO: All backups are valid

На ресторе имеем ошибку
pg_probackup restore --instance CYBERFT
ERROR: Invalid CRC of tablespace map file "/pg/backup/backups/CYBERFT/QQ7Z8H/database/tablespace_map" : 85DE79E3. Expected BF2B0B40, probably backup QQ7Z8H is corrupt, validate it

Указанный файл копировал повторно неоднократно. 
Содержимое
[CYBERFT]$ cat /pg/backup/backups/CYBERFT/QQ7Z8H/database/tablespace_map
16384 /pg/tablespaces/cyberft/ts_cyberft

[CYBERFT]$ ls -lh /pg/tablespaces/cyberft/ts_cyberft
total 0

Подскажите, пожалуйста, в чем может быть причина? Обязательно ли поднимать версию 2.0.24? Влияет ли редакция Постгреса Про - не Про?

**Comment by gsmol** [comment]
Добрый день!
Влияет, нужно использовать бинарь для пгпро. Его можнл взять тут:
https://github.com/postgrespro/pg_probackup#pg_probackup-for-postgrespro-standard-and-enterprise

**Comment by shab2** [comment]
[CYBERFT]$ pg_probackup-std-10 version
pg_probackup-std-10 2.4.10 (Postgres Pro 10.13.1 standard)

[CYBERFT]$ pg_probackup-std-10 restore --instance CYBERFT
ERROR: Invalid CRC of tablespace map file "/pg/backup/backups/CYBERFT/QQ7Z8H/database/tablespace_map" : 85DE79E3. Expected BF2B0B40, probably backup QQ7Z8H is corrupt, validate it

**Comment by gsmol** [comment]
Hm, I'm going to try to reproduce that, 10 min

**Comment by gsmol** [comment]
Нет, обратная совместимость сохранена.
Можете прислать метаданные этого бэкапа?
````
pg_probackup-std-10 show --instance CYBERFT -i QQ7Z8H
```

**Comment by gsmol** [comment]
Стоп, действительно нашел баг.

**Comment by gsmol** [comment]
Готов предоставить Вам пакет с фиксом. Под какую ОС собирать?

**Comment by shab2** [comment]
oel7.  Срочности нет.
--
Отправлено из Mail.ru для Android суббота, 20 марта 2021г., 23:21 +03:00 от gsmol  ***@***.*** :

**Comment by gsmol** [comment]
В аттаче тарник с пакетами.
Штатно фикс выйдет с версией 2.4.12.
[pbk-std-2.4.11.tar.gz](https://github.com/postgrespro/pg_probackup/files/6176524/pbk-std-2.4.11.tar.gz)
