### ISSUE TITLE
Fast restore

### ISSUE THREAD

**Issue by shab2** [postgrespro/pg_probackup#349]
Добрый день!

Иногда требуется восстановиться так быстро как это возможно. План такой: Бекап лежит на том же томе, где и кластер,
при restore указываем НЕ валидировать бекап и делать mv вместо cp. Т.е пользуемся тем, что probackup ЗНАЕТ куда разложить файлы. С точки зрения безопасности считаем, что есть еще одна копия бекапа на другом сервере.

**Comment by gsmol** [comment]
Добрый день.
С трудом представляю себе конфигурацию, при которой бэкапы хранятся на той же файловой системе, что и кластер.
И закладываться на это кажется ошибочным.

**Comment by gsmol** [comment]
Закрываем?
