### ISSUE TITLE
Возможности частичного восстановления.

### ISSUE THREAD

**Issue by ykurenkov** [postgrespro/pg_probackup#354]
Вопрос такой. А есть ли возможность восстановить в текущий кластер из бэкапа удаленную базу? Например, у нас есть кластер и его бэкапы В кластере по ошибке удалили базу. Возможно ли её восстановить из бэкапа? Пока вижу только вариант частичного восстановления в новый кластер и оттуда через dump-restore. Есть ли другие варианты, особенно интересные для баз больших объемов, например 1ТБ+?

**Comment by gsmol** [comment]
Добрый день.
Не вариант от слова совсем, базы в постгресе шарят между собой много чего: WAL, global, clog и прочее.
Склеить это вместе нереально, даже если база из того же инстанса.
Поэтому dump_restore, к сожалению, единственный вариант.

**Comment by ykurenkov** [comment]
Спасибо. Я это предполагал, но вдруг...
