### ISSUE TITLE
Выделенный пользователь резервного копирования и права на отдельные файлы.

### ISSUE THREAD

**Issue by dan-aksenov** [postgrespro/pg_probackup#356]
версия: БД 11.8
версия: pg_probackup-11 - 2.3.1
версия: patroni 1.6.5
ОС Ubuntu 18.04

На сервере резервного копирования и на сервере БД создана отдельная учетная запись **pgprobackup**.
Кластер под управлением patroni проинициализирован с парметром "allow-group-access"
Пользователь pgprobackup включен в группу postgres.

Однако, при попытке сделать резервную копию получаю ошибку:
```
INFO: Start transferring data files
ERROR: Cannot open source file "/data/postgresql/11/data/recovery.done": Permission denied
ERROR: Data files transferring failed, time elapsed: 0
```

Действительно после перезапуска кластера файл "recovery.done" имеет разрешния 600

При удалении recovery.done бекап проходит успешно. Но я бы не хотел такого решения в "проде".

Какие могут быть варианты решения проблемы запуска копирования под выделенным пользователем?

**Comment by gsmol** [comment]
Добрый день!
А каким образом был создан файл `recovery.conf` (который позже был переименован постгресом в recovery.done) ?

**Comment by gsmol** [comment]
Не был ли кластер восстановлен из бэкапа?

**Comment by gsmol** [comment]
> версия: pg_probackup-11 - 2.3.1
>
Рекомендую обновиться, версия годовой давности

**Comment by dan-aksenov** [comment]
Обновиться - не вариант. Пока мне сдается, что дело в patroni.
В директории с данными есть еще несколько файлов с "неправильными" разрешениями:
```
find /data/postgresql/11/data/ -type f  -perm 600
/data/postgresql/11/data/patroni.dynamic.json
/data/postgresql/11/data/postgresql.base.conf.backup
/data/postgresql/11/data/postgresql.conf.backup
/data/postgresql/11/data/recovery.done
```
А recovery.done появляется после перезапуска службы patroni

**Comment by dan-aksenov** [comment]
Думаю можно пока закрыть проблему. Если будут вопросы к pg_probackup - открою заново.
