### ISSUE TITLE
Не могу установить pg_probackup на ubuntu 20.10

### ISSUE THREAD

**Issue by avosluck** [postgrespro/pg_probackup#357]
Я пытаюсь установить pg_probackup на ubuntu 20.10 следуя мануалу на гитхабе, но ловлю ошибку

Err:7 https://repo.postgrespro.ru/pg_probackup/deb groovy Release
404 Not Found [IP: 93.174.131.139 443]
Hit:8 https://apt.postgresql.org/pub/repos/apt groovy-pgdg InRelease
Reading package lists... Done
E: The repository 'https://repo.postgrespro.ru/pg_probackup/deb groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by avosluck** [comment]
Я пытаюсь установить pg_probackup на ubuntu 20.10 следуя мануалу на гитхабе, но ловлю ошибку

Err:7 https://repo.postgrespro.ru/pg_probackup/deb groovy Release
  404  Not Found [IP: 93.174.131.139 443]
Hit:8 https://apt.postgresql.org/pub/repos/apt groovy-pgdg InRelease
Reading package lists... Done
E: The repository 'https://repo.postgrespro.ru/pg_probackup/deb groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by gsmol** [comment]
Добрый день!
20.10  скоро EOL, проще поставить пакеты для 20.04

**Comment by avosluck** [comment]
> Добрый день!
> 20.10 скоро EOL, поэтому для него нет отдельных пакетов, Вы можете поставить пакеты для 20.04

Спасибо! Сработало
