### ISSUE TITLE
Мануалы по работе с patroni кластером

### ISSUE THREAD

**Issue by avosluck** [postgrespro/pg_probackup#358]
Добрый день.

Только начинаю использовать Ваш продукт. Есть ли какие-то мануалы как правильно бекапить патрони кластер и соответственно восстанавливаться с бекапа.

Спасибо!

**Comment by gsmol** [comment]
Добрый день!
Каких-то готовых гайдов у нас на эту тему нет.
Нужно подумать, какую специфику привносит patroni в стандартный сценарий работы probackup с постгресом и какие у вас требования к резервным копиям.

**Comment by gsmol** [comment]
Есть доклад, в котором поверхностно описан пример интеграции:
https://docplayer.ru/182351710-Incountry-hranenie-reguliruemyh-dannyh-v-62-stranah-mira-pavel-konotopov-leonid-albreht.html

**Comment by avosluck** [comment]
> Есть доклад, в котором описан пример интеграции:
> https://docplayer.ru/182351710-Incountry-hranenie-reguliruemyh-dannyh-v-62-stranah-mira-pavel-konotopov-leonid-albreht.html

спасибо большое!
