### ISSUE TITLE
Публикация новых релизов

### ISSUE THREAD

**Issue by CHERTS** [postgrespro/pg_probackup#359]
День добрый,

На странице https://github.com/postgrespro/pg_probackup/releases вижу, что есть релизы 2.4.11, и даже уже 2.4.13, но в репо http://repo.postgrespro.ru/pg_probackup/deb/ их нет :(

Может какой сбой публикации? А то жду не дождусь новых версий с исправлениями багов, а их нет.

Спасибо.

**Comment by gsmol** [comment]
Это промежуточные версии, которые мы выпускаем не в рамках обычного релизного процесса, чтобы по горячим следам протестировать, что зарепорченные баги исправлены (как, например, тут https://github.com/postgrespro/pg_probackup/issues/351)
Ближайший публчный релиз - 2.3.14 на этой неделе.

**Comment by CHERTS** [comment]
Спасибо, буду ждать!
