### ISSUE TITLE
Опция для PG_STOP_BACKUP_TIMEOUT

### ISSUE THREAD

**Issue by olegkudrin** [postgrespro/pg_probackup#36]
Добавьте, пожалуйста, опцию для задания значения PG_STOP_BACKUP_TIMEOUT. На загруженной базе данных резервное копирование прерывается по истечении жестко заданных пяти минут. Меняю значение тайм-аута в исходниках и пересобираю программу, тогда резервное копирование успешно завершается.

**Comment by gsmol** [comment]
Добрый день.
Я подозреваю, что pg_stop_backup долго отрабатывает из-за того, что ожидает архивации WAL сегмента с STOP LSN. Можете привести лог PostgreSQL, соответствующий этому моменту?

**Comment by gsmol** [comment]
Как временное решение, мы решили привязать этот таймаут к --archive-timeout.
В будущем скорее всего появится отдельный параметр --query-timeout.
Фикс выйдет завтра в версии 2.0.25.

**Comment by gsmol** [comment]
Fixed in c14c5a58c
