### ISSUE TITLE
unlogged таблицы увеличивают размер DELTA бэкапа

### ISSUE THREAD

**Issue by Zergvl** [postgrespro/pg_probackup#360]
1.  
PostgresPro (standard) 11.10.1
pg_probackup 2.4.10
Развёрнута тестовая БД ~10GB. Проблем с бэкапами нет.
в 19:15 создана unlogged таблица ~3GB. 
DELTA бэкапы увеличились на размер новой таблицы.
![1](https://user-images.githubusercontent.com/39025791/114381151-261dfd80-9bce-11eb-858f-3bd6218a9d50.JPG)

2.
PostgreSQL 11.10
pg_probackup-11 2.4.10 
Развёрнута тестовая БД ~10GB. Проблем с бэкапами нет.
в 20:11 создана unlogged таблица ~3GB. 
DELTA бэкапы увеличились на размер новой таблицы.
![2](https://user-images.githubusercontent.com/39025791/114381328-58c7f600-9bce-11eb-9036-3b549e9662aa.JPG)

**Comment by gsmol** [comment]
Исправил.
Фикс выйдет в 2.4.17
