### ISSUE TITLE
Пользователь ОС для запуска pg_probackup

### ISSUE THREAD

**Issue by user12344312** [postgrespro/pg_probackup#372]
Здравствуйте!

В документации сказано, что запускать pg_probackup нужно пользователя ОС, который имеет доступ на чтение всех файлов и каталогов внутри PGDATA.

Также в документации говорится, что рекомендуется создать отдельную роль в PostgreSQL с минимальными правами.

Подскажите, пожалуйста, какого пользователя в Linux рекомендуется использовать для запуска pg_probackup. Если это не root и не postgres, как правильно выдать ему права на чтение PGDATA?

**Comment by gsmol** [comment]
Добрый день!
Штатный PostgreSQL способ - это group access
https://paquier.xyz/postgresql-2/postgres-11-group-access/

**Comment by user12344312** [comment]
Спасибо!
