### ISSUE TITLE
Ошибка очистки WAL, если каталог архивов WAL является symlink

### ISSUE THREAD

**Issue by triwada** [postgrespro/pg_probackup#376]
На одном серверов используется для хранения бэкапов разделы, подключенные по iscsi (в этом случае есть ограничение, что на них можно сделать ФС только до 16ТБ).
Как вариант попробовали вынести каталог архивов WAL на другой раздел, сделав на него symlink. Архивирование работает, но вот с удалением старых WAL проблема, т.к. pg_probackup не может обработать файла symlink

$ pg_probackup delete -B /pgdump/backup/ --instance dummy --wal --log-level-console=INFO
WARNING: Skip "/pgdump/backup/wal/dummy": unexpected file format
INFO: There are no backups to merge by retention policy
INFO: There are no backups to delete by retention policy
INFO: There is no WAL to purge by retention policy

$ ls -lh /pgdump/backup/wal/
итого 82M
lrwxrwxrwx 1 postgres postgres   27 апр 14 22:47 dummy -> /pgdump2/backup/wal/dummy

Как можно решить?

**Comment by gsmol** [comment]
Хм, похоже на баг.
А если перенести симлинк уровнем выше на `/pgdump/backup/wal`

**Comment by gsmol** [comment]
Пофиксил

**Comment by triwada** [comment]
> А если перенести симлинк уровнем выше на /pgdump/backup/wal
Это помогло

**Comment by triwada** [comment]
Спасибо
