### ISSUE TITLE
ошибка в README.md - установка репы в Ubuntu 

### ISSUE THREAD

**Issue by dld-r00f** [postgrespro/pg_probackup#379]
Строка `sudo echo "deb [arch=amd64] https://repo.postgrespro.ru/pg_probackup/deb/ $(lsb_release -cs) main-$(lsb_release -cs)" > /etc/apt/sources.list.d/pg_probackup.list` не работает от обычного пользователя. Так как `sudo` распространяется только на команду `echo`, и не даёт прав перенаправлению на запись в директорию `/etc/apt/sources.list.d/`
чтобы работало нужно что-то вроде:
`sudo sh -c 'echo "deb [arch=amd64] https://repo.postgrespro.ru/pg_probackup/deb/ $(lsb_release -cs) main-$(lsb_release -cs)" > /etc/apt/sources.list.d/pg_probackup.list'`

я сделал пул реквест в мастер с исправлением этой строчки в ридми, но не уверен, что поступил правильно :)
#378

**Comment by gsmol** [comment]
Добрый день!
Вы поступили правильно, ведь вы самостоятельно взялись за решение проблемы =)
Оставил предложения по улучшению вашего патча в тредике ваше пулл-реквеста.

**Comment by dld-r00f** [comment]
Спасибо, я, просто, не был уверен, что в мастер стоит пулреквест делать.
Я добавил изменения для секции PostgresPro.
