### ISSUE TITLE
Валидирование бекапа меняет даты создания директориев на дату валидирования

### ISSUE THREAD

**Issue by shab2** [postgrespro/pg_probackup#384]
Добрый день.

Делаю бекап на один сервер, затем делаю rsync синхронизацию на другой.  На втором сервере делаю валидирование.
После валидирования, указанные ниже каталоги, меняют даты на дату проведения валидирования.
После этого для rsync бекапы на разных серверах НЕ идентичны.
Вопрос: Можно ли внести изменения в программу так, чтобы в валидируемом бекапе даты каталогов не менялись?
Спасибо.

Ниже приведен пример.

postgres@db-cyberft-wtc:~
[LEP]$ ls -lh $BACKUP_PATH/backups/$DB_SID/
total 56K
-rw-r--r-- 1 postgres postgres  191 Feb 25 23:26 pg_probackup.conf
drwx------ 3 postgres postgres 4.0K May  9 22:00 QSUSS2
drwx------ 3 postgres postgres 4.0K May 10 22:00 QSWNG1
drwx------ 3 postgres postgres 4.0K May 11 22:00 QSYI42
drwx------ 3 postgres postgres 4.0K May 12 22:00 QT0CS2
drwx------ 3 postgres postgres 4.0K May 14 03:00 QT2LC1
drwx------ 3 postgres postgres 4.0K May 14 10:48 QT36ZL
drwx------ 3 postgres postgres 4.0K May 14 11:39 QT39CX
drwx------ 3 postgres postgres 4.0K May 14 11:46 QT39OK
drwx------ 3 postgres postgres 4.0K May 14 11:50 QT39W2
drwx------ 3 postgres postgres 4.0K May 14 12:08 QT3APU
drwx------ 3 postgres postgres 4.0K May 14 12:10 QT3ARS
drwx------ 3 postgres postgres 4.0K May 14 12:25 QT3BHV
drwx------ 3 postgres postgres 4.0K May 15 03:00 QT4G02

[LEP]$ pg_probackup validate --instance=$DB_SID; ls -lh $BACKUP_PATH/backups/$DB_SID/
INFO: Validate backups of the instance 'LEP'
INFO: Validating backup QT4G02
INFO: Backup QT4G02 data files are valid
INFO: Backup QT4G02 WAL segments are valid
INFO: Validating backup QT3BHV
INFO: Backup QT3BHV data files are valid
INFO: Backup QT3BHV WAL segments are valid
INFO: Validating backup QT3ARS
INFO: Backup QT3ARS data files are valid
INFO: Backup QT3ARS WAL segments are valid
INFO: Validating backup QT3APU
INFO: Backup QT3APU data files are valid
INFO: Backup QT3APU WAL segments are valid
INFO: Validating backup QT39W2
INFO: Backup QT39W2 data files are valid
INFO: Backup QT39W2 WAL segments are valid
INFO: Validating backup QT39OK
INFO: Backup QT39OK data files are valid
INFO: Backup QT39OK WAL segments are valid
INFO: Validating backup QT39CX
INFO: Backup QT39CX data files are valid
INFO: Backup QT39CX WAL segments are valid
INFO: Validating backup QT36ZL
INFO: Backup QT36ZL data files are valid
INFO: Backup QT36ZL WAL segments are valid
INFO: Validating backup QT2LC1
INFO: Backup QT2LC1 data files are valid
INFO: Backup QT2LC1 WAL segments are valid
INFO: Validating backup QT0CS2
INFO: Backup QT0CS2 data files are valid
INFO: Backup QT0CS2 WAL segments are valid
INFO: Validating backup QSYI42
INFO: Backup QSYI42 data files are valid
INFO: Backup QSYI42 WAL segments are valid
INFO: Validating backup QSWNG1
INFO: Backup QSWNG1 data files are valid
INFO: Backup QSWNG1 WAL segments are valid
INFO: Validating backup QSUSS2
INFO: Backup QSUSS2 data files are valid
INFO: Backup QSUSS2 WAL segments are valid
INFO: All backups are valid
total 56K
-rw-r--r-- 1 postgres postgres  191 Feb 25 23:26 pg_probackup.conf
drwx------ 3 postgres postgres 4.0K May 15 22:21 QSUSS2
drwx------ 3 postgres postgres 4.0K May 15 22:21 QSWNG1
drwx------ 3 postgres postgres 4.0K May 15 22:21 QSYI42
drwx------ 3 postgres postgres 4.0K May 15 22:21 QT0CS2
drwx------ 3 postgres postgres 4.0K May 15 22:21 QT2LC1
drwx------ 3 postgres postgres 4.0K May 15 22:21 QT36ZL
drwx------ 3 postgres postgres 4.0K May 15 22:21 QT39CX
drwx------ 3 postgres postgres 4.0K May 15 22:21 QT39OK
drwx------ 3 postgres postgres 4.0K May 15 22:21 QT39W2
drwx------ 3 postgres postgres 4.0K May 15 22:21 QT3APU
drwx------ 3 postgres postgres 4.0K May 15 22:21 QT3ARS
drwx------ 3 postgres postgres 4.0K May 15 22:21 QT3BHV
drwx------ 3 postgres postgres 4.0K May 15 22:21 QT4G02

**Comment by gsmol** [comment]
Добрый день!
Хм, неожиданно, а какая версия используется?

**Comment by shab2** [comment]
[LEP]$ pg_probackup version
pg_probackup 2.4.10 (PostgreSQL 13.1)

**Comment by shab2** [comment]
Еще можно вопрос? Как можно задействовать все ядра процессора во время бекапа с компрессией zlib?

**Comment by gsmol** [comment]
> Еще можно вопрос? Как можно задействовать все ядра процессора во время бекапа с компрессией zlib?
>
Задайте побольше тредов опцией `-j`, например `-j 5`

**Comment by gsmol** [comment]
mtime директории меняется из-за того, что перед валидацией мы лочим бэкап, создавая в директории бэкапа лок файл.
По-моему это не такая большая беда в контексте rsync
