### ISSUE TITLE
Switch off archive_command on restored instance after success restoration

### ISSUE THREAD

**Issue by slothfk** [postgrespro/pg_probackup#395]
Hi!
pg_barman comments string with archive_command in postgresql.conf on restored instance after recovery process successfully complete
can you make this feature by default behavior as pg_barman do this?

**Comment by gsmol** [comment]
Hello!
It is almost impossible to do this deterministically, since `archive_command` can be defined in config file, that we have no knowledge about, or be even defined via command line paramenter to postgres binary.
What problem are you trying to avoid exactly here?

**Comment by slothfk** [comment]
> What problem are you trying to avoid exactly here?

what is happened if i restore some instance in original environment where remote file server for backups is available and original instance is still work properly?

**Comment by gsmol** [comment]
Same as with any restore: you will get an instance with timeline and you will have a new timeline in your WAL archive.
This is correct behavior.

**Comment by slothfk** [comment]
i start to understand now why we must use archive-push in archive_command directive

**Comment by gsmol** [comment]
Can we close this issue or there are some questions left ?
