### ISSUE TITLE
can support MD5 when validting backup?

### ISSUE THREAD

**Issue by killua001** [postgrespro/pg_probackup#4]
Hi,
For now, many storages will save a file's MD5 in the metadata.  Can probackup do the consistency checks for database cluster files and backups use MD5 ?

Thank you.

**Comment by stalkerg** [comment]
probackup do it but in their own way. 
For backups we save CRC32 for each files (and can check it by validate command).
For instance we can check checksums for each page during full backup (in next versions we planned make this option as independent command).
