### ISSUE TITLE
Совместимость с Postgres Pro Standard 13

### ISSUE THREAD

**Issue by Morozzz689** [postgrespro/pg_probackup#402]
Добрый день!
Не обнаружил в репозитории https://repo.postgrespro.ru/pg_probackup-forks/deb/ опубликованных релизов для Pro Standard 13.
Есть ли особая причина их отсутствия?) Если нет, то подскажите пожалуйста, как корректно выполнить сборку для данной версии бд?

**Comment by gsmol** [comment]
Добрый день!
> Есть ли особая причина их отсутствия?
>
Нет, в рамках ближайшего релиза выпустим.
Если Вам горит, то могу собрать для Вас персонально - скажите версию OS

**Comment by Morozzz689** [comment]
Ubuntu 20.04

**Comment by Morozzz689** [comment]
Григорий, добрый день!
Подскажите, когда у вас найдется время чтобы подготовить сборку? Ну или когда примерно нам ожидать новый релиз? =)

**Comment by gsmol** [comment]
Добрый день!
Сегодня постараюсь сделать

**Comment by zorion79** [comment]
Так же для Ubuntu 20.04 отсутствует пакет pg_probackup-ent-12 Сделайте его тоже, пожалуйста.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/2866872/124525825-0c462c80-de44-11eb-9175-24d5d94d6305.png">

**Comment by Maksimilian063** [comment]
Григорий, добрый день!
Скажите, пожалуйста, когда можно ожидать сборку для Pro Standard 13?
Прошу прощения, если мой вопрос покажется вам "менеджерским пушем", просто эта сборка очень нужна нам для критически важного функционала в продукте

**Comment by gsmol** [comment]
Добрый день!
Всё правильно делаете, что периодически тыкаете палочкой.
Сегодня будет - край ночью, торжественно обещаю =)

**Comment by gsmol** [comment]
Готово, всё затребованные версии собраны, включая Enterprise для Ubuntu 20.4:
https://oc.postgrespro.ru/index.php/s/rVh2X8zQJhOntsk

В репо пакеты добавлю в выходные в рамках выхода 2.4.17

**Comment by Maksimilian063** [comment]
Спасибо вам огромное!

**Comment by triwada** [comment]
а когда в официальной ветке pgpro появятся?
https://repo.postgrespro.ru/pg_probackup-forks/rpm/latest/rhel-7Server-x86_64/ - здесь нет версии 13
