### ISSUE TITLE
start directly from direcotry which is created by pg_probackup 

### ISSUE THREAD

**Issue by qiulg** [postgrespro/pg_probackup#403]
Hi,

I found the database directory created by pg_probackup backup is almost same as original pg data direcotry, so I'm wondering if I can start database from backup directly. After stop original pg, I tried to start pg directly from the backup directory. The database started but has error in log file keep saying "FATAL: invalid page in block 0 of relation global/1262" and can not be connected".

My step is,
1. backup production:
pg_probackup backup -B /backup/pg_probackup --instance local_5432 -b full --stream --compress-alg=none --compress-level=0
2. stop original db and start this new:
pg_ctl -D  /backup/pg_probackup/backups/local_5432/QVPOT0/database start

My qustion is,
1. Is it possible to start database directly from full backup?
2. Is it possible to start database directly from a merge incremental backup?

Thanks!
Ligong

**Comment by gsmol** [comment]
Hello!
Unfortunately at this moment it is not possible due to the fact, that pg_probackup add its own 8-byte header to every page in cluster.
