### ISSUE TITLE
pg_probackup acting like pg_receivewal

### ISSUE THREAD

**Issue by alepaes1975** [postgrespro/pg_probackup#406]
Hi,

There is a way to put pg_backup in "continuous" running mode receiving streaming log via replication slots, like
pg_receivewal do ?
My backups are remote, and I dont want the archive_command way to send wal files.
If this cannot be possible, can I receive the stream via pg_receivewal and point pg_probackup to incorporate this WALs in catalog ?

Thanks for this incredible tool.

Best regards,

Alexandre

**Comment by gsmol** [comment]
Hello!
It is possible to setup pg_receivewal to steam WAL into corresponding wal directory in pg_probackup catalog.
pg_probackup does not care about the source of WAL as long it flows =)
Look at the second `Note` here:
https://postgrespro.github.io/pg_probackup/#pbk-setting-up-continuous-wal-archiving

**Comment by alepaes1975** [comment]
Hi !

Thank you very much! I haven't seen these notes in the documentation and this will help me a lot.

Best regards,
Alexandre

**Comment by uspen** [comment]
But there is a nuance when pg_probackup will require NOT a flat waldir, but a tree structure like 0000002C / 0000002C0000005E00000061.gz
