### ISSUE TITLE
Восстановление только одной базы кластера.

### ISSUE THREAD

**Issue by grudinko** [postgrespro/pg_probackup#407]
Добрый день!
Раньше пользовался pg_dump и мог восстановить только одну базу в кластере, не останавливая кластера.
Теперь хочу инкрементные бэкапы с помощью pg_probackup, но не понимаю как реализовать частичное восстановление.
А баз у меня на кластере куча, 1С все такое)

**Comment by gsmol** [comment]
Добрый день!
Посмотрите в документации:
https://postgrespro.github.io/pg_probackup/#pbk-partial-restore

**Comment by grudinko** [comment]
Да, я пробовал так делать, но probackup ругается на то, что папка data не пуста. А как она может быть пуста при работающем сервере?

**Comment by gsmol** [comment]
В работающий кластер нельзя восстановить отдельную базу

**Comment by grudinko** [comment]
У меня есть второй postgres, я пробовал сначала восстановить в него, чтобы потом перенести информацию дампом. Но мой второй postgres не стартанул после таких действий. Может есть примеры как это сделать правильно?

**Comment by gsmol** [comment]
> У меня есть второй postgres, я пробовал сначала восстановить в него, чтобы потом перенести информацию дампом. Но мой второй postgres не стартанул после таких действий
>
А на что именно он ругался?
