### ISSUE TITLE
Backup ****** is running, setting its status to ERROR

### ISSUE THREAD

**Issue by sk011** [postgrespro/pg_probackup#42]
Добрый день. 
По крону "снимаю" бекап 
`pg_probackup-9.5 backup -B /var/lib/postgresql/backup --instance prod -b FULL --stream`
все отрабатывает, но иногда (не знаю зависимости ) завершается ошибкой
`prod      9.5      PLCB9D  ---                     FULL  STREAM  1 / 0               545s      0B  D96/3D00C3D0           0/0  ERROR`
в логе 
```
INFO: Backup start, pg_probackup version: 2.0.24, backup ID: PLCB9D, backup mode: full, instance: prod, stream: true, remote: false
WARNING: This PostgreSQL instance was initialized without data block checksums. pg_probackup have no way to detect data block corruption without them. Reinitialize PGDATA with option '--data-checksums'.
INFO: Start transfering data files
INFO: Data files are transfered
INFO: wait for pg_stop_backup()
INFO: pg_stop backup() successfully executed
INFO: Wait for LSN D96/3D08A028 in archived WAL segment /var/lib/postgresql/backup/backups/prod/PLCB9D/database/pg_xlog/0000000100000D960000003D
ERROR: WAL segment 0000000100000D960000003D was archived, but target LSN D96/3D08A028 could not be archived in 330 seconds
WARNING: Backup PLCB9D is running, setting its status to ERROR
INFO: Nothing to delete by retention policy
```
целевой LSN не может быть заархивирован? Помогите понять почему и главное как это иправить
Спасибо

**Comment by gsmol** [comment]
Добрый день.
Бэкап снимаете с реплики?
Спасибо за фидбэк!

**Comment by sk011** [comment]
Добрый день. Реплики нет. Работающая БД

пт, 18 янв. 2019 г., 18:20 gsmol notifications@github.com:

**Comment by gsmol** [comment]
Попробуйте обновиться на 2.0.26.

**Comment by sk011** [comment]
Обновился. Надо время наблюдать. Напишу потом. Спасибо!

**Comment by gsmol** [comment]
Добрый день.
Я правильно понимаю, что на 2.0.26 данная проблема не воспроизводится?

**Comment by sk011** [comment]
Добрый. С момента обновления до 2.0.26 проблема отсутствует.

**Comment by gsmol** [comment]
Тогда я закрываю баг с вашего разрешения.
