### ISSUE TITLE
Возобновленный MERGE выполнялся 12 часов, вместо обычных 2

### ISSUE THREAD

**Issue by alexandermalykhin** [postgrespro/pg_probackup#421]
Добрый день!
Ситуация следующая:
Прервал процесс бэкапа (нужно было перезапустить master), запускаемый следующим образом:
pg_probackup-11 backup -B /srv/storage/postgres_backup -b PAGE --instance=pgsrv --stream --temp-slot --log-lev
el-console=off --delete-expired --merge-expired --delete-wal -j 4
При этом сам инкремент уже успел выполниться и kill пришел в момент merge.
После этого попробовал просто запустить процесс той же командой, но вылетел с ошибкой, т.к. не нашел "живой" FULL
У меня FULL один, он "скользящий". 
Запустил pg_probackup-11 merge -B /srv/storage/postgres_backup --instance=pgsrv -j 4 -i
Все прошло нормально, за исключением времени выполнения. 
В логах ничего "необычного", т.к. verbosity не добавлял. 
Не сколько ошибка программы, сколько хочу понять из-за чего такое могло случиться (замедление процесса)?

**Comment by alexandermalykhin** [comment]
[pg_probackup_2021-08-15.log](https://github.com/postgrespro/pg_probackup/files/6988032/pg_probackup_2021-08-15.log)

**Comment by gsmol** [comment]
Добрый день!
> Не сколько ошибка программы, сколько хочу понять из-за чего такое могло случиться (замедление процесса)?
>
merge по умолчнию использует массу оптимизаций, которые невозможно использовать при re-run мержа =(

**Comment by gsmol** [comment]
Закрываем?

**Comment by alexandermalykhin** [comment]
> Закрываем?

Да, конечно.
Спасибо за ответы!
