### ISSUE TITLE
RH8 support?

### ISSUE THREAD

**Issue by PavelSorokin** [postgrespro/pg_probackup#428]
Будет ли доступна сборка под os rh-8?
из репозитория  http://repo.postgrespro.ru/pg_probackup/rpm/2.4.9/

**Comment by PavelSorokin** [comment]
для Pg-13 и Pg-std-11(13)

**Comment by gsmol** [comment]
Добрый день!
Да, ожидается.

**Comment by gsmol** [comment]
RH8 support added in 2.5.2
