### ISSUE TITLE
question : retention ala barman style?

### ISSUE THREAD

**Issue by achix** [postgrespro/pg_probackup#43]
Hello, I think it is possible to just roll the oldest back back by specifying the next incremental backup to merge, so the window is moving forward, in the following fashion : 
FULL backup-6
PAGE backup-5
PAGE backup-4
PAGE backup-3
PAGE backup-2
PAGE backup-1
PAGE backup

where -6 means -6 days in the past.
so we could take a new incremental (page) backup every day, and then move the window forward by doing : 
./pg_probackup/pg_probackup merge -B /usr/local/var/lib/pgsql/mypgprobacks/ --instance testdb -i backup-5, i.e. the oldest page backup , resulting to 
FULL backup-5
PAGE backup-4
PAGE backup-3
PAGE backup-2
PAGE backup-1
PAGE backup
PAGE backup+1

PAGE backup-5 becoming FULL backup-5

So could we just use merge instead of delete in order to create an equivalent to a transparent window?

**Comment by gsmol** [comment]
Hello!
This is exactly why "merge" was conceived in the first place.
But we are a bit paranoid about it and think that this feauture is dangerous in a sense, that any possible bugs in old versions, will be accumulated in merged backup. So we need to be sure that:
a) current backup/restore algorithm is solid, which we think he is. Latest bugfix in 2.0.24.
b) current merge algorithm is solid. Latest bugfixes for merge are in 2.0.26, so, I think, we need more time to pass to consider merge to be "stable"

**Comment by achix** [comment]
Thank you for your fine explanation!
Also if I got it right, the backups can only be done locally, as the docs write : 
"The backup catalog must belong to the file system of the database server"
and this means that we cannot add remote instances. So, I'd like to ask you two questions : 
a) then why do the "[-d dbname] [-h host] [-p port] [-U username]" options exist in the backup?
b) do you plan to write this remote feature?

thanks!

**Comment by gsmol** [comment]
a) it is address for libpq connection to PostgreSQL
b) yes, you can track remote backup development in remote_ssh branch

**Comment by achix** [comment]
About the remote backup I'll check this as soon as possible, thanks!

**Comment by gsmol** [comment]
Hold on. I`ve just noticed that help isn`t up to date about remote backup.
I will try to update it today.

**Comment by achix** [comment]
And a mini howto would help. Currently I built the branch but still add-instance asks for a valid -D pgdata-path in the current catalog host's filesys.
