### ISSUE TITLE
PITR restore report error when using --recovery-target-time option

### ISSUE THREAD

**Issue by huanghy0592** [postgrespro/pg_probackup#432]
Hello, I am attempting to test a recovery of a 13.4 postgres cluster installed on redhat 7.9
from an full backup that I have set up using version 2.4.15,

I have setting the pg parameter:
max_wal_senders=4
wal_level = 'replica'
archive_mode = 'on'
archive_command = '/home/postgres/postgresql-13/bin/pg_probackup archive-push -B /home/postgres/bak --instance local_5432 --wal-file-path=%p --wal-file-name=%f' 
 
and restart postgresql.

my test case like this：
1.I make a full backup of backup at date '2021-09-17 15:09:59+08';

2.create a test table:
testdb=> create table t2 (id int primary key,name varchar(10));
testdb=> insert into t2 values (1,'aaa');
INSERT 0 1
testdb=> insert into t2 values (2,'bbb');
INSERT 0 1
testdb=> 
testdb=>  select current_timestamp;
       current_timestamp       
-------------------------------
 2021-09-17 15:14:49.284137+08
(1 row)

3. switch the wal file:
postgres=# select pg_switch_wal();
 pg_switch_wal 
---------------
 0/EA000318
(1 row)

postgres=# 
postgres=# select current_timestamp;
       current_timestamp       
-------------------------------
 2021-09-17 15:16:02.502561+08
(1 row)

4.continue to insert data:
testdb=> insert into t2 values (3,'ccc');
INSERT 0 1
testdb=> insert into t2 values (4,'ddd');
INSERT 0 1
testdb=>  select current_timestamp;
      current_timestamp       
------------------------------
 2021-09-17 15:16:52.47418+08
(1 row)

5.make a full backup again:
$ pg_probackup backup -B /home/postgres/bak/ --instance local_5432 -b full

Now ,I want to restore the t2 at the moment(after insert into record(2,'bbb'));

so I perform the following step:

1.check the backup detail: 
[postgres@pg1 data]$ pg_probackup show -B /home/postgres/bak/

BACKUP INSTANCE 'local_5432'
======================================================================================================================================
 Instance    Version  ID      Recovery Time           Mode  WAL Mode  TLI  Time    Data   WAL  Zratio  Start LSN   Stop LSN    Status 
======================================================================================================================================
 local_5432  13       QZKHL0  2021-09-17 15:17:26+08  FULL  ARCHIVE   3/0    5s  9844kB  16MB    3.29  0/EC000028  0/ED0000F0  OK     
 local_5432  13       QZKH8M  2021-09-17 15:09:59+08  FULL  ARCHIVE   2/0    4s  9844kB  16MB    3.29  0/E7000028  0/E80000F0  OK     
 local_5432  13       QZKGZL  2021-09-17 15:04:35+08  FULL  ARCHIVE   2/0    4s  9844kB  16MB    3.29  0/E4000028  0/E50000B8  OK     

2. pg_ctl stop and rm -rf $PGDATA
3.issue the command :
[postgres@pg1 postgresql-13]$ pg_probackup restore -B /home/postgres/bak/  --instance local_5432 -i QZKH8M --recovery-target-time="2021-09-17 15:16:02.502561+08"
ERROR: Invalid value for '--recovery-target-time' option '2021-09-17 15:16:02.502561+08'
[postgres@pg1 postgresql-13]$ 
[postgres@pg1 postgresql-13]$ 
[postgres@pg1 postgresql-13]$ 
[postgres@pg1 postgresql-13]$ pg_probackup restore -B /home/postgres/bak/  --instance local_5432 --recovery-target-time="2021-09-17 15:16:02.502561+08" --log-level-console=verbose
ERROR: Invalid value for '--recovery-target-time' option '2021-09-17 15:16:02.502561+08'
[postgres@pg1 postgresql-13]$ 
[postgres@pg1 postgresql-13]$pg_probackup restore -B /home/postgres/bak/  --instance local_5432 --recovery-target-time="2021-09-17 15:14:49.284137+08"
ERROR: Invalid value for '--recovery-target-time' option '2021-09-17 15:14:49.284137+08'
[postgres@pg1 data]$ 

why it report ERROR?  please help me ,thank you.

**Comment by gsmol** [comment]
Hello!
Currently `--recovery-target-time` does not support milliseconds, only seconds- level granularity is supported. So this should work:
```
--recovery-target-time="2021-09-17 15:16:02+08"
```

**Comment by gsmol** [comment]
Can we close this issue?

**Comment by huanghy0592** [comment]
pls close the issue,thank you.
