### ISSUE TITLE
refresh repository

### ISSUE THREAD

**Issue by jacks33** [postgrespro/pg_probackup#433]
Hello,

could  you please refresh repositories  https://repo.postgrespro.ru/pg_probackup/rpm/latest/suse-15.2-x86_64/

available  packages are 2.4.15 version.

Currently is 2.5.1

**Comment by gsmol** [comment]
Hello!
It is not quite ready yet to releasing it to public.
We are planning to release 2.4.17 first, do some heavy testing of 2.5.1 and then release it as 2.5.2

**Comment by gsmol** [comment]
2.5.2 released
