### ISSUE TITLE
Совместимость версий pg_probackup

### ISSUE THREAD

**Issue by BadRobot2000** [postgrespro/pg_probackup#446]
Задача стоит сделать один сервер для бэкапов разных баз PG с разных серверов разных версий - 9.6, 10, 12.
Требуется ли ставить на этот сервер pg_probackup всех этих версий, а также на сервера БД тоже соответствующей версии pg_probackup и каждой из них свой репозиторий для хранения бэкапов?
Или достаточно, скажем, pg_probackup-12 или 13 поставить и на этот сервер и сервера баз?

**Comment by BadRobot2000** [comment]
> 
> 
> Нет, а зачем?

Ну вдруг там тоже какие-то метаданные пишутся?

Экспериментально проверил - работает, но для каждого сервера только свою версию запускать надо, как вы и указали.
Спасибо!

**Comment by gsmol** [comment]
Рад был помочь!
