### ISSUE TITLE
Invalid CRC of backup file

### ISSUE THREAD

**Issue by aeuge** [postgrespro/pg_probackup#453]
Столкнулся с проблемой на ванильном Постгресе Ubuntu 20.04(21.04) (ВМ в GCP e2-standard)
ставлю с нуля Постгрес 13 (14) и пробкап 13 (14) - пробовал уже кучу разных вариантов
создаю каталог и создаю переменную export BACKUP_PATH='/var/lib/postgresql/13/main/backups/'
первый полный бэкап (из под рута. до этого и пользователя бэкап делал и все - сейчас для простоты воспроизведения) проходит на ура
делаю второй полный после этого и получаю ошибки:
INFO: Syncing backup files to disk
INFO: Backup files are synced, time elapsed: 4s
INFO: Validating backup R2TB1I
WARNING: Invalid CRC of backup file "/var/lib/postgresql/13/main/backups/backups/main/R2TB1I/database/backups/backups/main/R2TB16/database/global/pg_control" : A7DB2EB. Expected 87208743
WARNING: Backup R2TB1I data files are corrupted
INFO: Backup R2TB1I resident size: 63MB
ERROR: Backup R2TB1I failed

любые другие бэкапы также не проходят

Для воспроизведения:
sudo su postgres
mkdir /var/lib/postgresql/13/main/backups/
export BACKUP_PATH='/var/lib/postgresql/13/main/backups/'
pg_probackup-13 init
pg_probackup-13 add-instance --instance 'main' -D /var/lib/postgresql/13/main
pg_probackup-13 backup --instance 'main' -b FULL --stream --temp-slot
pg_probackup-13 backup --instance 'main' -b FULL --stream --temp-slot

При этом если создать каталог /home/backups и выдать права 777 и в него делать бэкапы, то все проходит на ура.
При указании любых каталогов, даже вложенных в папке с БД для бэкапов выдают такую ошибку

**Comment by gsmol** [comment]
Добрый день!
А какая версия pg_probackup ?
Это можно узнать с помощью `pg_probackup-13 --version`

**Comment by gsmol** [comment]
Пришлите, пожалуйста, выхлоп команды `pg_probackup-13 show --instance 'main'`

**Comment by aeuge** [comment]
Добрый день, gsmol. Проблема была и в 13 и 14 версии. Опять же архитектурно неправильно делать бэкап в каталог с БД, сделал отдельно и проблема больше не повторялась. Тех ВМ уже нет, версию конечно уже не вспомню

**Comment by gsmol** [comment]
Ааа, вы рекурсивно пытались забэкапить каталог бэкапов вместе с PGFATA, я только сейчас допер.
Вообще выглядит как интересный футган

**Comment by funny-falcon** [comment]
Раз причина стала понятна, и она внешняя, пока закрою.

Если кто-то ещё наступит на граблю, будем думать о детекторе грабли.
