### ISSUE TITLE
Ошибка 404 при установке на rhel-8-x86_64

### ISSUE THREAD

**Issue by rusha1333** [postgrespro/pg_probackup#455]
Пробую ставить и вот что пишет:
[root@01 ~]# yum install pg_probackup-{std,ent}-{13,12,11,10,9.6}
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

Repository 'docker-ce-edge' is missing name in configuration, using id.
PG_PROBACKUP Packages for RedHat Linux - x86_64                                                                                                                                                                                                 1.1 kB/s | 177  B     00:00
Errors during downloading metadata for repository 'pg_probackup':
  - Status code: 404 for https://repo.postgrespro.ru/pg_probackup/rpm/latest/rhel-8-x86_64/repodata/repomd.xml (IP: 10.63.11.61)
Error: Failed to download metadata for repo 'pg_probackup': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**Comment by gsmol** [comment]
Добрый день!
Косяк, поправим

**Comment by rusha1333** [comment]
Добрый! Спасибо, ждем

**Comment by kulaginm** [comment]
Исправлено

**Comment by rusha1333** [comment]
Спасибо!

**Comment by shaksul** [comment]
Приветствую
PG_PROBACKUP Packages for Oracle Linux - x86_64                                                                                                                                                              132  B/s | 153  B     00:01
Errors during downloading metadata for repository 'pg_probackup':
  - Status code: 404 for https://repo.postgrespro.ru/pg_probackup/rpm/latest/oraclelinux-8-x86_64/repodata/repomd.xml (IP: 213.171.56.11)
Ошибка: Не удалось загрузить метаданные для репозитория «pg_probackup»: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**Comment by fukanchik** [comment]
Начиная с версии 2.5.14 дистрибутивы, основанные на redhat должны использовать пакеты centos.

Это описано в разделе Installation в release notes 2.5.14: https://github.com/postgrespro/pg_probackup/releases/tag/2.5.14

> Red Hat-like systems (Red Hat, Oracle Linux, Rocky Linux etc) should now use CentOS pg_probackup packages so one may need to [add](https://postgrespro.github.io/pg_probackup/#pbk-install-rhel) the CentOS repository to the package manager.
