### ISSUE TITLE
Возможность исключения файлов из резервной копии

### ISSUE THREAD

**Issue by kkrasnov1** [postgrespro/pg_probackup#461]
Здравствуйте!

Добавьте, пожалуйста, возможность исключения файлов при резервном копировании, т.к. иногда в pgdata могут быть файлы, которые не нужны в копии или на которые отсутствуют права на чтение.

**Comment by gsmol** [comment]
Добрый день!
Звучит как довольно опасная фича, можно легко прострелить себе ногу.
Можете привести пример таких файлов?

**Comment by gsmol** [comment]
В любом случае мы стремимся исключать файлы при восстановлении, а не при бэкапе
