### ISSUE TITLE
Права на файлы резервных копий и архивов wal при использовании group access и выделенного пользователя для резервного копирования.

### ISSUE THREAD

**Issue by Andreev-AV** [postgrespro/pg_probackup#466]
Добрый день.

Подскажите пожалуйста, как корректно создать на уровне ОС Linux выделенного пользователя для выполнения резервного копирования при использовании group access?

Настройки на стороне СУБД понятны и описаны в документации, интересует именно пользователь ОС, его права и т.д.

**Проблема:** при выполнении резервного копирования от специального пользователя для резервного копирования каталоги резервных копий создаются с правами <**drwx------**  3 probackup postgres   97 Jan 20 05:05 R5Z9CE>, файлы журналов wal  с правами <**-rw-------** 1 probackup postgres  7224514 Jan 21 09:56 00000005000000970000002D.gz>. Соответственно при восстановлении, а оно обычно производится с правами пользователя postgres, получаем отсутствие доступа к необходимым подкаталогам и файлам в каталоге резервных копий.

**Версии:** pg_probackup 2.5.3 (Postgres Pro 11.14.1 standard).
**Пользователь ОС**: useradd probackup --gid postgres --no-user-group.

**Comment by gsmol** [comment]
Задачка на эту фичу уже есть
https://github.com/postgrespro/pg_probackup/issues/333
