### ISSUE TITLE
Backup from replica

### ISSUE THREAD

**Issue by windowsisnotos** [postgrespro/pg_probackup#47]
Hello! How can I backup from replica? I configured max_wal_senders and hot_standby on the replica. Configured on replica and master in pg_hba.conf:
host replication postgres 0.0.0.0/0 trust
On the master included full_page_writes.

When trying to backup from a replica with the command:
pg_probackup backup -B / data / pgsql / backup --instance pgsql-02 -b FULL -j 4 --master-host = pgsql-02 --master-db = postgres --master-user = postgres --master-port = 5432

I get the error message:

ERROR: WAL segment 000000020000000400000063 could not be archived in 300 seconds

If I specify the IP instead of the name in --master-host, the program will ask for the password forever (although I successfully connect from this machine using psql).

If I delete recovery.conf and run the command:
 pg_probackup backup -B / data / pgsql / backup --instance pgsql-02 -b FULL -j 4
The backup will be successfully created.

archive_command on the replica and on the wizard (at the moment backup is configured on the master):

/usr/pgpro-9.6/bin/pg_probackup archive-push -B / data / pgsql / backup --instance pgsql-02 --wal-file-path% p --wal-file-name% f

How should I set up the server in order to successfully make a backup from the replica?

**Comment by gsmol** [comment]
Hello!
What version do you use?
Do you plan to do autonomous backups or archive backups?

**Comment by windowsisnotos** [comment]
pg_probackup 2.0.0

**Comment by gsmol** [comment]
I strongly suggest you to upgrade to a latest 2.0.26 version, there are numerous bugfixes between 2.0.0 and 2.0.26.
Is it possible solution for you?

**Comment by windowsisnotos** [comment]
I managed to make a backup with the command:
pg_probackup backup -B /data/pgsq/ backup --instance pgsql-02 -b FULL --stream -j 4 --master-host=pgsql-02 --master-db=postgres --master-user=postgres

Can I download a binary version of pg_probackup version 2.0.26 somewhere?

**Comment by gsmol** [comment]
Are you using Postgrespro Standart or vanilla postgres?

**Comment by windowsisnotos** [comment]
Sorry, I backed up the local database (not replicas). The previous comment is not valid.

I use Postgrespro Standart.

**Comment by gsmol** [comment]
Can you, please, provide OS version and PostgresPro Standart version?

**Comment by windowsisnotos** [comment]
CentOS 7.3
PostgreSQL 9.6.3

**Comment by gsmol** [comment]
I will try to provide a fresh package for you today.

**Comment by gsmol** [comment]
Done:
https://oc.postgrespro.ru/index.php/s/WKK3MWzKH4ZNenA
On the next week I will orginize separate repo for pg_probackup for Postgrespro Standart.

**Comment by windowsisnotos** [comment]
I installed a new version of pg_probackup.
/bin/pg_probackup-std-9.6 version:
pg_probackup-std-9.6 2.0.26 (Postgres Pro 9.6.11.1 standard)
This did not change the situation.

ERROR: Switched WAL segment 00000004000000070000009A could not be archived in 300 seconds

Tell me, what are the requirements for creating a backup copy of the replica? Perhaps my servers are misconfigured?

**Comment by gsmol** [comment]
By default pg_probackup take backup in ARCHIVE mode, which rely on continuous archiving to be setup via archive_command:
https://postgrespro.com/docs/enterprise/9.6/app-pgprobackup#setting-up-archive-backups
Was it your intention or you want to make autonomous backups?
https://postgrespro.com/docs/enterprise/9.6/app-pgprobackup#autonomous-backups
If so, use --stream option

**Comment by windowsisnotos** [comment]
The above settings have already been made.

When using backup_mode FULL and using the --stream option, a backup is created successfully.
When using backup_mode PAGE and using the --stream option (and without it), the backup will fail:
<pre>
ERROR: Switched WAL segment 00000004000000070000009E could not be archived in 300 seconds.
</pre>

For me it is important to be able to PITR recovery.

**Comment by gsmol** [comment]
Hm, looks like there is a lapse in documentation. For replica you should set:
`archive_mode = 'always'`
to allow archiving on replica.
As you are using archiving, you don`t need to use --stream option.

**Comment by windowsisnotos** [comment]
I set archive_mode to always, it did not fix the problem.
Prompt, replicas should use a common archive directory?
At the moment, the replica and the wizard have different archive directories.

**Comment by gsmol** [comment]
Hm, can you lookup postgresql log there are any errors with archiving?
You can use the same directory, archive-push is smart and compares checksumms if pushed file already present in archive. But isn`t it simpler to enable archiving only on replica?

**Comment by windowsisnotos** [comment]
PostgreSQL log:
<pre>
< 2019-02-20 05:46:15.555 MSK >LOG:  replication terminated by primary server
< 2019-02-20 05:46:15.555 MSK >DETAIL:  End of WAL reached on timeline 4 at 8/B0000098.
< 2019-02-20 05:46:15.555 MSK >FATAL:  could not send end-of-streaming message to primary: no COPY in progress

< 2019-02-20 05:46:15.564 MSK >LOG:  invalid resource manager ID 39 at 8/B0000098
< 2019-02-20 05:46:15.622 MSK >FATAL:  could not connect to the primary server: server closed the connection unexpectedly
                This probably means the server terminated abnormally
                before or while processing the request.

< 2019-02-20 05:46:20.628 MSK >LOG:  started streaming WAL from primary at 8/B0000000 on timeline 4

</pre>

**Comment by windowsisnotos** [comment]
I recreated the replica and set it up. After executing the command:
/bin/pg_probackup-std-9.6 backup -B / data / pgsql / backup --instance pgsql-02 -b FULL -j 4

Pg_probackup log:
<pre>
INFO: Backup start, pg_probackup version: 2.0.26, backup ID: PN7KMJ, backup mode: full, instance: pgsql-02, stream: false, remote: false
WARNING: Update your ptrack to the version 1.5 or upper. Current version is 1.2
INFO: Start transfering data files
INFO: Data files are transfered
INFO: wait for pg_stop_backup()
INFO: pg_stop backup() successfully executed
INFO: Wait for LSN 8/EC010538 in archived WAL segment /data/pgsql/backup/wal/test-pgsql-02/0000000400000008000000EC
ERROR: Switched WAL segment 0000000400000008000000EC could not be archived in 300 seconds
WARNING: Backup PN7KMJ is running, setting its status to ERROR
</pre>

PostgreSQL log:
<pre>
< 2019-02-20 08:01:22.715 MSK >LOG:  database system was shut down in recovery at 2019-02-20 08:01:21 MSK
< 2019-02-20 08:01:22.715 MSK >LOG:  entering standby mode
< 2019-02-20 08:01:22.719 MSK >LOG:  redo starts at 8/EC00C920
< 2019-02-20 08:01:22.720 MSK >LOG:  consistent recovery state reached at 8/EC010538
< 2019-02-20 08:01:22.720 MSK >LOG:  record with incorrect prev-link 2D/4D00000A at 8/EC010538
< 2019-02-20 08:01:22.721 MSK >LOG:  database system is ready to accept read only connections
< 2019-02-20 08:01:22.780 MSK >LOG:  started streaming WAL from primary at 8/EC000000 on timeline 4
</pre>

**Comment by gsmol** [comment]
I think, I get it.
pg_probackup checks that all WAL records, needed for successfull recovery, are present. On master it is easy as pg_start_backup() and pg_stop_backup do switch_xlog() so segments needed by backup are send to archive. But on replica it is impossible, so half-empty segments like 0000000400000008000000EC will be send to archive only when replica streams from master enough WAL to fill it fully. On busy PostgreSQL instanses, where master constantly produce large amount of WAL, it is not a problem. But on cold instances it is a problem.
There are several way deal with it:
1) simplest way: always use --stream option when taking a backups from replica. It will produce
2) set archive_timeout option on master lower than archive_timeout option in pg_probackup. It will force master to send half-empty segments to archive.
3) use pg_receivexlog for streaming WAL to archive instead of archive_command. pg_receivexlog has several advantages over archive_command, but it will requiare demonizing and monitoring. If you choose this approuch, I will provide you with systemd unit file.

**Comment by gsmol** [comment]
Do you need any additional help or we can close this issue?

**Comment by windowsisnotos** [comment]
I correctly understood that in this case I can only perform a full backup?

**Comment by gsmol** [comment]
Of course not, you can perform all backup modes, even PAGE as you have an enabled archiving(you just have to figure a way to deal with cold replica)

**Comment by gsmol** [comment]
Do you have any more questions?
