### ISSUE TITLE
Поддержка group access

### ISSUE THREAD

**Issue by Andreev-AV** [postgrespro/pg_probackup#472]
Доброй ночи.

Планируется ли в ближайшее время включение полноценной поддержка group access?

 @pg_probackup.h:

/* Directory/File permission */
#define DIR_PERMISSION		(0700)
#define FILE_PERMISSION		(0600)

**Comment by gsmol** [comment]
Добрый день!
permission mask сейчас захардкожена, да.
Уже есть задача по этой теме, рассмотрим возможность поднять ей приоритет.
https://github.com/postgrespro/pg_probackup/issues/333
