### ISSUE TITLE
параметр --backup-pg-log для PostgreSQL с версии 10

### ISSUE THREAD

**Issue by triwada** [postgrespro/pg_probackup#50]
параметр --backup-pg-log срабатывает, если есть значение log_directory='pg_log'. В случае, если параметр был переопределен на другое значение (а в PostgreSQL 10 по умолчанию ='log'), то в backup попадает содержимое каталога log_directory независимо от значения --backup-pg-log

**Comment by gsmol** [comment]
Да, действительно.
Спасибо за фидбэк, будем исправлять.

**Comment by gsmol** [comment]
Исправлено в 2ce874c557435.
Выйдет в рамках релиза 2.0.27
