### ISSUE TITLE
merge всех бэкапов

### ISSUE THREAD

**Issue by ykurenkov** [postgrespro/pg_probackup#51]
Возможно ли реализовать возможность мержить последний инкрементальный бэкап, если явно не указан -i ид_резервной_копии, Например:

`pg_probackup merge -B каталог_копий --instance имя_экземпляра`

выполнит merge всех имеющихся инкрементальных бэкапов.

**Comment by gsmol** [comment]
С нашей стороны предпочтительно, чтобы юзер явно(!) указывал, какой бэкап мержить. Кроме того, даже с флагом "схлопни всю цепочку" все равно потребует как-то указывать - а какую именно цепочку схлопывать, т.к. сейчас у одного FULL бэкапа теоретически может быть несколько цепочек инкрементальных бэкапов.

**Comment by za-arthur** [comment]
Также может быть несколько FULL бекапов и у каждого свой список инкрементальных бекапов.

**Comment by ykurenkov** [comment]
А как такое ветвление от FULL можно получить?

**Comment by gsmol** [comment]
> Также может быть несколько FULL бекапов и у каждого свой список инкрементальных бекапов.

C этим мы худо-бедно могли бы разобраться

> А как такое ветвление от FULL можно получить?

Например, закорраптить инкрементальный бэкап, сделать новый инкрементальный бэкап, после чего первый бэкап "починить" и ревалидировать.

**Comment by ykurenkov** [comment]
> закорраптить инкрементальный бэкап, сделать новый инкрементальный бэкап, после чего первый бэкап "починить"

Какой занимательный кейс! И зачем чинить убитое? Не, я могу чего-то не знать.

**Comment by gsmol** [comment]
А это может произойти прозрачно для юзера. Например, у него настроена полуночная автоматическая валидация всех бэкапов и сразу бэкап. В понедельник валидация пометила некий инкрементальный бэкап как CORRUPT и сразу сделала бэкап в новой цепочке, во вторник она же пришла его ревалидировать и он "починился"

**Comment by ykurenkov** [comment]
Прямое нарушение пространственно-верменного континуума, о котором предупреждал доктор Эммет Браун :)

**Comment by gsmol** [comment]
К счастью, нам для этого не нужно 1.21 гигаватт
