### ISSUE TITLE
remote backup issue

### ISSUE THREAD

**Issue by hunterhuang8810** [postgrespro/pg_probackup#516]
Hi Expert,
I'm using pg_probackup backup pg database via remote mode, and got issue as below:
[root@***.rds-backup-worker.sgp hunter-pg-0719]# pg_probackup-12  backup -B /home/pg_backup --instance hunter-pg-0719 -b full  -p 54322 -d postgres -U backup --log-level-file=verbose  --remote-user=postgres --remote-host=*** --remote-port=18822
INFO: Backup start, pg_probackup version: 2.5.5, instance: hunter-pg-0719, backup ID: RG3DRX, backup mode: FULL, wal mode: ARCHIVE, remote: true, compress-algorithm: none, compress-level: 1
Password for user backup: 
pg_probackup-12: symbol lookup error: pg_probackup-12: undefined symbol: PQconninfo
[root@***.rds-backup-worker.sgp hunter-pg-0719]# 

could you  help to check?

pg_probackup-12 2.5.5 (PostgreSQL 12.9)

postgresql version 12.5

**Comment by fukanchik** [comment]
@1142255791  Make sure you use an appropriate version of pg_probackup for your version of postgres.

**Comment by 1142255791** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by 1142255791** [comment]
> @1142255791 Make sure you use an appropriate version of pg_probackup for your version of postgres.
The version is consistent, and the reason for the remote backup failure is due to the inconsistency between the libpq.so file and the version of my pg_probackup.

**Comment by 1142255791** [comment]
@fukanchik The version is consistent, and the reason for the remote backup failure is due to the inconsistency between the libpq.so file and the version of my pg_probackup.
