### ISSUE TITLE
Allow Backups to skip backup validation

### ISSUE THREAD

**Issue by krlatter** [postgrespro/pg_probackup#52]
Can you add an option to allow skipping backup validation following a backup, and simply leave the backup in the state DONE? I still want to perform block validation during the backup, but I can't always afford the second pass on the completed backup files.

This will be helpful for very large databases where the backups are placed on significantly slower storage where we may choose to perform the validate at a later time.

**Comment by gsmol** [comment]
Sure, created PR:
https://github.com/postgrespro/pg_probackup/pull/53

**Comment by gsmol** [comment]
Merged.
Will be released on this week, I hope.

**Comment by gsmol** [comment]
@krlatter, requested feature is available in 2.1.1 release:
https://github.com/postgrespro/pg_probackup/releases/tag/2.1.1
Packages are available in repository.

Can we close this issue?

**Comment by krlatter** [comment]
@gsmol This is great! Thank you so much! Ready to close this issue.
