### ISSUE TITLE
Vanilla PostgreSQL должен быть скомпилирован с ptrack patch или может использовать как опция? 

### ISSUE THREAD

**Issue by patsevanton** [postgrespro/pg_probackup#54]
Спасибо за pg_probackup.

```
PTRACK backup support provided via following options:
vanilla PostgreSQL compiled with ptrack patch. Currently there are patches for PostgreSQL 9.6 and PostgreSQL 10
```

Vanilla PostgreSQL должен быть скомпилирован с ptrack patch или может использовать как опция?

**Comment by za-arthur** [comment]
Добрый день.
Если вы хотите делать ptrack бекапы, то нужен PostgreSQL, собранный с помощью патча ptrack.
Если вы не будете ptrack использовать, то патч не обязателен.

**Comment by patsevanton** [comment]
Думаю стоит это подробнее описать. 
Спасибо.
