### ISSUE TITLE
Is pg_probackup-15 not available yet?

### ISSUE THREAD

**Issue by sms1222** [postgrespro/pg_probackup#558]
Hi.

Is pg_probackup-15 not available yet??
When is pg_probackup-15 available?

Thank you.

**Comment by daniel-95** [comment]
Hi!

The compatibility with the PostgreSQL 15 is going to be published in the upcoming 2.5.9 release.

**Comment by sms1222** [comment]
Thank you for reply.

**Comment by sgrinko** [comment]
@Burus for a long time as version 2.5.10 came out
But the assemblies in the repository `https: // repo.postgrespro.ru/pg_probackup` is still not ...
Can you name the approximate period?

**Comment by sgrinko** [comment]
@funny-falcon for a long time as version 2.5.10 came out
But the assemblies in the repository https: // repo.postgrespro.ru/pg_probackup is still not ...
Can you name the approximate period?

**Comment by kulaginm** [comment]
@sgrinko 2.5.10 is buggy and will never be released.

**Comment by sgrinko** [comment]
Thank you, we are waiting for the next release

**Comment by Burus** [comment]
@sgrinko until 8 december we plan release 2.5.11 with minor bug fixes for the 15 version.

**Comment by sgrinko** [comment]
Thank you for reply.

**Comment by Burus** [comment]
Ready to use and fully tested.

**Comment by sms1222** [comment]
Thank you so much for your work.
