### ISSUE TITLE
[feature] Cleanup on ERROR

### ISSUE THREAD

**Issue by gsmol** [postgrespro/pg_probackup#57]
It would be good to have some flag, that will enable deleting already copied data files, if backup has failed with ERROR. Proposed name: '--cleanup-on-error'.
So ERROR backup will still be present in backup_catalog(but without data files) and cleaned up by retention in due time.

**Comment by stepansantalov** [comment]
Nice feature to have

**Comment by gsmol** [comment]
Approach proposed in https://github.com/postgrespro/pg_probackup/issues/120 is more general.
