### ISSUE TITLE
Ошибка ERROR: Restore destination is not empty

### ISSUE THREAD

**Issue by Mogaba** [postgrespro/pg_probackup#574]
Изучаю pg_probackup, пробую бэкапить/восстановить базу по документации:
https://postgrespro.github.io/pg_probackup/

Делаю бэкап командой:
`pg_probackup-12 backup -B /opt/pgbackup --instance sber -b FULL --stream --temp-slot -U pgbackup -d sber`

Все проходит успешно, далее пытаюсь восстановить:
`pg_probackup-12 restore -B /opt/pgbackup --instance sber -i RLSY9Y`

Выводится ошибка:
`ERROR: Restore destination is not empty: "/var/lib/postgresql/12/main"`

Удаляю все из каталога "/var/lib/postgresql/12/main", после этого такая ошибка:
```
ERROR: Cannot open restore target file "/var/lib/postgresql/12/main/PG_VERSION": Permission denied
ERROR: Backup files restoring failed. Transfered bytes: 104kB, time elapsed: 0
```
Подскажите, пожалуйста, новичку, в чем проблема.
ОС: Ubuntu 20.04
PostgreSQL: 12

**Comment by daniel-95** [comment]
Добрый день.
Если у вас запущен постгрес, то перед восстановлением остановите его. Также вам нужны права на директорию /var/lib/postgresql/12/main, с правами может быть проблема, если вы запустили постгрес с sudo

**Comment by daniel-95** [comment]
Вообще, конечно, не важно, но на практике обычно из соображений безопасности (не только для бекапирования, а вообще для самых разных задач) создают пользователей с необходимыми для работы правами, и не более того. В идеале - бекапить и восстанавливать одним и тем же пользователем.
