### ISSUE TITLE
Сообщения WARNING: File 'pg_multixact/...' was stored as non-datafile, but looks like it is

### ISSUE THREAD

**Issue by xinferum** [postgrespro/pg_probackup#585]
Добрый день.

PostgreSQL 15.1 (ванильный), pg_probackup-15 2.5.11.

Мы на одном из тестовых контуров, с довольно нагруженной бд, столкнулись с тем, что после обновления с 14-й на 15-ю мажорную версии PostgreSQL во время проверочного ручного запуска бекапа начали сыпаться сообщения следующего вида:
```
WARNING: File 'pg_multixact/members/3994' was stored as non-datafile, but looks like it is
WARNING: File 'pg_multixact/members/3995' was stored as non-datafile, but looks like it is
WARNING: File 'pg_multixact/members/3996' was stored as non-datafile, but looks like it is
WARNING: File 'pg_multixact/members/3997' was stored as non-datafile, but looks like it is
WARNING: File 'pg_multixact/members/3998' was stored as non-datafile, but looks like it is
WARNING: File 'pg_multixact/members/3999' was stored as non-datafile, but looks like it is
WARNING: File 'pg_multixact/offsets/1064' was stored as non-datafile, but looks like it is
WARNING: File 'pg_multixact/offsets/1065' was stored as non-datafile, but looks like it is
WARNING: File 'pg_multixact/offsets/1066' was stored as non-datafile, but looks like it is
WARNING: File 'pg_multixact/offsets/1067' was stored as non-datafile, but looks like it is
WARNING: File 'pg_multixact/offsets/1068' was stored as non-datafile, but looks like it is
WARNING: File 'pg_multixact/offsets/1069' was stored as non-datafile, but looks like it is
WARNING: File 'pg_multixact/offsets/1070' was stored as non-datafile, but looks like it is
```
То есть pg_probackup стал писать WARNING на каждый файл из директорий pg_multixact/members/ и pg_multixact/offsets/.
Проверили по логам - на PostgreSQL 14 тоже возникали такие сообщения с момента обновления pg_probackup на версию 2.5.11, до этого была установлена 2.5.8 и с ней в логе таких WARNING нет. 

Поискал по коду - начиная с версии 2.5.11 был введен следующий код проверки (впервые он появляется еще в 2.5.10, но эта версия, насколько мне известно, в релиз не была выпущена):
https://github.com/postgrespro/pg_probackup/blob/b90273fe143c4b2d2d198f2e29b61547c316a561/src/catalog.c#L1145-L1161

Подскажите, что конкретно для нас должен означать этот WARNING и корректно ли в данном случае поведение самого pg_probackup? Файлы принадлежат кластеру postgres и они корректны.

Спасибо.

**Comment by funny-falcon** [comment]
Косяк...

**Comment by funny-falcon** [comment]
А нет, опасности нет. Просто неприятный ворнинг.

**Comment by sgrinko** [comment]
Очень надеемся, что в следующей версии это поправите :)

**Comment by funny-falcon** [comment]
Помержил в REL_2_5
