### ISSUE TITLE
Does this conditional branch have any special meaning？

### ISSUE THREAD

**Issue by zxbzswxr** [postgrespro/pg_probackup#591]
https://github.com/postgrespro/pg_probackup/blob/7792b98a998706ca5e6fb203e1b07384eec6d9cc/src/merge.c#L339-L341

what if we rewrite it as 
if(full_backup->status == BACKUP_STATUS_MERGED && dest_backup->start_time != full_backup->merge_dest_backup)  
......

**Comment by zxbzswxr** [comment]
> Thanks, for reporting this! We suspect it should be MERGED+MERGING. Will be fixed in one of the next releases.

so, it will be 
 if ((full_backup->status == BACKUP_STATUS_MERGED || 
 	full_backup->status == BACKUP_STATUS_MERGING) && 
 	dest_backup->start_time != full_backup->merge_dest_backup)  
.....  ?
that's all ??

**Comment by fukanchik** [comment]
Yes

**Comment by zxbzswxr** [comment]
> Yes

Thank you.
