### ISSUE TITLE
Использование pg_probackup в удалённом режиме

### ISSUE THREAD

**Issue by ion70** [postgrespro/pg_probackup#593]
Добрый день!
Возможно ли использование pg_probackup в удалённом режиме, 
если отличаются версии СУБД и соответственно версии pg_probackup (например между  PostgreSQL 11 и Postgres PRO 13)?

**Comment by Burus** [comment]
Добрый день. Можно использовать pg_probackup только для конкретной мажорной версии СУБД. 
Привмер: 11 версия СУБД с pg_probackup для 11 версии. 
Проверить совместимость можно командой pg_probackup -- version.

pg_probackup [можно использовать в remote режиме. ](https://postgrespro.github.io/pg_probackup/#pbk-configuring-the-remote-mode)
