### ISSUE TITLE
version for 22.04.1 LTS (Jammy Jellyfish)

### ISSUE THREAD

**Issue by Nikitin-Alexandr** [postgrespro/pg_probackup#594]
Hello! Do you have pg_probackup.deb for Ubuntu 22.04.1 LTS (Jammy Jellyfish)? 

E: The repository 'https://repo.postgrespro.ru/pg_probackup/deb jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by fukanchik** [comment]
It will be included into the next releases. Release 2.5.12 should be available in a few business days. Release 2.6.2 might take longer.

**Comment by Burus** [comment]
Ready for release.
