### ISSUE TITLE
add-instance doesn't save "remote-.." instance parameters

### ISSUE THREAD

**Issue by bomuva** [postgrespro/pg_probackup#599]
pg_probackup-15 add-instance 
doesn't  save "remote-.." instance parameters in config, but set-config command does

**Comment by daniel-95** [comment]
Could you please share the command as it was executed and full output log?

**Comment by bomuva** [comment]
$ pg_probackup-15 add-instance --backup-path=/mnt/backupdir --pgdata=/var/lib/pgsql/15/data --instance=prod-adhoc-instance --pguser=backup --pgdatabase=backupdb --retention-redundancy=2 --retention-window=14 --compress-algorithm=zlib --compress-algorithm=zlib --compress-level=1 --remote-host=10.122.3.61 --remote-user=postgres
`INFO: Instance 'prod-adhoc-instance' successfully initialized`

$ pg_probackup-15 show-config --backup-path=/mnt/backupdir --instance=prod-adhoc-instance
```
# Backup instance information
pgdata = /var/lib/pgsql/15/data
system-identifier = 7225663664781777115
xlog-seg-size = 16777216
# Connection parameters
pgdatabase = backupdb
pguser = backup
# Replica parameters
replica-timeout = 5min
# Archive parameters
archive-timeout = 5min
# Logging parameters
log-level-console = INFO
log-level-file = OFF
log-format-console = PLAIN
log-format-file = PLAIN
log-filename = pg_probackup.log
log-rotation-size = 0TB
log-rotation-age = 0d
# Retention parameters
retention-redundancy = 2
retention-window = 14
wal-depth = 0
# Compression parameters
compress-algorithm = zlib
compress-level = 1
# Remote access parameters
remote-proto = ssh

```

**Comment by bomuva** [comment]
$ pg_probackup-15 set-config --backup-path=/mnt/backupdir --instance=prod-adhoc-instance --remote-host=10.122.3.61 --remote-user=postgres
pg_probackup-15 show-config --backup-path=/mnt/backupdir --instance=prod-adhoc-instance

```
# Backup instance information
pgdata = /var/lib/pgsql/15/data
system-identifier = 7225663664781777115
xlog-seg-size = 16777216
# Connection parameters
pgdatabase = backupdb
pghost = 10.122.3.61
pguser = backup
# Replica parameters
replica-timeout = 5min
# Archive parameters
archive-timeout = 5min
# Logging parameters
log-level-console = INFO
log-level-file = OFF
log-format-console = PLAIN
log-format-file = PLAIN
log-filename = pg_probackup.log
log-rotation-size = 0TB
log-rotation-age = 0d
# Retention parameters
retention-redundancy = 2
retention-window = 14
wal-depth = 0
# Compression parameters
compress-algorithm = zlib
compress-level = 1
# Remote access parameters
remote-proto = ssh
remote-host = 10.122.3.61
remote-user = postgres

```

**Comment by bomuva** [comment]
remote-host and remote-user are set only via set-config

**Comment by MetalDream666** [comment]
#504
