### ISSUE TITLE
Retention policy

### ISSUE THREAD

**Issue by stalkerg** [postgrespro/pg_probackup#6]
- [ ] recycle
- [ ] changes in the retention period
- [ ] meta information about period
- [ ] special command for changes retention period

We want set up special rules for each backup for automatic removal.

**Comment by select-artur** [comment]
Retention policy is done by `retention purge` command with `redundancy` and `window` parameters.

**Comment by stalkerg** [comment]
I think test does not check all cases.

**Comment by select-artur** [comment]
Retention cases? Will think about it.

**Comment by select-artur** [comment]
Tests were added.
