### ISSUE TITLE
[feature] zratio

### ISSUE THREAD

**Issue by gsmol** [postgrespro/pg_probackup#60]
During backup pg_probackup must calculate uncompressed size and store it in backup metadata.
It will allow to calculate compression ratio for every individual backup.
Also it would be nice to calculate and pgdata size, it will allow user to see a profit from incremental backup regardless of using compression

**Comment by gsmol** [comment]
new backup attributes:
1. pgdata_size
2. read_size
3. uncompressed_size

**Comment by gsmol** [comment]
Example:
```
BACKUP INSTANCE 'node'
=====================================================================================================================================
 Instance  Version  ID      Recovery Time           Mode   WAL Mode  TLI  Time    Data   WAL  Zratio   Start LSN    Stop LSN  Status 
=====================================================================================================================================
 node      11       PYE6CQ  2019-09-25 17:46:22+03  FULL   STREAM    1/0   21s   111MB  16MB    9.66  1/6E000028  1/6E000198  DONE   
 node      11       PYE64C  2019-09-25 17:41:29+03  FULL   STREAM    1/0   31s  1070MB  32MB    1.00  1/6C000028  1/6C000198  DONE 
```

**Comment by gsmol** [comment]
backup.control:
```
#Configuration
backup-mode = FULL
stream = true
compress-alg = zlib
compress-level = 1
from-replica = false

#Compatibility
block-size = 8192
xlog-block-size = 8192
checksum-version = 1
program-version = 2.1.5
server-version = 11

#Result backup info
timelineid = 1
start-lsn = 1/6E000028
stop-lsn = 1/6E000198
start-time = '2019-09-25 17:46:02+03'
end-time = '2019-09-25 17:46:23+03'
recovery-xid = 587
recovery-time = '2019-09-25 17:46:22+03'
data-bytes = 115972555
wal-bytes = 16777216
uncompress-bytes = 1120622355
status = DONE
primary_conninfo = 'user=backup passfile=/home/gsmol/.pgpass port=31738 sslmode=disable sslcompression=0 target_session_attrs=any'
```

**Comment by gsmol** [comment]
TODO: documentation, pgdata_size

**Comment by gsmol** [comment]
pgdata_size is done.

**Comment by alubennikova** [comment]
1)
 +                        * Size of WAL files in 'pg_wal' is counted separately
Do you mean "wal archive" here?
pg_wal is a part of pgdata, so I think its size must be included in pgdata-size

2) 
-                       /* update backup_content.control every 10 seconds */
-                       if ((difftime(time(NULL), prev_time)) > 10)
+                       /* update backup_content.control every 15 seconds */
+                       if ((difftime(time(NULL), prev_time)) > 15)

Is there any specific reason for this change?

**Comment by gsmol** [comment]
> Do you mean "wal archive" here?
> 
No, I mean  'pg_wal/pg_xlog' in pgdata directory in case of STREAM backup.

> pg_wal is a part of pgdata, so I think its size must be included in pgdata-size
>
In some cases it would be good to know exact size of data files and exact size of WAL files.
For example, we have a very busy system that generates a lot of WAL, but actual data changes are very small, like in taxi services with COPY+TRUNCATE load.
We take DELTA backup with compression and it may comes that streamed WAL takes 50% of total backup size. It think that user must know about it.

**Comment by gsmol** [comment]
> Is there any specific reason for this change?

Hmpf, nope. Lets trash it.

**Comment by alubennikova** [comment]
> > Do you mean "wal archive" here?
> 
> No, I mean 'pg_wal/pg_xlog' in pgdata directory in case of STREAM backup.
> 
> > pg_wal is a part of pgdata, so I think its size must be included in pgdata-size
> 
> In some cases it would be good to know exact size of data files and exact size of WAL files.
> For example, we have a very busy system that generates a lot of WAL, but actual data changes are very small, like in taxi services with COPY+TRUNCATE load.
> We take DELTA backup with compression and it may comes that streamed WAL takes 50% of total backup size. It think that user must know about it.

Fair enough. Please, mention it in the documentation.

**Comment by gsmol** [comment]
Ok

**Comment by gsmol** [comment]
Pushed documentation update.

**Comment by alubennikova** [comment]
Everything is fine, except for several typos in documentation.

1) ```+- WAL — the size of WAL files required to reply by PostgreSQL to reach consistency.```
Is it a compressed size or not? "reply by" - is it a typo? Please, fix it.

2) ```+Detailed output has some additional attributes:```
'some' is excessive here

```+- primary_conninfo — libpq conninfo used for connection to PostgreSQL cluster during backup. Password is not included.```
The password

**Comment by gsmol** [comment]
Fixed.

**Comment by gsmol** [comment]
Merged.
