### ISSUE TITLE
Создание реплики из мастер

### ISSUE THREAD

**Issue by hocuspocus0** [postgrespro/pg_probackup#604]
pg_probackup имеет возможность создавать реплику из бэкапа, есть ли возможность создавать реплики на прямую из мастера?  в документации не увидел упоминания об этом, данный функционал полезен для параллельного создания реплики, т.к. pg_basebackup не имеет возможность делать это параллельно.

**Comment by Roman2dot0** [comment]
Catchup, прописать conninfo и создать standby.signal.

**Comment by MetalDream666** [comment]
Этот функционал выполняет команда catchup. [Документация команды](https://postgrespro.github.io/pg_probackup/#pbk-creating-backup-to-catchup) на английском. [Документация](https://postgrespro.ru/docs/postgrespro/15/app-pgprobackup#PBK-CREATING-BACKUP-TO-CATCHUP) на русском.

Пример команды (больше примеров в документации):
`./pg_probackup catchup --source-pgdata=/home/sofia/install15/bin/test1 --destination-pgdata=/home/sofia/install15/bin/test1_catchup -d mydb -p 5432 -U sofia -b FULL --stream`
