### ISSUE TITLE
pg_probackup support for Postgres running on Windows server. support for Postgres running on Windows server.

### ISSUE THREAD

**Issue by maheshetty20** [postgrespro/pg_probackup#610]
Hello,
I have below versions of Pg running on Windows server.
V11.
V15.
V16.

Wanted to know below:
1) Does pg_probackup supports taking backup of PG running on windows system.
2) Is it safe to use pg_probackup for production system.

**Comment by Burus** [comment]
Hello, yes. We have Windows version for all PostgreSQL version. Asap we will release 2.5.13 with PostgreSQL 16 support. Its safe and secure.

**Comment by maheshetty20** [comment]
Thanks for your reply. One last question when are expecting the release 2.5.13 with PostgreSQL 16 support.

**Comment by Burus** [comment]
Today)
