### ISSUE TITLE
Debian 12 support

### ISSUE THREAD

**Issue by vut12** [postgrespro/pg_probackup#613]
Hello. Can you add package for Debian bookworm ?

**Comment by asavchkov** [comment]
Yes, it should be available in a couple of weeks.

**Comment by asavchkov** [comment]
Pg_probackup 2.5.13 packages for Debian 12.2 (bookworm) are available now. Check the i[nstallation instructions](https://postgrespro.github.io/pg_probackup/#pbk-install-deb) for assistance.
