### ISSUE TITLE
Проблем с запуском  full pg_probackup-16 

### ISSUE THREAD

**Issue by AndreyMoiseev84** [postgrespro/pg_probackup#619]
Имеем  Debian 11 + postgrespro-1c-16 
Установил g_probackup-16  добавил хранилище и инстансе в нём. 
Пытаюсь запустить создание фулл бэкапа, получаю следующую ошибку 

postgres@PGAUTO:~$ pg_probackup-16 backup --threads=3 -B /backup_pg --instance backup -b FULL --stream --compress
WARNING: Control file "/backup_pg/backups/backup/S93KQV/backup.control" doesn't exist
WARNING: Control file "/backup_pg/backups/backup/S93JUP/backup.control" doesn't exist
INFO: Backup start, pg_probackup version: 2.5.13, instance: backup, backup ID: S93LBZ, backup mode: FULL, wal mode: STREAM, remote: false, compress-algorithm: zlib, compress-level: 1
ERROR: could not connect to database postgres: не удалось подключиться к серверу: Нет такого файла или каталога
        Он действительно работает локально и принимает
        соединения через Unix-сокет "/var/run/postgresql/.s.PGSQL.5432"?

Postgres pro работает

root@PGAUTO:~# systemctl status postgrespro-1c-16.service
● postgrespro-1c-16.service - Postgres Pro 1c 16 database server
     Loaded: loaded (/lib/systemd/system/postgrespro-1c-16.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-02-19 11:12:21 MSK; 2h 5min ago
    Process: 372 ExecStartPre=/opt/pgpro/1c-16/bin/check-db-dir ${PGDATA} (code=exited, status=0/SUCCESS)
   Main PID: 384 (postgres)
      Tasks: 10 (limit: 23394)
     Memory: 2.3G
        CPU: 11min 6.465s
     CGroup: /system.slice/postgrespro-1c-16.service
             ├─ 384 /opt/pgpro/1c-16/bin/postgres -D /var/lib/pgpro/1c-16/data
             ├─ 451 postgres: logger
             ├─ 452 postgres: checkpointer
             ├─ 453 postgres: background writer
             ├─ 455 postgres: walwriter
             ├─ 456 postgres: autovacuum launcher
             ├─ 457 postgres: logical replication launcher
             ├─2137 postgres: postgres auto 192.168.250.110(56752) idle
             ├─2868 postgres: postgres auto 192.168.250.110(60419) idle
             └─2869 postgres: postgres auto 192.168.250.110(60420) idle

фев 19 11:12:20 PGAUTO systemd[1]: Starting Postgres Pro 1c 16 database server...
фев 19 11:12:21 PGAUTO postgres[384]: 2024-02-19 11:12:21.307 MSK [384] СООБЩЕНИЕ:  передача вывода в протокол процессу сбора протоколов
фев 19 11:12:21 PGAUTO postgres[384]: 2024-02-19 11:12:21.307 MSK [384] ПОДСКАЗКА:  В дальнейшем протоколы будут выводиться в каталог "log".
фев 19 11:12:21 PGAUTO systemd[1]: Started Postgres Pro 1c 16 database server.
root@PGAUTO:~#

**Comment by fukanchik** [comment]
Скорее всего у Вас в системе установлен системный пакет libpq. Системный libpq пытается установить соединение с сервером через /var/run, в то время как не-дебиановские постгресы ожидают соединения в /tmp.

Детали (про ваниллу, но и в пгпро то же самое) - https://www.postgresql.org/message-id/21044.1326496507@sss.pgh.pa.us

**Comment by AndreyMoiseev84** [comment]
Спасибо за информацию, насколько я понимаю   Можно сделать так 
В postgresql.con 
Раскоментить и указать нужное значение для  unix_socket_directories
unix_socket_directories = '/var/run/postgresql/'

но почему то после  указания данного параметра перестает стартовать служба postgres 

Job for postgrespro-1c-16.service failed because the control process exited with error code.
See "systemctl status postgrespro-1c-16.service" and "journalctl -xe" for details.

Вопрос в том почему не работает ?

**Comment by fukanchik** [comment]
`journalctl -xe` даст нужную информацию. Скорее всего сокет в /var/run/postgresql уже занят процессом другим постгрес который вы ставили из репозитория debian. Попробуйте сконфигурировать другой номер порта.

**Comment by AndreyMoiseev84** [comment]
> `journalctl -xe` даст нужную информацию. Скорее всего сокет в /var/run/postgresql уже занят процессом другим постгрес который вы ставили из репозитория debian. Попробуйте сконфигурировать другой номер порта.
Это было бы слишком просто ))  Pg установлен только 1 - postgrespro-1c-16

**Comment by fukanchik** [comment]
А что было-то?

**Comment by AndreyMoiseev84** [comment]
> А что было-то?
С упорством достойным лучшего применения пытался указать настройку так 
unix_socket_directories = /var/run/postgresql/  
затем выспался и понял что дичь творю (логи наше все ) )
 root@bakupTest:/var/lib/pgpro/1c-16/data# cat postgresql.conf | grep unix
unix_socket_directories = '/var/run/postgresql/'        # comma-separated list of directories
