### ISSUE TITLE
Windows: Ошибка бэкапа в случае залоченного файла

### ISSUE THREAD

**Issue by ykurenkov** [postgrespro/pg_probackup#62]
```
2019-04-22 23:00:01 RTZ 4 (зима): INFO: Backup start, pg_probackup version: 2.0.27, backup ID: PQDJC1, backup mode: delta, instance: ny1-10, stream: true, remote: false
2019-04-22 23:00:04 RTZ 4 (зима): ERROR: cannot stat file "D:/IBIS_DATA/ny1-10/base/15520165/15522614": Permission denied
2019-04-22 23:00:04 RTZ 4 (зима): WARNING: Backup PQDJC1 is running, setting its status to ERROR
2019-04-22 23:00:04 RTZ 4 (зима): WARNING: backup in progress, stop backup
```

Я не знаю, что делает postgresql, что лочит иногда вот так эксклюзивно файл. Иногда сталкиваюсь с подобным явлением. Под виндой. Бывает, что лочит на несколько дней. Обычно это лечат перезагрузкой, если долго не отпускает. Попадётся мне живьем, надо oid2name посмотреть что это. Соответственно и pg_probackup не может выполнить бэкап.

**Comment by gsmol** [comment]
А сейчас этот файл существует?

**Comment by ykurenkov** [comment]
Сейчас - нет.

**Comment by gsmol** [comment]
А упомянутый лок на несколько дней висит на одном и том же файле?

**Comment by ykurenkov** [comment]
Пару раз такое встречал. Даже было на нескольких файлах. Причем, после рестарта постгреса эти файлы или становились доступны для чтения или переставали существовать. Даже видел один раз такой лок длительностью несколько недель по времени последней записи в файл. Даже в логах ругань autovacuum была на невозможность получить доступ к файлу. Что в них было (талицы, индексы, временные тавлицы) - трудно предположить, но вероятность того, что это обычные таблицы, скорее всего самая низкая у перечисленых.

**Comment by gsmol** [comment]
Вот тут обвиняют в аналогичном поведении антивирус:
https://www.postgresql.org/message-id/flat/9837222c1001310820u4c05a6ccn9aff1d7d3ceb129c%40mail.gmail.com#c4a2799c767cc5a3239edbfa4cdd5ec9

**Comment by ykurenkov** [comment]
Проверил - стандартный Windows Server 2016 без установленного стороннего антивирусного ПО.

**Comment by gsmol** [comment]
Если это решит проблему, то мы напишем об этом в документации.

**Comment by ykurenkov** [comment]
Будем ждать бэкапа со статусом ERROR. Посмотрим в логи.

**Comment by ykurenkov** [comment]
![image](https://user-images.githubusercontent.com/25895491/58007026-08cf7a00-7af2-11e9-889c-abedca2cc2df.png)

Вот, только что произошло. Дата изменения на файле около двух с половиной часов назад. Вот запись из лога:

```
2019-05-20 13:20:11 RTZ 4 (зима): INFO: command: D:\IBIS_ADM\bin\pg_probackup\pg_probackup_5.exe backup -B \\10.20.9.240\Ibis\IBIS_BACKUPS\PGBACKUPS\ --instance ny1-10 --backup-mode=DELTA --skip-block-validation --stream --progress -j 15 
2019-05-20 13:20:11 RTZ 4 (зима): INFO: Backup start, pg_probackup version: 2.0.27, backup ID: PRSN5N, backup mode: delta, instance: ny1-10, stream: true, remote: false
2019-05-20 13:20:16 RTZ 4 (зима): ERROR: cannot stat file "D:/IBIS_DATA/ny1-10/base/15520165/15526327": Permission denied
2019-05-20 13:20:16 RTZ 4 (зима): WARNING: Backup PRSN5N is running, setting its status to ERROR
2019-05-20 13:20:16 RTZ 4 (зима): WARNING: backup in progress, stop backup

```

**Comment by ykurenkov** [comment]
Всё еще...
```
2019-05-20 13:58:07 RTZ 4 (зима): INFO: command: D:\IBIS_ADM\bin\pg_probackup\pg_probackup_5.exe backup -B \\10.20.9.240\Ibis\IBIS_BACKUPS\PGBACKUPS\ --instance ny1-10 --backup-mode=DELTA --skip-block-validation --stream --progress -j 15 
2019-05-20 13:58:07 RTZ 4 (зима): INFO: Backup start, pg_probackup version: 2.0.27, backup ID: PRSOWV, backup mode: delta, instance: ny1-10, stream: true, remote: false
2019-05-20 13:58:13 RTZ 4 (зима): ERROR: cannot stat file "D:/IBIS_DATA/ny1-10/base/15520165/15526327": Permission denied
2019-05-20 13:58:13 RTZ 4 (зима): WARNING: Backup PRSOWV is running, setting its status to ERROR
2019-05-20 13:58:13 RTZ 4 (зима): WARNING: backup in progress, stop backup

```

**Comment by gsmol** [comment]
Давайте попробуем понять, что это за релейшен. Нужно подключиться к базе с oid 15520165, ее легко вычислить с помощью запроса:
`select datname from pg_database where oid = 15520165`

После подключения к ней выполняем запрос:
`select pg_filenode_relation(1663, 15526327);`

**Comment by ykurenkov** [comment]
Хм... А ничего не вернул запрос

```
ny1=# select datname from pg_database where oid = 15520165;
 datname
---------
 ny1
(1 row)

ny1=# select pg_filenode_relation(1663, 15526327);
 pg_filenode_relation
----------------------

(1 row)

ny1=#
```
На всякий случай проверил:

```
ny1=# select dattablespace from pg_database where oid = 15520165;
 dattablespace
---------------
          1663
(1 row)

ny1=#
```

**Comment by gsmol** [comment]
Хм, похоже на удаленный релейшен.
А если сделать CHECKPOINT, он пропадет?

**Comment by ykurenkov** [comment]
Как коррекно его сделать?

**Comment by gsmol** [comment]
в psql вбейте "CHECKPOINT" и enter
Перезагружать не надо.

**Comment by ykurenkov** [comment]
Файл остался.

**Comment by gsmol** [comment]
А нет ли в логе постгреса каких-либо ошибок за последнее время?

**Comment by ykurenkov** [comment]
Есть, но они только касаются синтаксиса и вывода чечез NOTICE.
[postgresql-Mon.log-errors.txt](https://github.com/postgrespro/pg_probackup/files/3197508/postgresql-Mon.log-errors.txt)

**Comment by gsmol** [comment]
А перезагрузка постгреса помогает в этих случаях?

**Comment by ykurenkov** [comment]
Скорее всего - даю Я сейчас не могу его перегрузить :( Сейчас попытаюсь на файл со всех сторон посмотреть.

**Comment by gsmol** [comment]
а какие на него сейчас права?

**Comment by ykurenkov** [comment]
Не пускает к файлу, совсем.
А вот этот процесс.

![image](https://user-images.githubusercontent.com/25895491/58019155-894fa400-7b0d-11e9-9ad3-cd898a5ea212.png)

**Comment by ykurenkov** [comment]
Вот список открытых процессом файлов. Может на какие мысли натолкнёт. 

[pid3816.txt](https://github.com/postgrespro/pg_probackup/files/3197761/pid3816.txt)

**Comment by gsmol** [comment]
А что возвращает:
`select * from pg_stat_activity where pid = 3816`

**Comment by ykurenkov** [comment]
```
  datid   | datname | pid  | usesysid |     usename      |         application_name         | client_addr | client_hostname | client_port |         backend_start         | xact_start |          query_start          |         state_change          | wait_event_type | wait_event | state | backend_xid | backend_xmin |                  query                  |  backend_type  
----------+---------+------+----------+------------------+----------------------------------+-------------+-----------------+-------------+-------------------------------+------------+-------------------------------+-------------------------------+-----------------+------------+-------+-------------+--------------+-----------------------------------------+----------------
 15520165 | ny1     | 3816 | 15325970 | XСТУПНИКОВАНИ--2 | policlinic.exe (1.0.0.19390) 101 | 10.20.42.61 |                 |       63706 | 2019-05-15 08:14:55.685519+05 |            | 2019-05-15 08:14:58.889609+05 | 2019-05-15 08:14:58.890249+05 | Client          | ClientRead | idle  |             |              | SELECT mm.adj_get_value_def($1, $2, $3) | client backend
(1 row)


```

**Comment by gsmol** [comment]
А ваше приложение делает DROP TABLE или DROP INDEX ?

**Comment by ykurenkov** [comment]
> XСТУПНИКОВАНИ--2
У этого пользователя нет таких прав. Временные таблицы считаются? Примерно в районе 10:50 п серверному времени были заменены несколько функций.

**Comment by gsmol** [comment]
А версия PG какая?

**Comment by ykurenkov** [comment]
PgPro 10.6.1
Этот процесс 3816 завершился. Файла, к которому не было доступа сейчас нет.

**Comment by ykurenkov** [comment]
Плановый бэкап из шедулера выполнился нормально. Скорее всего это был удалённый объект. Поэтому он не был показан на момент вызова

 `select pg_filenode_relation(1663, 15526327);`

Вот только почему postgres его "держал" несколько дней? Такое поведение было замечено, кажется, и за ванильными 9.4 и 9.6.

**Comment by gsmol** [comment]
Есть предожение - настроить подробное логирование. Тогда можно будет понять, какие именно действия, а, главное, чьи привели к этому состоянию.

**Comment by gsmol** [comment]
Отбой, кажется, нашли в чем причина.

**Comment by gsmol** [comment]
Открыли соответствующий тред в рассылке:
https://www.postgresql.org/message-id/flat/a9c76882-27c7-9c92-7843-21d5521b70a9%40postgrespro.ru

**Comment by ykurenkov** [comment]
Хорошо, ждём реакции...

**Comment by gsmol** [comment]
В следующем минорном релизе будет фикс.

**Comment by ykurenkov** [comment]
Отлично!

**Comment by gsmol** [comment]
Добавлен тест tests.backup.BackupTest.test_drop_table

**Comment by gsmol** [comment]
В релизе 2.1.3 исправлено.
К вечеру организуем инсталлеры

**Comment by ykurenkov** [comment]
Здорово! Жду... А для Pro-Standard-10 будет?

**Comment by gsmol** [comment]
Будет

**Comment by gsmol** [comment]
Инсталлеры выпустили, закрываем тикет?
