### ISSUE TITLE
[feature] restore optimization

### ISSUE THREAD

**Issue by gsmol** [postgrespro/pg_probackup#63]
Currently, every backup in incremental chain restored in an extremely inefficient way:
```
PAGE (fileA is known to be deleted)
FULL (contain fileA)
```
fileA is still getting copied and then deleted.
So when restoring incremental chain, every backup should have destination backup filelist.

**Comment by za-arthur** [comment]
Pushed into **issue_63** branch. I introduced pgFile->rel_path to easily store relative paths instead of using GetRelativePath(). GetRelativePath() is still is used in the code though.

**Comment by gsmol** [comment]
Are we going to get rid of GetRelativePath() completely?

**Comment by za-arthur** [comment]
Yes, but only in the following patches. New patches shouldn't use GetRelativePath() and maybe someday we'll remove it completely.

**Comment by gsmol** [comment]
Am I correct that GetRelativePath() is still needed when dealing with backups, produced by previous pg_probackup versions?

**Comment by za-arthur** [comment]
No, GetRelativePath() isn't need for backward compatibility, since `path` in `backup_content.control` is relative path.

**Comment by gsmol** [comment]
Oh, right, forgot about it.

**Comment by gsmol** [comment]
Added new test in master 87f28e76fd, additional tests for `external dirs` and `merge` will be added shortly

**Comment by gsmol** [comment]
So this code should not be need, right?
https://github.com/postgrespro/pg_probackup/blob/master/src/restore.c#L453

**Comment by gsmol** [comment]
I`m sorry, wrong branch.

**Comment by gsmol** [comment]
Well, looks like everything is ok.
I think it can be merged to master.
