### ISSUE TITLE
ERROR: Syntax error on include при работе с СУБД PostgresPro standard

### ISSUE THREAD

**Issue by KsanterX** [postgrespro/pg_probackup#636]
При использовании pg_probackup возникает ошибка, если в файле конфигурации СУБД PostgresPro postgresql.conf есть опция include:
`ERROR: Syntax error on /var/lib/pgpro/std-15/data/postgresql.conf:870: include '/var/lib/pgpro/std-15/data/postgresql.conf.d/server.conf'`

Пример команды: /opt/pgpro/std-15/bin/pg_probackup add-instance -B /backup -D /var/lib/pgpro/std-15/data --instance myinstance

Соответствующая часть файла postgresql.conf:
`
include '/var/lib/pgpro/std-14/data/postgresql.conf.d/server.conf'

include '/var/lib/pgpro/std-14/data/postgresql.conf.d/replica.conf'
`
Сами файлы существуют, права корректные и параметры успешно читаются СУБД.

Если убрать include из файла конфигурации и внести настройки непосредственно в файл postgresql.conf, то pg_probackup работает как надо. При этом, таких проблем нет для БД с обычным PostgreSQL, где файлы конфигурации идентичны и тоже включены через include.

Версия pg_probackup: pg_probackup 2.8.0 community (Postgres Pro 15.7.1 standard) (compressions: zlib, pglz, lz4, zstd)
Версия СУБД PostgresPro: 15.7.1

**Comment by Ogurezzz** [comment]
Здравсвуйте, проблема известная. Появилась как раз в 2.8.0. В 2.8.1 сделали workaround (игнор include) в ближайшем релизе 2.8.4 будет уже полноценная поддержка include в pg_probackup.
Обновление до 2.8.1. должно помочь.

**Comment by fukanchik** [comment]
Известная проблема, которая была решена в 2.8.1
