### ISSUE TITLE
[feature] incremental restore

### ISSUE THREAD

**Issue by gsmol** [postgrespro/pg_probackup#66]
It would be useful to scan PGDATA for changed blocks and replace only them instead of copying whole instance anew.

**Comment by Extortioner01** [comment]
Добрый день!
В нашей конфигурации бэкап снимается с физической реплики. Теперь давайте представим, что реплика безнадёжно отстала - мониторинг не сработал, файлы wal, необходимые для того, чтобы реплика догнала мастер отсутствуют (понятно, что настроены всякие archive_command, мониторинг и прочие вещи, которые практически исключают такой исход, но тем не менее беда случилась и реплика отстала).
На реплике мы можем посмотреть START LSN и STOP LSN последнего доступного бэкапа.
Можем ли мы используя pg_probackup снять инкрементальный бэкап (видимо, в режиме DELTA) с мастера, начиная с известного нам LSN, после чего подложить его на реплику и каким-то образом догнать состояние реплики до мастера?

**Comment by uspen** [comment]
Здравствуйте! Спасибо за отличный продукт!

Очень хотелось бы иметь возможность восстановить backup в непустой кластер. Наподобие --delta у pgbackrest

Задача утилиты резервного копирования  не только качественно делать backup, но и, иногда более важно, быстро его восстановить

**Comment by gsmol** [comment]
@uspen, @Extortioner01, cпасибо за ваш фидбэк.
Инкрементальное восстановление будет в версии 2.4.0.

**Comment by gsmol** [comment]
First results:
```
simple  restore:
INFO: Backup files are restored. Transfered bytes: 7533MB, time elapsed: 58s
INFO: Restore overwriting ratio (less is better): 100% (7533MB/7501MB)

incremental:
INFO: Backup files are restored. Transfered bytes: 120kB, time elapsed: 22s
INFO: Restore overwriting ratio (less is better): 0% (120kB/7501MB)

incremental-lsn:
INFO: Backup files are restored. Transfered bytes: 16MB, time elapsed: 8s
INFO: Restore overwriting ratio (less is better): 0% (16MB/7501MB)
```

**Comment by gsmol** [comment]
More results:
```
incremental
INFO: Backup files are restored. Transfered bytes: 1074MB, time elapsed: 28s
INFO: Restore incremental ratio (less is better): 14% (1074MB/7513MB)

incremental-lsn:
INFO: Backup files are restored. Transfered bytes: 1078MB, time elapsed: 12s
INFO: Restore incremental ratio (less is better): 14% (1078MB/7501MB)
```

**Comment by gsmol** [comment]
Merged.

**Comment by gsmol** [comment]
rsync vs incremental restore, 15 GB:
rsync  9m45s
vs
pbk 57s. Transfered bytes: 962MB, incremental ratio (less is better): 6% (962MB/15GB)

**Comment by gsmol** [comment]
@Extortioner01 
> Можем ли мы используя pg_probackup снять инкрементальный бэкап (видимо, в режиме DELTA) с мастера, начиная с известного нам LSN, после чего подложить его на реплику и каким-то образом догнать состояние реплики до мастера?
>
Эта фича пилится в рамках https://github.com/postgrespro/pg_probackup/issues/277
