### ISSUE TITLE
Backup aging

### ISSUE THREAD

**Issue by alexign** [postgrespro/pg_probackup#68]
Hello!
I think pg_probackup need something like backup aging mechanism. 
How it should work:

1. Let say at the 1 day of month we make full backup of database and set its max age 12 months(or 365 day whenever). Lets it id is 1 
2. After that  we also make full backup say at every sunday and set its max age at 30 days their id is say 10 20 30 40
3. During week we make incremental backup.
4. Every day we have retention policy work and delete our expired backup with their age > max_age we set in p 1 and 2

After 30 days have passed we have in our backup repo something like that:

Full backup (id 1 29 or more days ago) ==> Full backup (id 10 28 days ago) ==> Full backup (id 20 21 days ago) ==>Full backup (id 30 14 days ago) ==>Full backup (id 40 7 days ago) ==>Incremental backup ==> Incremental backup...==> now
After 30 days have passed and retention mechanism clear aged backup we have in our repo:
Full backup (id 1) ==> Full backup (id 20 ) ==> Full backup (id 30) ==>Full backup (id 40) ==> Full backup (id 50 ) ==> Incremental backup ==> Incremental backup...==> now
As you can see there is no full backup with id = 10 because its age is greater than its max_age set on p 2. and retention policy removed it from backup chain 
and so on...

With this feature in mind pg_probackup can make some simple(or maybe complex) backup archive policy without using any external tools.

**Comment by gsmol** [comment]
Sounds interesting, but how exactly pinning should work?
I think, the most obvious way is to use time, for example: `--pinned-for=number_of_days` or `--pinned-until=timestamp`.

**Comment by gsmol** [comment]
And we will need an interface for backup manipulation.

**Comment by alubennikova** [comment]
> And we will need an interface for backup manipulation. Something like separate command `set-backup`

I would rather we reuse existing subcommand.
pg_probackup set-config -B backupdir --instance instance_name [options] - to set instance specific config

pg_probackup set-config -B backupdir --instance instance_name -i backup_id [options] - to set backup specific config

**Comment by gsmol** [comment]
> I would rather we reuse existing subcommand.

I think it will be too complicated from user point of view. I vote for separate command =)

**Comment by triwada** [comment]
> 
> 
> > I would rather we reuse existing subcommand.
> 
> I think it will be too complicated from user point of view. I vote for separate command =)

+1
Every organization has own backup policy, and the complex of this policy is solved by backup script. So need only  an interface for backup manipulation

**Comment by gsmol** [comment]
Currently implementling the following interface:
1. Set the aging via command `set-backup`:
```
pg_probackup set-backup --instance node -i PYFEF4 --ttl=30d
```
2. Show via new backup attribute `expire-date` :
pg_probackup show --instance node -i PYFEF4
...
expire-time = '2019-010-25 09:38:16+03'
...
3. Unset:
```
pg_probackup set-backup --instance node -i PYFEF4 --ttl=0
```

**Comment by gsmol** [comment]
4. Additional parameter `--expire-time`:
``
pg_probackup set-backup --instance node -i PYFEF4 --expire-time='2020-01-01 00:00:00+03'
```

**Comment by gsmol** [comment]
Review and testing are greatly appreciated.

**Comment by alubennikova** [comment]
0) I've fixed several obvious typos in the documentation in error messages.

1) From documentation:
` -ttl ... Supported units: ms, s, min, h, d (s by default)`

I suggest changing the default unit to days like in --retention-window.
It's highly unlikely that someone wants to keep a backup for seconds rather than days.
Maybe we can even remove other units at all.

2) 
```	if (target_backup->recovery_time <= 0)
		elog(ERROR, "Failed to set 'expire-time' for backup %s: invalid 'recovery-time'",
						base36enc(backup_id));
```

Is it possible that valid backup has invalid recovery time? I think this message can be more informative. And also it's worth to mention this behavior in the documentation.
I moved this check to pin_backup() so that do_backup() and do_set_backup() were consistent.

3) parse_time is quite strange.
Are you ok with changing this
```
	i = sscanf(tmp, "%04d %02d %02d %02d %02d %02d%1s",
		&tm.tm_year, &tm.tm_mon, &tm.tm_mday,
		&tm.tm_hour, &tm.tm_min, &tm.tm_sec, junk);
	free(tmp);

	if (i < 1 || 6 < i)
		return false;
```
to 
``` if (i != 6) return false; ```  or at least ``` if (i < 3 and i > 6) return false; ```

4) Let's check that `expire_time` > `recovery_time` when setting it
and throw a warning if it isn't.

**Comment by gsmol** [comment]
> I suggest changing the default unit to days like in --retention-window.
> It's highly unlikely that someone wants to keep a backup for seconds rather than days.
> Maybe we can even remove other units at all.
>
This is no trivial task, I`ve tried to switch to 'day' as a default unit, but apparently our unit parse-engine is bugged. I can try to tackle it, if you think it`s worth it.

**Comment by gsmol** [comment]
> Is it possible that valid backup has invalid recovery time?
Highly unlikely, but it is good to be sure before doing something potentially destructive.

> parse_time is quite strange. Are you ok with changing this
>
Sure.

> Let's check that expire_time > recovery_time when setting it
and throw a warning if it isn't.
>
Should we? It could be a handy why to unpin a backup.

**Comment by gsmol** [comment]
Merged.
