### ISSUE TITLE
Windows: pg_probackup не видит прошлых бэкапов

### ISSUE THREAD

**Issue by ykurenkov** [postgrespro/pg_probackup#73]
Бэкапы делаются шедулером. В воскресенье выполнен был полный бэкап. При запуске в понедельник и во вторник инкрементального бэкапа pg_probackup сообщает, что нет полного и завершается с ошибкой. Однако по show он их показывает. pg_probackup_5 2.0.27 (Postgres Pro 10.7.1 standard) - pg_probackup5.exe

Отмечу, что это поведение абсолютно идентично на мастере и слейве. На мастере запустил выполнение полгного бэкапа.

![Screenshot from 2019-05-22 09-30-35](https://user-images.githubusercontent.com/25895491/58152132-625fb200-7c74-11e9-881a-d421bd09b51c.png)
[pg_probackup-Mon.log](https://github.com/postgrespro/pg_probackup/files/3205921/pg_probackup-Mon.log)
[pg_probackup-Sun.log](https://github.com/postgrespro/pg_probackup/files/3205922/pg_probackup-Sun.log)
[pg_probackup-Tue.log](https://github.com/postgrespro/pg_probackup/files/3205923/pg_probackup-Tue.log)

**Comment by gsmol** [comment]
Да, он ищет полный бэкап в том же таймлайне, что и бэкапируемый инстанс.
Мы пока не умеем делать инкрементальные цепочки на несколько таймлайнов

**Comment by ykurenkov** [comment]
Ага, я делал promote на сервере. Это послужило причиной?

**Comment by gsmol** [comment]
Ага

**Comment by ykurenkov** [comment]
Спасибо. Пополнил багаж знаний.
