### ISSUE TITLE
Question on Documentation

### ISSUE THREAD

**Issue by jobinau** [postgrespro/pg_probackup#81]
Documentation says:
"DELTA backup. In this mode, pg_probackup read all data files in PGDATA directory and only those pages that where changed since previous backup, are copied"
Those pages or Those files?

**Comment by gsmol** [comment]
> Those pages or Those files?

Those pages, all incremental backup modes in pg_probackup are page-level

**Comment by gsmol** [comment]
Do you have any more questions? Can we close this issue?
