### ISSUE TITLE
[feature] backup encryption

### ISSUE THREAD

**Issue by gsmolk** [postgrespro/pg_probackup#87]
New env variables:
 - PGPROBACKUP_PGP_PUBLIC_KEY_PATH
 - PGPROBACKUP_PGP_SECRET_KEY_PATH

New options:
  - pgp-public-key-path
  - pgp-secret-key-path

**Comment by gsmol** [comment]
Branch https://github.com/postgrespro/pg_probackup/tree/encryption

**Comment by sgrinko** [comment]
Каково состояние на сейчас?

**Comment by gsmol** [comment]
Попробуем поднять приоритет

**Comment by funny-falcon** [comment]
Пока исключаем из планов. Может вернём позже.
