### ISSUE TITLE
Залипшие бэкапы в состоянии RUNNING

### ISSUE THREAD

**Issue by ykurenkov** [postgrespro/pg_probackup#97]
![image](https://user-images.githubusercontent.com/25895491/61289962-548d5f80-a7d3-11e9-8316-b60e82d81604.png)
Бэкап производится на NAS. С ним возникали технические проблемы, в результате чего остались в состоянии RUNNING PTKCO2 и PU6KO1. И что такое DONE у PTXBC1?

**Comment by ykurenkov** [comment]
Запустил валидацию PTXBC1

![image](https://user-images.githubusercontent.com/25895491/61290765-53f5c880-a7d5-11e9-8a7f-6d7b00c578ca.png)

После этого он получил статус CORRUPT. При этом потребовались права Администратора потому что

![image](https://user-images.githubusercontent.com/25895491/61290905-ad5df780-a7d5-11e9-9395-5206df94778d.png)

На текущий момент PID 15648 - postgres.exe, а это значение прописано в backup.pid

**Comment by ykurenkov** [comment]
Самое главное забыл
![image](https://user-images.githubusercontent.com/25895491/61291314-e185e800-a7d6-11e9-89c9-6db2f43791be.png)

**Comment by ykurenkov** [comment]
Провалидировал PTXBC1 - он стал ОК. Удалил PTKCO2 и PU6KO1.  Выполнил expire и запустил FULL. Надеюсь, что на этом мой ремонт закончен и мои действия были верны.

**Comment by gsmol** [comment]
DONE - это значит, что бэкап завершился, и, если Вы не запускали бэкап с флагом `--no-validate`, в данный момент идет его валидация

https://user-images.githubusercontent.com/25895491/61290905-ad5df780-a7d5-11e9-9395-5206df94778d.png
Вот это плохо, мы используем 0 сигнал чтобы получить статус процесса по pid`у

**Comment by gsmol** [comment]
А какого рода технические проблемы были с NAS ?

**Comment by ykurenkov** [comment]
Со стороны NAS суть проблемы не скажу, а клиенту приходила ошибка, что указанный CIFS не существует, в другой раз отсутствовал доступ в связи невозможностью автризоваться.  pg_probackup в качестве параметра -B получал путь в UNC (\\NAS\Share).

**Comment by ykurenkov** [comment]
> Вот это плохо, мы используем 0 сигнал чтобы получить статус процесса по pid`у
В данном случае этот PID уже принадлежал совсем другому процессу. Просто так совпало, что под этим PID совсем другой процесс уже работал. Может у этого процесса и имя проверять?

**Comment by gsmol** [comment]
> Удалил PTKCO2 и PU6KO1. 
>
Удалили вручную или через `delete`?

**Comment by ykurenkov** [comment]
delete использовал

**Comment by gsmol** [comment]
А, это отлично.
Что делать в случае, если система переиспользовала pid, я, честно говоря, затрудняюсь сказать. Имя процесса проверять бессмысленно, ведь это может быть в том числе и probackup, просто другой.

**Comment by ykurenkov** [comment]
Да, возможно эта задача и не формализуется :( А если какой-то дополнительный достаточно уникальный признак в pid файл писать?

**Comment by gsmol** [comment]
Надо будет над этим подумать.
Закрываем задачу?

**Comment by ykurenkov** [comment]
Например, время старта процесса мы везде можем получить?

Думаю, можно закрывать.
