### ISSUE TITLE
Backup from Standby/Replica.

### ISSUE THREAD

**Issue by pinakesh** [postgrespro/pg_probackup#98]
Backup from Standby/Replica - is it possible to take incremental backup (type PAGE) from standby as it seems to me only Full and DELTA backup is possible from standby (using --stream option) but I need PAGE backup as I need archived WAL files for PITR

**Comment by pinakesh** [comment]
I am using -
vanilla postgres -> psql (PostgreSQL) 11.0 
pg_probackup -> pg_probackup-11 2.1.2 (PostgreSQL 11.3)

**Comment by pinakesh** [comment]
If I try to do a PITR using FULL and DELTA backup, I get below error ::

[postgres@appftd04cn ~]$
[postgres@appftd04cn ~]$ pg_probackup-11 show -B /u02/pb/postgres/pg_pro_backup_dir --instance pgpro_stby1
======================================================================================================================================
 Instance     Version  ID      Recovery Time           Mode   WAL      Current/Parent TLI  Time  Data   Start LSN    Stop LSN  Status
======================================================================================================================================
 pgpro_stby1  11       PURT6G  2019-07-17 01:13:21-04  DELTA  STREAM   1 / 0                10s  84MB  0/1430F930  0/180011F8  OK
 pgpro_stby1  11       PURT2F  2019-07-17 01:08:59-04  DELTA  STREAM   1 / 0                87s  69MB  0/1430F930  0/17000028  OK
 pgpro_stby1  11       PURSRL  2019-07-17 01:04:35-04  FULL   STREAM   1 / 0                86s  94MB  0/12000060  0/13000028  OK
[postgres@appftd04cn ~]$
[postgres@appftd04cn ~]$
[postgres@appftd04cn ~]$ pg_probackup-11 restore -B /u02/pb/postgres/pg_pro_backup_dir --instance pgpro_stby1 -D /u02/pb/postgres/pg_pro_backup_dir_recovered --recovery-target-time="2019-07-17 01:13:12-04:00"
INFO: Validating parents for backup PURT2F
INFO: Validating backup PURSRL
INFO: Backup PURSRL data files are valid
INFO: Validating backup PURT2F
INFO: Backup PURT2F data files are valid
ERROR: WAL archive is empty. You cannot restore backup to a recovery target without WAL archive.
[postgres@appftd04cn ~]$

**Comment by pinakesh** [comment]
If I try to do PITR using FULL and DELTA backups I get below error ::

[postgres@server1 ~] pg_probackup-11 restore -B /u02/pb/postgres/pg_pro_backup_dir --instance pgpro_stby1 -D /u02/pb/postgres/pg_pro_backup_dir_recovered --recovery-target-time="2019-07-17 01:13:12-04:00"
INFO: Validating parents for backup PURT2F
INFO: Validating backup PURSRL
INFO: Backup PURSRL data files are valid
INFO: Validating backup PURT2F
INFO: Backup PURT2F data files are valid
ERROR: WAL archive is empty. You cannot restore backup to a recovery target without WAL archive.
[postgres@server1 ~]$

**Comment by gsmol** [comment]
Hello!

> Backup from Standby/Replica - is it possible to take incremental backup (type PAGE) from standby as it seems to me only Full and DELTA backup is possible from standby (using --stream option) 
>

Sure you can take PAGE backup from standby:
https://github.com/postgrespro/pg_probackup/blob/master/Documentation.md#backup-from-standby

PAGE backup rely on WAL to detect block change, so WAL archiving is mandatory:
https://github.com/postgrespro/pg_probackup/blob/master/Documentation.md#setting-up-continuous-wal-archiving 

> If I try to do PITR using FULL and DELTA backups I get below error ::
> 
> [postgres@server1 ~] pg_probackup-11 restore -B /u02/pb/postgres/pg_pro_backup_dir --instance pgpro_stby1 -D /u02/pb/postgres/pg_pro_backup_dir_recovered --recovery-target-time="2019-07-17 01:13:12-04:00"
> INFO: Validating parents for backup PURT2F
> INFO: Validating backup PURSRL
> INFO: Backup PURSRL data files are valid
> INFO: Validating backup PURT2F
> INFO: Backup PURT2F data files are valid
> ERROR: WAL archive is empty. You cannot restore backup to a recovery target without WAL archive.

You can use PITR regardless(!!) of backup type (FULL, DELTA or PAGE). For PITR you only need to setup WAL archiving.
The fact that PAGE mode is also rely on WAL archiving is coincidence and does`t mean, that PITR can be used only when restoring PAGE backup.

**Comment by pinakesh** [comment]
Hi Gsmol,

Thanks for reverting.

I have just a few followup questions 

I understand in order to set up WAL archival I have to set archive_mode on and the archive command as below :-

 archive_command = 'pg_probackup archive-push -B backup_dir --instance instance_name --wal-file-path %p --wal-file-name %f [remote_options]'

Now, should I set this  archive_command in 
i> both primary and standby?
ii> or in only primary?
iii> or in only standby?  -- (i don't think it will work as pg_start_backup() and pg_stop_backup wont do wal log switch in standby)

If I need to setup in primary then I have to configure pg_probackup in primary as well, but my need was just to setup pr_probackup only on standby server and then get backup (of both datafiles and archived wal files) from the standby itself - is it possible?

Please help me with the command of how to send archived wal files to the directory 'standby_server:backup_dir/wals' which in this example will be 'server1:/u02/pb/postgres/pg_pro_backup_dir/wals'

Thanks

**Comment by gsmol** [comment]
> Now, should I set this archive_command in
> i> both primary and standby?
> ii> or in only primary?
> iii> or in only standby?

Only on standby.

>i don't think it will work as pg_start_backup() and pg_stop_backup wont do wal log switch in standby)
>
It should be a problem only if there is very small WAL-traffic coming from primary, so WAL segments are slow to fill up and thus are very infrequently send to archive.
Is it your case?

> Please help me with the command of how to send archived wal files to the directory 'standby_server:backup_dir/wals' which in this example will be 'server1:/u02/pb/postgres/pg_pro_backup_dir/wals'
>

archive_command = 'pg_probackup-11 archive-push -B /u02/pb/postgres/pg_pro_backup_dir --instance pgpro_stby1 --remote-proto=ssh --remote-host=server1 --wal-file-path %p --wal-file-name %f'

**Comment by pinakesh** [comment]
yes...I am just testing if it works before using it on DEV/PROD...after starting the backup from standby I tried manually switching logs on primary (select pg_switch_wal()) but still it failed.

Would it help if I start a backup on standby (around 2gb incremental data ) and then start inserting around 1GB of data on the primary?

**Comment by gsmol** [comment]
Is archiving working at all on standby?
Is `archive_mode` is set to `always` on standby?
Can you copy the content of standby logfile?

**Comment by pinakesh** [comment]
Hi Gsmol,

Hope you are doing well.

Many thanks for your help, now its working after setting archive_mode=always on standby.

Just needed to clear up a few more things?

1> In your earlier comment you mentioned that pg_probackup only needs to be setup in standby server (if we want to backup from standby), so my question is can we make the same configuration (pg_probackup directories, postgresql.conf, etc) in Primary server as well, so as to make sure transparent switchover/failover i.e. without any need to change configurations. (not sure if we can use archive_mode=always in primary)?

2> Will pg_probackup be able to recover from errors and resume backup in case of errors like (lack of free space, power outage, system restart, system hangs, etc)?

3> I understand there is an option --progress, but is it possible to monitor pg_probackup using :
	      i> Any Postgres table (similar to v$session_longops for RMAN in Oracle)
	      ii> Tools like Nagios/Icinga ??

4> Is encryption possible with pg_probackup? (I think it is not supported at the moment)

5> During backup process will pg_probackup prevent access to the database for readers or writers i.e. will there be any kind of locking on tables/tablespaces?

Regards,
Pinakesh

**Comment by gsmol** [comment]
Hello!
I`m fine, thanks for asking. I hope you are doing well too!

> 1> In your earlier comment you mentioned that pg_probackup only needs to be setup in standby server (if we want to backup from standby), so my question is can we make the same configuration (pg_probackup directories, postgresql.conf, etc) in Primary server as well, so as to make sure transparent switchover/failover i.e. without any need to change configurations.
>

Sure you can, but it is a bit costly approach, because with two `backup catalogs` running indepedently  total backup size will eat x2 disk space and also I/O comsuption will double; with no clear benefits other than simplicity of design.

Usually HA infrastructure comes with floating IP, so switchover/failover happens transparently for application. pg_probackup can also reply on floating IP to always connect to correct instance(master or replica) via ssh.

Is it possible in your case?

> (not sure if we can use archive_mode=always in primary)?
>
Sure you can:
https://www.postgresql.org/docs/current/runtime-config-wal.html#GUC-ARCHIVE-MODE

> 2> Will pg_probackup be able to recover from errors and resume backup in case of errors like (lack of free space, power outage, system restart, system hangs, etc)?
>
`Resume` feature is planned for 2.2.0 release, which will come out in the following month:
https://github.com/postgrespro/pg_probackup/issues/64

> 3> I understand there is an option --progress, but is it possible to monitor pg_probackup using :
i> Any Postgres table (similar to v$session_longops for RMAN in Oracle)
>
No, unfortunately. We are planning to be able to store metadata in separate database, but it is not happening any time soon.

ii> Tools like Nagios/Icinga ??
>
No, but you can file feature request and we will look into it.

> 4> Is encryption possible with pg_probackup? (I think it is not supported at the moment)
>
At this moment - no, there is a dev-branch but it is not production-ready:
https://github.com/postgrespro/pg_probackup/issues/87

> 5> During backup process will pg_probackup prevent access to the database for readers or writers i.e. will there be any kind of locking on tables/tablespaces?
>
No, pg_probackup takes physical backup, it works on filesystem level, so no locking of anything.

**Comment by gsmol** [comment]
Also I would recommend you the upgrade to the latest minor version 2.1.3

**Comment by gsmol** [comment]
Do you have any more questions?

**Comment by pinakesh** [comment]
Thanks a lot.

I don't have any more questions at the moment, if I do later can I post it in this ticket?

**Comment by gsmol** [comment]
I think it`s better to just create another ticket in this case.
It will make life easier for anyone looking for answers to similar question.

**Comment by pinakesh** [comment]
sure..will do...many thanks :)
