### ISSUE TITLE
feature for mark backup as keep forever

### ISSUE THREAD

**Issue by triwada** [postgrespro/pg_probackup#99]
it is usefull to have a feature for mark backup as "keep forever", so that backup is not deleted by retention policy.

**Comment by gsmol** [comment]
Hello!
Sounds useful, but maybe this problem can be solved via more general approach like this:
https://github.com/postgrespro/pg_probackup/issues/68

What do you think?

**Comment by triwada** [comment]
https://github.com/postgrespro/pg_probackup/issues/68 - yes, it looks more globally
